### ISSUE TITLE
Provide configuration parameter to set `samtools sort` memory per thread

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#109]
The user doc has a section on Troubleshooting: `samtools sort: couldn't allocate memory for bam_mem`...

If using more than one process (`nprocesses` > 1) you might get the error:

```
samtools sort: couldn't allocate memory for bam_mem
```

This leads to a failure to create `.bam` and `.bam.bai` files.

In this case, you may need to explicitly set the amount of memory per thread in calls to `samtools sort`.

Check how much free memory you have e.g.

```console
$ free --mega
              total        used        free      shared  buff/cache   available
Mem:           2017         684        1028           2         303        1181
Swap:           969         619         350
```

Divide the free memory by the number of processes, `nprocesses` e.g. 1024/4 = 256 MB.

Edit `riboviz/workflow.py` and change the lines:

```python
cmd_sort = ["samtools", "sort", "-@", str(run_config.nprocesses),
            "-O", "bam", "-o", bam_file, "-"]
```

to include the `samtools` flag `-m <MEMORY_DIV_PROCESSES>M` e.g.:

```python
cmd_sort = ["samtools", "sort", "-@", str(run_config.nprocesses),
            "-m", "256M",
            "-O", "bam", "-o", bam_file, "-"]
```
...this involves the user editing the source code which is not good! Add support for a configuration parameter (`samtools_memory: <MEMORY>`). If this configuration flag is present then add `-m <MEMORY>` to the `samtools sort` call.

**Comment by FlicAnderson** [comment]
Is this something that's worth fixing for the `nextflow` method rather than python (since we're now moving to Nextflow as the main method after riboviz version 2.0)? 

Perhaps something to do after specifying `nprocesses` for `cutadapt` in #216 ?

**Comment by mikej888** [comment]
Support for samsort_memory was added back at c73309b.
