### ISSUE TITLE
Create tags and releases for 1.0.0 and 1.1.0

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#12]
From #7.

- [ ] 1.0.0: version used for the 2017 paper.
- [x] 1.1.0: 340b9b592ba2d45b186d8e3705adc75e7e7aefcf, 31 Jan version prior to @mikej888 changes,

**Comment by mikej888** [comment]
Pending comment on #7 about commit hash of version used for 2017 paper.

**Comment by mikej888** [comment]
Tagged commit 340b9b592ba2d45b186d8e3705adc75e7e7aefcf as 1.1.0 and released (see [1.1.0](https://github.com/riboviz/RiboViz/releases/tag/1.1.0))

**Comment by mikej888** [comment]
Edward suggests:

* Early 2017 version, on BioArchive, with no pipeline, 0.9.0.
* prepRiboViz.sh pipeline version, for paper, 1.0.0.

@shahpr, @ewallace, please provide the commit hashes.

**Comment by kavousan** [comment]
@shahpr and @ewallace: we would still benefit from this.

**Comment by ewallace** [comment]
I suggest
* 0.8.0 for 2017 biorXiv submission: [39dae52](https://github.com/riboviz/RiboViz/commit/39dae52504ddd58a2b80ba3bb732ce4e3e3bbfd8)
* 0.9.0 more data for 2017 bioRXiv: [b1f0346](https://github.com/riboviz/RiboViz/commit/b1f03460482e57a5b30d1612bdf7ab45c993863b)
* 1.0.0 for 2017 paper, including prepRiboviz.sh: [83027ef9](https://github.com/riboviz/RiboViz/commit/83027ef9ccd9f4b88753f1c824ed3540b5deeb88)

@shahpr does this look ok?

**Comment by kavousan** [comment]
@shahpr: Mike has tagged as per above. Shall we consider this done or do you disagree with the tags?

**Comment by shahpr** [comment]
I agree with Edward's versioning.
