### ISSUE TITLE
Accelerate 2.0-beta release onto master branch for discoverability?

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#130]
Should we consider accelerating a 2.0-beta release onto master branch to enable testing/discoverability?

Related to #99 - Build release 2.0

**Problem**: Currently new / inexperienced users can't easily discover the new features in develop as master branch is landing page, and often end up trying to install the older master content without being aware of newer content and additional features - potentially worth documentation update to clarify ongoing development occurs in develop branch vs stable content in master branch? 

Also worth adding something to the developer guide around RiboViz approach to development vs master branches?

**Comment by mikej888** [comment]
`develop` has been merged into `master`.

`docs/developer/git-branching-model.md` describes the branching model used.
