### ISSUE TITLE
Add helpful error if attempt to run RiboViz with Python 2

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/RiboViz#132]
I just rediscovered this proto-issue in my notes from a couple of months back (sorry!), and thought I'd flag it for discussion/prioritisation.  Happy to close if we decide it wouldn't be useful. 

Since we've now deprecated Python 2 support (as in #54) and those changes have been merged in (#93), it might be worth adding an obvious error if the user tries running it in Python 2? This might be (hopefully) not too difficult since we're identifying all the software versions pretty early on as a result of the wizardry by @mikej888.

This would be helpful now we're officially over to Python3 and would give user a hand in identifying why there are problems.

**Comment by mikej888** [comment]
Merged via pull request #143.
