### ISSUE TITLE
Break fork relationship between shahpr/RiboViz and riboviz/RiboViz

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#135]
At present on GitHub riboviz/RiboViz is marked as a fork of shahpr/RiboViz. To promote riboviz/RiboViz as the canonical repository we need to break this explicit relationship.

To do this requires contacting GitHub Support (from StackOverflow's [Delete fork dependency of a GitHub repository](https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository)).

@shahpr is it OK if we break the fork from your repository in this way?

**Comment by mikej888** [comment]
Emailed @shahpr and CCd @ewallace

**Comment by kavousan** [comment]
@shahpr: can you please consider giving us permission to do this? Thanks.

**Comment by ewallace** [comment]
@shahpr just sent the request to github support.

**Comment by shahpr** [comment]
The fork dependency has been severed.

**Comment by mikej888** [comment]
Thanks :-)
