### ISSUE TITLE
Investigate whether Shiny website directory can be purged from repository history

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#139]

**Comment by mikej888** [comment]
GitHub's [Removing sensitive data from a repository](https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository) describes a `git filter-branch` command but they recommend the open source [BFG repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) tool.

From the docs, this allows purging of blobs or other files by either name and/or whether they exceed a certain size. 

Without yet having experimented with it, the only evident downside is that it creates new commit hashes for historical commits, as it has to recreate the history without the purged files. Any links we have from issues to specific commit hashes would break. I don't think this should be a blocker. We can keep a copy of the repository before the purge. If in the rare event we need to follow a commit hash link from an old issue then we just look up that commit has in the repository copy.

I'll experiment with BFC Repo-Cleaner in due course.

**Comment by mikej888** [comment]
Key points from this afternoon's explorations. This used https://github.com/mikej888/riboviz-purge.

Problematic files/folders must not be present in current commits as these are considered to be "protected". These need to be removed using `git rm` and the changes commited i.e. `Shiny/`, `Frontend/` and `Data/` need to be removed from `master` and `website/` from `developer` and other branches. Once done...

Get bare repository:
```console
$ git clone --mirror https://github.com/mikej888/riboviz-purge.git
$ du -sm riboviz.git riboviz-purge.git
368	riboviz.git
```
Download BFG-Repo-Cleaner:
```console
$ wget https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar
$ java -jar bfg-1.13.0.jar 
bfg 1.13.0
Usage: bfg [options] [<repo>]
...
```
Clean commits, branches and tags:
```console
$ java -jar bfg-1.13.0.jar --delete-folders "{website,Shiny,Frontend,Data}" riboviz-purge.git
```
Physically remove the requested folders:
```console
$ cd riboviz-purge.git
$ git reflog expire --expire=now --all && git gc --prune=now --aggressive
$ cd ..
$ du -sm riboviz-purge.git
124	riboviz-purge.git
```
Bare repository is now far smaller!

Push updates:
```console
$ cd riboviz-purge.git
$ git push
$ cd ..
```
Check size of repositories for current RiboViz repository and the purged one:
```console
$ git clone https://github.com/riboviz/riboviz
$ git clone https://github.com/mikej888/riboviz-purge riboviz-purge-check
$ du -sm riboviz riboviz-purge-check
887	riboviz
232	riboviz-purge-check
```
Repository is now far smaller!

Check commits at significant points:

```console
# Commit immediately prior to website/ removal in "develop" branch.
# Date:   Fri Feb 21 13:40:30 2020 +0000
$ git checkout 7738f8c997d81c1550de23d6774b38b84b9836f2
$ ls
code-docs  docs     LICENSE    riboviz    rscripts
data       install  README.md  rmarkdown  vignette

# Commit immediately prior to Shiny/ Frontend/ Data/ removal in "master" branch.
# Date:   Mon Sep 16 16:48:32 2019 -0400
$ git checkout 66baeb6cc78f4c6484704749c371e0b0df5e7646
$ ls
docs  install  LICENSE  README.md  scripts  vignette

# Commit immediately prior to creating website/ folder.
# Date:   Tue Aug 20 16:10:53 2019 +0100
$ git checkout 9fa494a71624cadfc83d9c252f938fcf45581df8
$ ls
data  install  pyscripts  riboviz    rscripts  vignette
docs  LICENSE  README.md  rmarkdown  tests

# Date:   Tue Aug 20 02:47:05 2019 -0700
$ git checkout f554c7c05431162ba5fd4e918d6646c2786b379b
$ ls
data  install  pyscripts  riboviz    rscripts  vignette
docs  LICENSE  README.md  rmarkdown  tests

# Commit immediately before my first ever commit.
# Date:   Thu Jul 26 15:03:40 2018 -0400
$ git checkout 4db10776ab0e90de259b776491b63704943c6739
$ ls
LICENSE  README.md  scripts  vignette
```

No trace of the Shiny-related folders.

Explore https://github.com/mikej888/riboviz-purge for the updated example.

**Notes for doing this "for real"**

* Create a new `riboviz/riboviz-with-shiny` repository and push all commits, branches and tags to it (this can serve as a backup):

```console
$ cd riboviz
$ git remote add riboviz-with-shiny https://github.com/riboviz/riboviz-with-shiny
$ git push riboviz-with-shiny --all
$ git push riboviz-with-shiny --tags
```

* Everyone will need to take fresh forks/clones of `riboviz/riboviz` before continuing development.
* Links to specific commit hashes in `riboviz/riboviz` issues will no longer work as BFG-Repo-Cleaner creates new commit hashes. If there is really a need to explore such a link from an issue then a developer can just edit the link and use `riboviz/riboviz-with-shiny`.

I think this seems to be what we're after. @ewallace, @FlicAnderson, @kavousan comments welcome!

**Comment by FlicAnderson** [comment]
This seems pretty reasonable and (fingers crossed) pain-free and not an actual crawling chaos.

Bit of a shame we'll lose the commit hashes, but as you say, we'll have the old copy for reference and can add a bit to the developer documentation re: that.  

Is it worth adding a small note about what's been done (and existence of old copy with original commit hashes) on the Readme?  Or is this something that a 'typical user' wouldn't need to know about?

**Comment by mikej888** [comment]
I don't think it is something for the README.md. It only relates to developers and then only if they actually go into a specific issue in enough depth to click on a commit hash link within it.

**Comment by mikej888** [comment]
Done, backup is in https://github.com/riboviz/riboviz-20200304-pre-website-removal
