### ISSUE TITLE
Answer regression test-related questions about RiboViz

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#14]
@ewallace, @shahpr 

1) Are `scripts/trim_5p_mismatch.pl` and `scripts/trim_5p_mismatch_sam.pl` deprecated by `trim_5p_mismatch.py`? If so, can they be deleted?

2) Is `script_for_transcript_annotation.nb.html` just the HTML form of `script_for_transcript_annotation.Rmd`?

3) What, if anything, should be done with `script_for_transcript_annotation.Rmd`? Should the code embedded in there be extracted into `.R` functions at some point?

4) The BedGraph format, [BedGraph Track Format](https://genome.ucsc.edu/goldenPath/help/bedgraph.html), states that:

> BedGraph data are preceded by a track definition line...

> The track type is REQUIRED, and must be bedGraph:
>
> type=bedGraph

This isn't defined in the RiboViz BedGraph files. Should it be?

5) BedGraph values in the 4th, data value, column could, according to the specification, be integer or real values. Are there ever reals in these files when output by RiboViz or are they only ever integers?

6) Is the order of entries in the following types of file significant or can the order be ignored when comparing these files?

* FASTQ
* GFF3
* SAM (ignoring any header)
* FASTA index

7) Is the order of rows, after the header row, in each of the types of TSV files output by RiboViz significant or can the order be ignored when comparing these files?

* `TPMs_collated.tsv`
* `<PREFIX>_3nt_periodicity.tsv`
* `<PREFIX>_codon_ribodens.tsv`
* `<PREFIX>_pos_sp_nt_freq.tsv`
* `<PREFIX>_pos_sp_rpf_norm_reads.tsv`
* `<PREFIX>_read_lengths.tsv`
* `<PREFIX>_tpms.tsv`

8) To within what number of decimal places should non-integer numeric data values in each of the types of TSV files output by RiboViz be considered equal?

`TPMs_collated.tsv`:

```
ORF	WTnone	WT3AT
YAL001C	116.7	953
YAL002W	212.8	365.8
```

`<PREFIX>_3nt_periodicity.tsv`:

```
Pos	Counts	End
-24	0	5'
-23	0	5'
```

`<PREFIX>_codon_ribodens.tsv`:

```
AA	Codon	tRNA	tAI	Microarray	RNA.seq	A	P	E
K	AAA	7	0.431034	222273	82386	0.624663450336652	0.648007593904554	0.611661754463277
N	AAC	10	0.615764	378101	110849	0.415972879217912	1.30686729790977	0.988643300065999
```

`<PREFIX>_pos_sp_nt_freq.tsv`:

```
Length	Position	Frame	A	C	G	T
10	1	0	0	0	0	0
10	2	0	0	0	0	0
```

`<PREFIX>_pos_sp_rpf_norm_reads.tsv`:

```
Position	Mean	SD	End
1	0.114900896763824	0.114900896763824	5'
2	1.75191797936548	1.01523280394192	5'
```

`<PREFIX>_read_lengths.tsv`:

```
Length	Counts
10	0
11	0
```

`<PREFIX>_tpms.tsv`:

```
ORF	readcount	rpb	tpm
YAL001C	19	0.00538243626062323	953.022776609483
YAL002W	8	0.00206611570247934	365.829752221778
```

9) Edward, I recall you mentioned adding a flag to `check_fasta_gff.py` for some purpose. If so, what flag and for what purpose?

**Comment by mikej888** [comment]
1) Yes, these are deprecated.

3) This is one-time preprocessing when a new organism is brought on board. As this is a custom task it won't be reused as-is but heavily customised. This can be documented.

4) These are made by `bedtools genomecov`. This may not matter. Check online if others have raised this as an issue.

5) Edward only every uses Bedgraphs as counts, so they will be integers.

**Comment by ewallace** [comment]
9. Flag should be "startcodons", with default value "ATG". We can then replace that by a string of multiple start codons if required, e.g. [ "ATG", "TTG", "ACG"].

**Comment by ewallace** [comment]
> 6. Is the order of entries in the following types of file significant or can the order be ignored when comparing these files?
> 
> FASTQ
For the important information, the order is not significant in FASTQ. 

> GFF3
Conventionally the GFF3 would be sorted by chromosome and position. I don't think we have a gff3 output that needs to go in the test, do we?

> SAM (ignoring any header)
Sorted bam files, the order matters. This means that the bam files in the output directory (product of  `samtools sort -@ ${nprocesses} -O bam -o ${fn_out}.bam`) the order matters. For others the order might differ depending on any parallelization.

> FASTA index
I have no idea.

**Comment by mikej888** [comment]
GFF3 files are output by script_for_transcript_annotation.Rmd (but as 2. states this is used for one-time preprocessing)

**Comment by mikej888** [comment]
For 4. The BedGraph format, BedGraph Track Format, see #22.

**Comment by mikej888** [comment]
For 2) Is `script_for_transcript_annotation.nb.html` just the HTML form of `script_for_transcript_annotation.Rmd`?

Yes it is HTML form.

For 7) Is the order of rows, after the header row, in each of the types of TSV files output by RiboViz significant or can the order be ignored when comparing these files?

```
TPMs_collated.tsv - NO
WT3AT_3nt_periodicity.tsv - YES
WT3AT_codon_ribodens.tsv - YES
WT3AT_pos_sp_nt_freq.tsv - YES
WT3AT_pos_sp_rpf_norm_reads.tsv - YES
WT3AT_read_lengths.tsv - YES
WT3AT_tpms.tsv - NO
```

For 8) To within what number of decimal places should non-integer numeric data values in each of the types of TSV files output by RiboViz be considered equal?

* 4 decimal places is more than enough.
