### ISSUE TITLE
Confirm author and funder list for README.md

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#148]
Drafted from publicly available information...

## Contributors

* Edward Wallace, Felicity Anderson: [The Wallace Lab](https://ewallace.github.io/), The University of Edinburgh
* Premal Shah, John Favate, Tongji Xing: [The Shah Lab](https://theshahlab.org/), Rutgers University
* Liana Lareau, Amanda Mok: [The Lareau Lab](http://www.lareaulab.org/), University of California, Berkeley
* Kostas Kavousannakis, Mike Jackson: [EPCC](https://www.epcc.ed.ac.uk/), The University of Edinburgh:
* Oana Carja, Joshua Plotkin: The University of Pennsylvania:

## Funding

Development of RiboViz has been, and is currently, supported by the following funders.

May 2019 to April 2022

BBSRC grant awarded to Edward Wallace and NSF/BIO grant awarded to Premal Shah and Liana Lareau as a [BBSRC-NSF/BIO Lead Agency](https://bbsrc.ukri.org/funding/filter/2018-nsfbio-lead-agency-scheme/) collaboration.

August 2018

Assistance from the Software Sustainability Institute. The work carried out by the Software Sustainability Institute is supported by the UK Engineering and Physical Sciences Research Council (EPSRC) through grant EP/H043160/1 and EPSRC, BBSRC and ESRC Grant EP/N006410/1 and EPSRC, BBSRC, ESRC, NERC, AHRC, STFC and MRC grant EP/S021779/1.

January 2016 to October 2017 (1.0.0)

Penn Institute for Biomedical Informatics grant awarded to Oana Carja; the European Union's Horizon 2020 research and innovation programme under the Marie Sklodowska-Curie grant agreement No 661179 awarded to Edward Wallace; funding from the David & Lucille Packard foundation and the Army Research Office (W911NF-12-1-0552) awarded to Joshua Plotkin; NIH grant R35 GM124976 and start-up funds from Human Genetics Institute of New Jersey and Rutgers University awarded to Premal Shah.

October 2016 to January 2017 (0.8.0)

Start-up funds from Human Genetics Institute of New Jersey and Rutgers University awarded to Premal Shah; Penn Institute for Biomedical Informatics grant awarded to Oana Carja; funding from the David & Lucille Packard foundation, Army Research Office, and DARPA, awarded to Joshua Plotkin.

## Funding (more succinct)

Development of RiboViz has been, and is currently, supported by the following funders.

* [BBSRC-NSF/BIO Lead Agency](https://bbsrc.ukri.org/funding/filter/2018-nsfbio-lead-agency-scheme/) collaboration funded by BBSRC and NSF/BIO.
* The Software Sustainability Institute, supported by the UK Engineering and Physical Sciences Research Council (EPSRC) through grant EP/H043160/1 and EPSRC, BBSRC and ESRC Grant EP/N006410/1 and EPSRC, BBSRC, ESRC, NERC, AHRC, STFC and MRC grant EP/S021779/1.
* Penn Institute for Biomedical Informatics grant.
* European Union's Horizon 2020 research and innovation programme under Marie Sklodowska-Curie grant agreement No 661179.
* David & Lucille Packard foundation.
* Army Research Office (W911NF-12-1-0552)
* NIH grant R35 GM124976.
* Start-up funds from Human Genetics Institute of New Jersey and Rutgers University.

---

**Comment by shahpr** [comment]
Riboviz is also currently supported by NIH grant R35 GM124976 awarded to PS (Oct 2017 - Current). (Support for John Favate, and hosting costs).

**Comment by ewallace** [comment]
BBSRC grant number is *BB/S018506/1*. Can we say RiboViz is primarily funded by that grant? @shahpr what's the NSF/BIO grant number?

Edward Wallace is funded by a Sir Henry Dale Fellowship jointly funded by the Wellcome Trust and the Royal Society (Grant Number 208779/Z/17/Z).

**Comment by mikej888** [comment]
Googled for remaining grant numbers. Draft page at https://github.com/riboviz/RiboViz/blob/develop/docs/acks.md.
