### ISSUE TITLE
Provide examples of FASTA + GFF (decribing 2 transcripts with overlapping ORFs) for bacterial genome.

### ISSUE THREAD

**Issue by kavousan** [riboviz/riboviz#159]
As discussed on the 18 March call, John, can you please give us some such examples in this ticket?

Thanks.

**Comment by john-s-f** [comment]
Here is an E coli. genomic fasta and a gff3 that has only two genes where the last base of the stop codon of the first gene is the first base of the start codon of the next gene. The .txt file is the gff, I had to give it a different extension to upload it here.
[e_coli_genome.fasta.gz](https://github.com/riboviz/riboviz/files/4383192/e_coli_genome.fasta.gz)
[e_coli_overlapping_genes.txt](https://github.com/riboviz/riboviz/files/4383196/e_coli_overlapping_genes.txt)

**Comment by ewallace** [comment]
We can close this now, as @john-s-f  has provided an example. Next, #159 completion includes making transcript- and/or ORF-centric gffs using this example.
