### ISSUE TITLE
Deposit RiboViz 2.0 and get a citable DOI

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#173]
Deposit RiboViz release into Zenodo or figshare and get a persistent citable DOI for the software:

Figshare:

* https://figshare.com/
* Digital Science.
* Persistent, citable, long-term archiving for research outputs.
* Agreement with Nature, PLOS, Wiley and Taylor&Francis to ensure data persists for >10 years.
* They work with PLOS, Microbiology, Springer Nature, Wellcome Trust, Human Genome Variation, ORCID, Genetics Society of America, and many others.

Zenodo:

* https://zenodo.org/
* OpenAIRE, CERN.
* Retention period = repository lifetime = host laboratory (CERN) lifetime = >20 years.

**Comment by kavousan** [comment]
Figshare it is.

**Comment by FlicAnderson** [comment]
Since we seem to have [this DOI: https://doi.org/10.6084/m9.figshare.12624200](https://figshare.com/articles/riboviz_software_for_analysis_and_visualization_of_ribosome_profiling_datasets/12624200), I'm marking this issue as done.
