### ISSUE TITLE
Deprecate Python riboviz.tools.prep_riboviz with Nextflow prep_riboviz.nf

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#176]
Files to update include:

* `riboviz.tools.prep_riboviz` - delete.
*  `riboviz.workflow` - delete.
*  `riboviz.params` - remove `dir_logs` and `cmd_file` constants.
* `riboviz/workflow_files.py`
* `riboviz/count_reads.py`
* `riboviz/test/regression/test_regression.py` and `riboviz/test/regression/conftest.py`.
* `riboviz/test/tools/test_prep_riboviz.py` - delete.
* `riboviz/test/tools/test_prep_riboviz_simdata_multiplex.py` - delete.
* `riboviz/test/tools/test_prep_riboviz_simdata_umi.py`- delete.
* Remove "--nextflow" flag from `riboviz.test.regression.conftest`.
* `**/*config.yaml` - remove `cmd_file`, `dir_logs` parameters.
* `riboviz/upgrade_config.py` - remove `dir_logs` and `cmd_file`.
* Update `workflow.svg` with Nextflow temporary file naming.
* `docs/**/*.md` including searching code and documentation for occurrences of "Python workflow" and "riboviz.tools.prep_riboviz" and removing these.
* Add regression test data from a Nextflow run to DataSync.

**Comment by ewallace** [comment]
How are we going to manage the handoff? Should there be one release in which **both** `nextflow` and `prep_riboviz.py` work and pass the same regression test, and then after that deprecate?

**Comment by mikej888** [comment]
I was originally of the view that the next release would have both co-existing, but I'm now moving towards the view we should just make the leap as it were as it removes the need to maintain both going forward (even for a short term).

For users, the migration requires installing Nextflow (1 line via conda) then using the new command-line invocations. Configuration via YAML is unchanged.

We should discuss that at the next meeting

**Comment by kavousan** [comment]
Edward prefers one release with both; then we can lose Python. From this point on (today) we focus on Nextflow.

**Comment by mikej888** [comment]
The Nextflow workflow has evolved beyond the capabilities of the Python one. Removing it removes this stagnating unused code from the repository and avoids the risk of new users using that instead of Nextflow.

**Comment by ewallace** [comment]
I agree with Mike, this is a high priority for release 2.1.

**Comment by mikej888** [comment]
As of commit 19ebd1c, [deprecate-python-176](https://github.com/riboviz/riboviz/tree/deprecate-python-176), branched from [develop](https://github.com/riboviz/riboviz/tree/develop).

* Update README.md and docs/user/install.md to remove Python workflow references #341.
* Removed all reference to Python workflow from docs.
* Removed `prep_riboviz.py` related tests. Removed `--nextflow` flag from riboviz.test.regression.test_regression.py which now runs Nextflow always.
* Removed import of `riboviz.tools.prep_riboviz` from `riboviz.test.regression.test_regression`.
* Merged [upgrade-config-313](https://github.com/riboviz/riboviz/tree/upgrade-config-313) and added `cmd_file` and `dir_logs` to deprecated parameters.
* Removed `riboviz.tools.prep_riboviz` and related code.

**Comment by mikej888** [comment]
Closed by RP #362.
