### ISSUE TITLE
Allow underscore characters in sample names

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#18]
It would be great to allow underscores in sample names. Currently in the vignette_config.yaml we have:
```
fq_files: # fastq files to be processed
  WTnone: SRR1042855_s1mi.fastq.gz # do not use "_" in dataset name
  WT3AT: SRR1042864_s1mi.fastq.gz
```
We could not have '\_' in sample names because characters after the '\_' were dropped by the string processing in prepRiboviz.sh. This might not be a problem in prepRiboviz.py?

I would like to be able to use, for example:
```
fq_files: # fastq files to be processed
  WT_none: SRR1042855_s1mi.fastq.gz
  WT_3AT: SRR1042864_s1mi.fastq.gz
```

The use-case is where the underscore separates distinct and useful parts of information aobut the sample:
```
fq_files: # fastq files to be processed
  WT_rep1: SRR1042855_s1mi.fastq.gz
  WT_rep2: SRR1042864_s1mi.fastq.gz
  Mutant_rep1: SRRxxxxx.fastq.gz
  Mutant_rep2: SRRxxxx.fastq.gz
```

In the long run we would like to have a more sample-sheet based approach to metadata, but it would still be nice if the sample ids/names could include underscores.

**Comment by mikej888** [comment]
Setting `vignette_config.yml`:

```
fq_files: # fastq files to be processed
  WT_none: SRR1042855_s1mi.fastq.gz
  WT_3AT: SRR1042864_s1mi.fastq.gz
```

and running:

```bash
python scripts/prepRiboviz.py scripts/ vignette/vignette_config.yaml 
```

gives: `vignette/tmp`:

```
WT_3AT_nonrRNA.fq
WT_3AT_orf_map_clean.sam
WT_3AT_orf_map.sam
WT_3AT_rRNA_map.sam
WT_3AT_trim.fq
WT_3AT_unaligned.sam
WT_none_nonrRNA.fq
WT_none_orf_map_clean.sam
WT_none_orf_map.sam
WT_none_rRNA_map.sam
WT_none_trim.fq
WT_none_unaligned.sam
```

and `vignette/output`:

```
TPMs_collated.tsv
WT_3AT_3nt_periodicity.pdf
WT_3AT_3nt_periodicity.tsv
WT_3AT.bam
WT_3AT.bam.bai
WT_3AT_codon_ribodens.pdf
WT_3AT_codon_ribodens.tsv
WT_3AT_features.pdf
WT_3AT.h5
WT_3AT_minus.bedgraph
WT_3AT_plus.bedgraph
WT_3AT_pos_sp_nt_freq.tsv
WT_3AT_pos_sp_rpf_norm_reads.pdf
WT_3AT_pos_sp_rpf_norm_reads.tsv
WT_3AT_read_lengths.pdf
WT_3AT_read_lengths.tsv
WT_3AT_tpms.tsv
WT_none_3nt_periodicity.pdf
WT_none_3nt_periodicity.tsv
WT_none.bam
WT_none.bam.bai
WT_none_codon_ribodens.pdf
WT_none_codon_ribodens.tsv
WT_none_features.pdf
WT_none.h5
WT_none_minus.bedgraph
WT_none_plus.bedgraph
WT_none_pos_sp_nt_freq.tsv
WT_none_pos_sp_rpf_norm_reads.pdf
WT_none_pos_sp_rpf_norm_reads.tsv
WT_none_read_lengths.pdf
WT_none_read_lengths.tsv
WT_none_tpms.tsv
```

Compare collated file with results before introduction of `_`:

```bash
diff vignette/output/TPMs_collated.tsv ~/RiboViz-Outputs/Ubuntu18/vignette-bash/output/TPMs_collated.tsv
```
```
1c1
< ORF	WT_none	WT_3AT
---
> ORF	WTnone	WT3AT
```

**Comment by mikej888** [comment]
In `prepRiboviz.sh`, in each iteration of the loop:

```bash
for fq in ${fqfs}
```

`fq` to has values `fq_files_NotHere`, `fq_files_WT_3AT`, `fq_files_WTnone`. This is then parsed to get `fn_stem`:

```bash
eval fn_stem=${fq##*_}
```

This is where problems arise if there are multiple underscores:

```bash
fq=fq_files_WTnone; eval fn_stem=${fq##*_}; echo $fn_stem
```
```
WTnone
```
```bash
fq=fq_files_WT_none; eval fn_stem=${fq##*_}; echo $fn_stem
```
```
none
```

This is bash substring removal of form `PARAMETER##PATTERN`(see [example](https://wiki.bash-hackers.org/syntax/pe#substring_removal)). `##` means 'take the longest matching string possible', so it removes the longest `*_` string i.e. `fq_files_WT_`. To fix this, one can explicitly specify the prefix to be removed i.e. `fq_files_`:

```bash
fq=fq_files_WTnone; eval fn_stem=${fq##fq_files_}; echo $fn_stem
```
```
WTnone
```
```bash
fq=fq_files_WT_none; eval fn_stem=${fq##fq_files_}; echo $fn_stem
```
```
WT_none
```
