### ISSUE TITLE
Document dependency versions

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#183]
We need to document the version numbers of software that riboviz has run on, which will be extremely useful for users especially those running on clusters or external computers. The goal is that a new riboviz user knows what versions to install, and if a current installation is adequate. I think this software version info should be put in the github documentation. We may as well collect it in a form that is useful for containerization, issue #107.

Version information should include external software (e.g. cutadapt), python packages, and R packages.  I think this information is in one or more of the logfiles? Or somewhere in nextflow wrappers?

@XUEXUEXUE0 raised this question regarding what software versions she needs on Eddie, for issue #59.

**Comment by mikej888** [comment]
It is in doc/user/install.md

**Comment by mikej888** [comment]
Another example is in https://github.com/riboviz/regression-test-data-2.0.beta/blob/master/environment.txt

**Comment by mikej888** [comment]
Adding a summary table to the docs would be useful.

**Comment by ewallace** [comment]
Sorry, I hadn't picked up that the versions were in there. Yes a summary table would be useful.

**Comment by mikej888** [comment]
Convert  https://github.com/riboviz/riboviz/blob/nextflow-167/install/environment.sh to a Python script that outputs a Markdown table perhaps.

On a related note, can get a list of Python packages via
```
conda list --export > python_packages.txt
```
which can then be installed via:
```
conda install --file packagelist.txt
```
However, this relies on the user having `conda` available.

**Comment by mikej888** [comment]
As of commit 6e40387:

* Added `bash/environment-tables.sh` bash script that gets versions of each command-line tool, Python package, R package and outputs these in the form of Markdown tables. I used bash as the version information could be extracted using `head`, `cut`, and `tr` and, for this, Python felt like overkill.
* Added a new "Dependencies overview" section to the start of [docs/user/install.md](https://github.com/riboviz/riboviz/blob/develop/docs/user/install.md) with these tables and notes on constraints on versions.
* Updated [docs/developer/documentation.md](https://github.com/riboviz/riboviz/blob/develop/docs/developer/documentation.md) with a section on how to run `bash/environment-tables.sh`.
