### ISSUE TITLE
Review each item of documentation in `develop` branch

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#185]
Task to review - read through and make comments about - each separate documentation file in the `/docs/` folder.  

This will help give an idea of what each piece of documentation gives information about, and we'd like comments on if the document is clear, understandable or missing any information, and ideas for what we should add.

This should be done by 12th June, commenting on each file so we know each one has been reviewed.

**Comment by ewallace** [comment]
Suggest @XUEXUEXUE0 creates an issue branch `doc-review-185` for any *edits* to the documentation as a result of the feedback.

**Comment by ewallace** [comment]
We need to review this, recommend for 1st July dev meeting.

**Comment by ewallace** [comment]
@XUEXUEXUE0 will finish the review and make comments, by 6th July.

We request:

* make suggested edits to documentation on `doc-review-185` branch.
* list which files have been reviewed on this issue thread, even if they have not been changed.
* ask any questions about missing documentation on this issue thread.

**Comment by XUEXUEXUE0** [comment]
Actually this comment is from my research proposal marker. I cited the workflow image from `docs/image` in my research proposal.
The markers said the image was difficult to read at this font size, and also difficult to understand. And I agree. Maybe we should use a larger font and make the image easier to understand?

**Comment by XUEXUEXUE0** [comment]
Could we move the testing.md in `docs/developer` to `docs/user` folder so that users understands what is happening about the riboviz tests in install.md?
Also, I find there is no troubleshooting about the regression tests. What if the regression tests fail? I mean the first time I ran the regression tests, it did not pass. But I cannot fix the error. Finally Mike helped me fix the error.

**Comment by XUEXUEXUE0** [comment]
When I click the `enviroment.txt` , it says 404. Maybe we should upload the  `enviroment.txt` file?

**Comment by XUEXUEXUE0** [comment]
Do we need to have another file like `run-example-dataset.md` to teach users who cannot use Eddie to run full size example dataset?

**Comment by ewallace** [comment]
@FlicAnderson, @XUEXUEXUE0 and @ewallace discussed in dev meeting 15/07.

- Regression tests are how users check that riboviz is installed correctly. So we do need some user-facing documentation on how to use regression test fails to troubleshoot an installation problem.

**Comment by kavousan** [comment]
Discussed on 05 Aug 2020.
