### ISSUE TITLE
Run R scripts from anywhere

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#187]
Investigate putting a shebang statement `#!/usr/bin/env Rscript` at the top of each R script. This, in conjunction with adding `riboviz/rscripts` to the `PATH` environment variable would allow the R scripts to be run from any directory, and without the use of `Rscript` i.e. instead of:

```console
$ Rscript rscripts/generate_stats_figs.R ...
```

one could do

```console
$ export PATH=$HOME/riboviz/rscripts:$PATH
$ generate_stats_figs.R ...
```

The following would need to be investigated whether:

* This would affect the relative imports of other R scripts (e.g. `provenance.R`).
* `provenance.R` could still find out information about the Git repository in which it is located.
* Interactive debugging of the R scripts could still be done.

**Comment by ewallace** [comment]
I think this will be superseded by two other issues:

1. Make R scripts into a separate repository as an R package, as in #52.
2. Replace the current R scripts by .Rmd files, as in #193.

Unless there is a plausible use-case where we expect users to run R scripts with a shebang from the command line. I suggest we review and close this unless such a use-case is found.

**Comment by mikej888** [comment]
The command-line use case - and which motivated this ticket - is running the R scripts as command-line tools from within the RiboViz workflow(s). The workflow is the "user".

**Comment by ewallace** [comment]
I get it. So for example the `bam_to_h5.R` script will continue to be run in this way, regardless of whether the successor to `generate_stats_figs.R` is in .Rmd format.

**Comment by mikej888** [comment]
Yes. For Rmd, Nextflow can invoke it using something like

```
Rscript -e "rmarkdown::render('generate_stats_figs_successor.Rmd',params=list(args = myarg))"
```

(from https://stackoverflow.com/questions/49904943/run-rmarkdown-with-arguments-on-the-command-line)

But, if Nextflow has to explicitly be told where the Rmd files are (rather than them being on the `PATH`), then it might as well be explicitly told where the R scripts are as well (as at present). So we do return to your suggestion to just close the issue!

**Comment by ewallace** [comment]
Agree that this isn't needed, closing issue.
