### ISSUE TITLE
Test alternative adapter trim/QC

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#19]
RiboViz currently uses cutadapt to trim adapters and QC reads, which is one of the slower steps. We should test [FASTP](https://academic.oup.com/bioinformatics/article/34/17/i884/5093234), which claims to be 2-5x faster.

**Comment by mikej888** [comment]
Shifu Chen, Yanqing Zhou, Yaru Chen, Jia Gu, fastp: an ultra-fast all-in-one FASTQ preprocessor, Bioinformatics, Volume 34, Issue 17, 01 September 2018, Pages i884-i890,, https://doi.org/10.1093/bioinformatics/bty560

https://github.com/OpenGene/fastp

* MIT licence
* Oct 2017 - Apr 2019, 34 releases
* Python bioconda install OR C++, g++

**Comment by mikej888** [comment]
This could be deprecated by #43.

**Comment by ewallace** [comment]
Also could be deprecated by #37, as UMI-tools regex also allows adapter trimming.

**Comment by ewallace** [comment]
Deprecated by #43. Not worth revisiting unless adapter trimming becomes a problematically slow step in the future.
