### ISSUE TITLE
Document recommended memory requirements

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#192]
For 2.0 make a short-term update to the documentation to say that memory usage may be an issue, pending improvement in a future release. 

Include reference to "excessive dedup memory usage with output-stats" CGATOxford/UMI-tools/issues/409, and suggest that users set `dedup_stats: FALSE` to turn off output statistics creation (see #186).

Spawned from #179

**Comment by mikej888** [comment]
When running RiboViz - either Python or Nextflow - with the vignette data it runs fine for me under:

* VMWare VM with 8GB RAM (running on my laptop)
* University of Edinburgh EDDIE compute cluster:
  - Interactive node (accessed via `qlogin`) with 8GB RAM requested.
  - Back-end node (accessed via `qsub`) with 16GB RAM requested. On job completion, `qacct` shows: `maxvmem 13.726G`.
  - If my `qsub` job requests 8GB RAM they quickly fail with `qacct` showing, for example, `failed 46  : execd enforced h_vmem limit`, `exit_status  137`, `maxvmem 8.115G`


@FlicAnderson, @ewallace, @john-s-f, @amandamok  @XUEXUEXUE0 please could you provide some idea as to how much GB memory (to the nearest GB will be fine) the platforms run RiboViz on have - both for vignette data and for any full size datasets.

**Comment by FlicAnderson** [comment]
My machine has run riboviz (Python & Nextflow) successfully for vignette & multiple full-size yeast datasets & has 16GB RAM to play with.

**Comment by XUEXUEXUE0** [comment]
8GB RAM is enough for running the riboviz vignette with python method but is not enough for nextflow method. So I suggest 16GB RAM.

**Comment by mikej888** [comment]
Thanks @FlicAnderson  and @XUEXUEXUE0!

**Comment by kavousan** [comment]
@john-s-f and @amandamok this is the ticket for the "survey" of Riboviz memory usage. Thanks!

**Comment by john-s-f** [comment]
I've been running the nextflow version on our lab server which has the following:
2x Intel Xeon Processor E5-2660 v4 amounting to 28 cores and 56 threads
264Gb of ram
Ubuntu 18.04.4 LTS

**Comment by ewallace** [comment]
Following @XUEXUEXUE0 's advice, I've run vignette and full-size yeast data on Eddie with 16GB requested. I haven't tested this any further.

**Comment by mikej888** [comment]
Please add further updates to #179.
