### ISSUE TITLE
Change data input file yeast_codon_pos_i200.RData to alternative file format

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#194]
This was discussed as part of the pull request #184 on the way to close issue #32, so I'm opening this as a ticket since it probably needs a bit of investigation anyway, regardless of how I navigate this in closing #184 

The file: yeast_codon_pos_i200.RData 

Initial issue details here: https://github.com/riboviz/riboviz/pull/184#issuecomment-652469274 

It'd be handy to change this from a specific R data file to something easier to interrogate.

**Comment by ewallace** [comment]
This file encodes a list of character matrices, that could easily be recast into a tidy data frame (flat text file). There are also problems with specific choices hard-coded into the script, that could easily be removed.

The information is, what is the codon at each position of every coding sequence (CDS) for the transcripts in the annotation? Thus my suggested data format would be a tidy data frame:

```
Gene    Pos_aa codon
YAL001C      1   ATG
YAL001C      2   GTA
YAL001C      3   CTG
YAL001C      4   ACG
YAL001C      5   ATT
...
```

Note, these column names should be consistent with other names for genes and **amino acid position** (not nucleotide position) as used in `generate_stats_figs.R` and so on.

However, currently:

```
> load("~/Repos/riboviz/riboviz/data/yeast_codon_pos_i200.RData")
> str(codon_pos)
List of 61
 $ TTT: chr [1:48833, 1:2] "YAL001C" "YAL001C" "YAL001C" "YAL001C" ...
 $ TTC: chr [1:32873, 1:2] "YAL001C" "YAL001C" "YAL001C" "YAL001C" ...
 ...
> View(codon_pos$ATA)
> head(codon_pos$AAA)
     [,1]      [,2]
[1,] "YAL001C" "14"
[2,] "YAL001C" "17"
[3,] "YAL001C" "19"
[4,] "YAL001C" "23"
[5,] "YAL001C" "40"
[6,] "YAL001C" "52"
```

This object was created by code in [script_for_transcript_annotation.Rmd](https://github.com/riboviz/riboviz/blob/master/rmarkdown/script_for_transcript_annotation.Rmd).

Problems:
- bespoke undocumented data shape requires special accession.
- codon position stored as character, not as integer.
- data stored as binary file not text.
- the choice to ignore the first 200 codon positions, and genes shorter than 200nt, is hard-coded in both the data-creation and data-analysis code. This should be a parameter.

All these can be solved by making a tidy data text format starting at the **first** position of the ORF. We can save it .gzipped to reduce footprint. Then there should be a new parameter, called `codon_ramp_length` or something, that controls how many initial codons to ignore, with default value 200. Then we write code to pass regression tests with that, and drop the .RData.

Writing code to address this harks back to issue #35.

**Comment by ewallace** [comment]
I already wrote a function to decompose a sequence in to codons, in a pull request to `stringr` that was refused. Boohoo.

```
#' Dice a character vector into pieces of fixed length.
#' 
#' Wraps stri_sub for situations where completely decomposing a string 
#' into fixed-length substrings is appropriate. The last
#' 
#' This is useful for example for breaking a coding sequence of DNA
#' into codon-sized triplets.
#'
#'
#' @param string input character vector.
#' @param width integer giving the width in letters of each piece to return.
#'
#' @return A character vector of substrings each of length `width`, except
#'   the last will be shorter if `length(string)` is not a multiple of `width`.
#' 
#' @seealso The underlying implementation in [stringi::stri_sub()]
#' @export
#' @examples
#' hw <- "Hadley Wickham"
#' CDS <- "ATGTTTGGGTAG"
#'
#' str_dice(hw, width=1L)
#' str_dice(hw, width=2L)
#' str_dice(hw, width=4L)
#' str_dice(CDS, width=3L)
str_dice <- function(string, width=1L) {
     starts <- seq(1, nchar(string), width)
     stri_sub(string, from = starts, to = starts+width-1)
}
```

Given a sequence, we can chop it into codons using `str_dice(CDS,width=3L)`.

Similarly, riboviz needs a function like this:

```
seq_to_codon_df <- function(seq, width=3L) {
     aa_pos <- seq(1, nchar(string), width)
     codons <- stringi::stri_sub(string, from = aa_pos, to = aa_pos+width-1)
    tibble(aa_pos=aa_pos, codon = codons)
}
```

Then we could automatically calculate the codons for each gene by:

1. get relevant coding sequences / ORFs from the annotation gff and fasta.
2. calculate the codon table as shown.
3. then join together across genes.

This is related to, but much simpler than, #105.

Lastly, the relevant chunk of `generate_stats_figs.R` or successor can then join this matrix to the RPF count matrix per A-site (I think) codon, and then calculate codon-specific occupancy in windows around those. To be discussed.

**Comment by ewallace** [comment]
@mikej888 is writing code to *create* this data frame as part of #74.

We (probably @FlicAnderson in consultation with @mikej888) will then need to rewrite the R code so that it allows the code chunk (I think `CalculateCodonSpecificRibosomeDensity`) to exclude a user-defined number of initial codons. We can set this number to 200 initially to pass the regression test.

**Comment by mikej888** [comment]
For testing this and #74 and other, related, work, I wrote a short R script [rscripts/yeast_codon_pos_rdata_tsv.R](https://github.com/riboviz/riboviz/blob/gff-spec-74/rscripts/yeast_codon_pos_rdata_tsv.R) which converts `data/yeast_codon_pos_i200.RData` to [data/yeast_codon_pos_i200.tsv](https://github.com/riboviz/riboviz/blob/gff-spec-74/data/yeast_codon_pos_i200.tsv). The usage was:

```console
$ Rscript rscripts/yeast_codon_pos_rdata_tsv.R  --offset 200
```

The TSV file is in the same TSV file format (header `Gene Codon Pos`) as output by `python -m riboviz.tools.get_cds_codons_file` (see #74).

An offset of 200 is added to each codon position to reflect the fact that the original `.RData` file had the first 200 codons removed. This also means that the file will be consistent going forward to test the proposed functionality in previous comments that the number of codons to exclude be a parameter to `generate_stats_figs.R` (or its successor) so inputs to this refactored/new script will assume all codons in the TSV file are 1-based.

**Comment by kavousan** [comment]
Used for pausing analysis; @john-s-f you brought this up on 02 Sept.

**Comment by FlicAnderson** [comment]
After chat with @mikej888 earlier, this is my plan to make progress on this issue: 


I need to work on [this function](https://github.com/riboviz/riboviz/blob/develop/rscripts/stats_figs_block_functions.R#L746) in `stats_figs_block_functions.R` which gets used [here]( https://github.com/riboviz/riboviz/blob/develop/rscripts/generate_stats_figs.R#L445) in `generate_stats_figs.R`, to add the ability to process [data/yeast_codon_pos_i200.tsv](https://github.com/riboviz/riboviz/blob/gff-spec-74/data/yeast_codon_pos_i200.tsv) which Mike's created from the .RData file version which generate_stats_figs.R currently uses as `codon_positions_file`.

Step 0: make branch from `gff-spec-74` since this contains the .tsv file and relevant code 
Step 1: test creation (objects `A`, `P`, `E`, `cod_dens_tRNA_data` to be written out as .tsv files, then check their equality)
Step 2: edit CalculateCodonSpecificRibosomeDensity() function to be able to load in the .tsv instead of just:
```R
load(codon_positions_file) # Position of codons in each gene (numbering ignores first 200 codons)
  # Reads in an object named "codon_pos""
```
Step 3: start editing the function `CalculateCodonSpecificRibosomeDensity()` and contents to accept an argument of how many codons to skip. Default: 200
Step 4: check that the test gives same result between objects created when running with `codon_positions_file` as `yeast_codon_pos_i200.RData` and `yeast_codon_pos_i200.tsv`.

**Comment by FlicAnderson** [comment]
Update: I haven't made any progress on this yet since chatting about what the next steps are [last week with Mike](https://github.com/riboviz/riboviz/issues/194#issuecomment-693572608).

**Comment by FlicAnderson** [comment]
Still to do!

**Comment by ewallace** [comment]
@shahpr is working on this as of the hackathon; @ewallace volunteers to test the changes.

**Comment by FlicAnderson** [comment]
> After chat with @mikej888 earlier, this is my plan to make progress on this issue:
> 
> I need to work on [this function](https://github.com/riboviz/riboviz/blob/develop/rscripts/stats_figs_block_functions.R#L746) in `stats_figs_block_functions.R` which gets used [here](https://github.com/riboviz/riboviz/blob/develop/rscripts/generate_stats_figs.R#L445) in `generate_stats_figs.R`, to add the ability to process [data/yeast_codon_pos_i200.tsv](https://github.com/riboviz/riboviz/blob/gff-spec-74/data/yeast_codon_pos_i200.tsv) which Mike's created from the .RData file version which generate_stats_figs.R currently uses as `codon_positions_file`.
> 
> Step 0: make branch from `gff-spec-74` since this contains the .tsv file and relevant code
> Step 1: test creation (objects `A`, `P`, `E`, `cod_dens_tRNA_data` to be written out as .tsv files, then check their equality)
> Step 2: edit CalculateCodonSpecificRibosomeDensity() function to be able to load in the .tsv instead of just:
> 
> ```r
> load(codon_positions_file) # Position of codons in each gene (numbering ignores first 200 codons)
>   # Reads in an object named "codon_pos""
> ```
> 
> Step 3: start editing the function `CalculateCodonSpecificRibosomeDensity()` and contents to accept an argument of how many codons to skip. Default: 200
> Step 4: check that the test gives same result between objects created when running with `codon_positions_file` as `yeast_codon_pos_i200.RData` and `yeast_codon_pos_i200.tsv`.

As an update, the `yeast_codon_pos_i200.tsv` file can be found in branch `develop` at `data/yeast_codon_pos_i200.tsv` after the branch `gff-spec-74` was merged into develop ~6 months ago.  This will be useful for @swinterbourne
