### ISSUE TITLE
Add details to documentation on how to find log files from nextflow run method

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#199]
In Nextflow's output...
```
[d2/460a23] Submitted process > generateStatsFigs (umi5_umi3)
```
The `d2/460a23` is a unique job ID. In your Nextflow `work/` directory there will be a corresponding sub-directory `d2/460a23.....`. In that there will be `.` files including `.command.out`, `.command.err` (`ls -A work/d2/460a23...` will show them)

_Originally posted by @mikej888 in https://github.com/riboviz/riboviz/pull/184#issuecomment-655445963_  

I've had a look in the documentation but so far can't see any mention of how to find the log files in Nextflow run output, so it might be worth adding this for users to help troubleshoot or  find more information on how the processes ran?

Apologies @mikej888 if this is included already and I've overlooked it!

**Comment by mikej888** [comment]
These are described in 

* https://github.com/riboviz/riboviz/blob/master/docs/user/prep-riboviz-operation.md#nextflow-workflow
* https://github.com/riboviz/riboviz/blob/master/docs/user/prep-riboviz-operation.md#nextflow-work-directory

**Comment by FlicAnderson** [comment]
Thanks, I have no idea how I overlooked ALL OF THOSE. Sorry! :scream:
