### ISSUE TITLE
Nextflow error when organism-specific input files: null in .yaml config

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#202]
Myself and @XUEXUEXUE0 have encountered an error in master branch when running the nextflow workflow on full-size dataset Cryptococcus neoformans H99 and JEC21 [as here](https://github.com/riboviz/example-datasets/tree/CryptococcusH99-3/fungi/cryptococcus) on Eddie, and on my laptop. 

The error shows up when running validation (`--validate_only`), and the same error applies when running normally (without `--validate_only`).

Python methods run fine, and give no errors.  

I'm presuming this is an input-handling/validating issue, since the python code is working ok without these parameters?

I've been able to reproduce the error by editing the vignette to not use certain input files, as this recreates the scenario where these files are missing for other organisms' datasets, e.g. Cryptococcus. 

```
#  @ master branch, last commit: 03a4f13

# when vignette_config.yaml is edited to show: 
  # asite_disp_length_file: null
  # codon_positions_file: null
  # do_pos_sp_nt_freq: false
  # features_file: null 
  # t_rna_file: null 
# ... as these are commonly not used with non-Saccharomyces cerevisiae datasets

(base) flic@circe:~/riboviz$ nextflow run prep_riboviz.nf -params-file vignette/vignette_config.yaml --validate_only
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [grave_cuvier] - revision: a48b061e17
Validating configuration only
No such sample file (NotHere): example_missing_file.fastq.gz
Argument of `file` function cannot be null
 -- Check script 'prep_riboviz.nf' at line: 397 or see '.nextflow.log' file for more details

# NOTE: line 397 of prep_riboviz.nf is this:  "t_rna_file = file(params.t_rna_file)"
```
@mikej888 Can you reproduce this and do you have any ideas how to narrow down the source of this error?

**Comment by mikej888** [comment]
As a quick check what happens if, instead of setting the files to null:
```
 asite_disp_length_file: null
 codon_positions_file: null
 do_pos_sp_nt_freq: false
 features_file: null 
 t_rna_file: null 
```
In your YAML, you comment the parameters out altogether i.e.
```
# asite_disp_length_file: null
# codon_positions_file: null
 do_pos_sp_nt_freq: false
# features_file: null 
# t_rna_file: null 
```
If that doesn't work then what happens if you remove them altogether i.e.
```
do_pos_sp_nt_freq: false
```
It may be that the Nextflow script needs to be smarter and check for "null" as an explicit value (rather than just checking whether the parameter is defined or not)

**Comment by mikej888** [comment]
Edward comments that "null" should be permitted as a value. This should be interpreted the same way as the absence of an optional parameter.

**Comment by mikej888** [comment]
@FlicAnderson please try fix in branch optional-null-values-202-203.

**Comment by FlicAnderson** [comment]
Nextflow `--validate-only` now works on Cryptococcus dataset yaml after running the fix from branch `optional-null-values-202-203`.  Nice fix! :100:

**Comment by mikej888** [comment]
@FlicAnderson glad it works :-)

**Comment by mikej888** [comment]
Merged into "develop" branch.
