### ISSUE TITLE
Webtool to create config.yaml?

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#208]
Proposed by @shahpr and discussed at 26 August 2020 meeting.

The suggestion is to write a webtool to allow users an "easy way" to set up the config.yaml file, that they can download and run riboviz nextflow locally.

**Comment by kavousan** [comment]
Focussing on semi-expert users currently; this may surface.

**Comment by mikej888** [comment]
Deprecated by #389? If so then this issue can be closed.

**Comment by mikej888** [comment]
Agreed this is deprecated by #389.
