### ISSUE TITLE
Make trim_5p_mismatch.py optional

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#209]
At 2nd Sep meeting @amandamok showed that her bias-correction work, at least in some cases, requires *untrimmed* 5' end mismatches. This means that we need to make the `trim_5p_mismatch.py` step in the pipeline optional. Perhaps a parameter `trim_5p_mismatches` in `config.yaml`, that if `FALSE` skips the step and if `TRUE` runs it.

@amandamok, how urgent is this for you? Would you have any interest in implementing in nextflow? @mikej888 might be able to do it, but he is only 1 day/week on riboviz now.

**Comment by amandamok** [comment]
Not urgent on my end, but I'm happy to take a stab at a nextflow implementation!

**Comment by mikej888** [comment]
It's useful for as many people as possible to get experience with editing the Nextflow workflow (to increase its bus factor!) As it can help to think of the workflow pictorially, I've attached an image of the part of the workflow that needs updated - both as it is just now and how it should look. The curved edge nodes are processes, the square edged nodes are Nextflow `branch` and `mix` operations, the arrows are data channels (for which unique names will need to be chosen)

![nextflow-trim5pmismatches](https://user-images.githubusercontent.com/2621549/92586020-9e65be80-f28d-11ea-94ee-9cce303f1e78.png)

**Comment by amandamok** [comment]
Added `trim_5p_mismatches` flag (optional; defaults to TRUE) for config.yaml

Pushed to branch: `trim-5pMismatches-optional-209`

**Comment by ewallace** [comment]
@amandamok that looks great - have you tested that it runs both ways on vignette data? On any other data?

When it works both ways for you, please put in a pull request.

**Comment by kavousan** [comment]
@mikej888 to review this.

**Comment by mikej888** [comment]
Merged pull request #221.
