### ISSUE TITLE
Job submission script for Eddie

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#217]
@FlicAnderson has written a "job submission script" for Eddie, to load modules and run the nextflow fiboviz pipeline using the job scheduler.

I'm starting this as a separate ticket related to #59, because this script should be in a separate place on the riboviz repository, as well as referred to in `/docs/user/run-on-Eddie.md`. 

Currently there are versions of these scripts discussed in [example-datasets#13](https://github.com/riboviz/example-datasets/issues/13).

**Comment by FlicAnderson** [comment]
@ewallace , @mikej888 do you have any suggestions/strong feelings on where these should be? 

Worth popping them in `/bash` folder for now alongside the install scripts and environment ones? Or a new folder at the same level as `/bash` (ie `riboviz/example-submission-scripts`)?  I'd err towards the former currently...  

I'll make an issue branch and will put them there for now.

Agree on linking to documentation though, good shout!

**Comment by FlicAnderson** [comment]
Planning to add example submission scripts from:
 - vignette 
 - full-size-dataset from `example-datasets` repo.  

Any suggestions on which is a 'nice' full-size example? Possibly Brar 2012 saccharomyces? 

I'm currently running the Brar 2012 dataset (6 samples only) now, so I'll have an idea of how it runs and how big the outputs are in the near-ish future, since I think it would be good to add that to the submission scripts as comments.

**Comment by FlicAnderson** [comment]
Or do people think it is worth adding an example submission script for EACH dataset in example-datasets?  
Was this what you'd intended @ewallace ?

Personally I think if the majority of the information is available in the #59 `run-on-eddie.md` documentation, and there are a couple of examples to extrapolate from, it might not be too difficult for folks to create their own and so having one for each dataset might be unnecessary? Also makes them easier to keep up-to-date if anything changes in the codebase?

**Comment by ewallace** [comment]
How hard would it be to write a script to produce a specific job submission script from the `config.yaml`? Does that even make sense?

**Comment by mikej888** [comment]
> @ewallace , @mikej888 do you have any suggestions/strong feelings on where these should be?
> 
> Worth popping them in `/bash` folder for now alongside the install scripts and environment ones? Or a new folder at the same level as `/bash` (ie `riboviz/example-submission-scripts`)? I'd err towards the former currently...
> 
> I'll make an issue branch and will put them there for now.

They're not really bash scripts, and `example-submission-scripts` is a bit verbose? How about `jobs`?

**Comment by mikej888** [comment]
> How hard would it be to write a script to produce a specific job submission script from the `config.yaml`? Does that even make sense?

One could have a job submission script template file with tokens (e.g. CPU, memory, YAML file name). The script could replace these tokens with values from the RiboViz YAML file and/or from command-line parameters.

**Comment by kavousan** [comment]
> 
> 
> > How hard would it be to write a script to produce a specific job submission script from the `config.yaml`? Does that even make sense?
> 
> One could have a job submission script template file with tokens (e.g. CPU, memory, YAML file name). The script could replace these tokens with values from the RiboViz YAML file and/or from command-line parameters.

This to become a new ticket; Mike to take it on, in preference to tests and #92.

**Comment by FlicAnderson** [comment]
Created branch `job-submission-scripts-217` and pushed an example vignette submission script (and accompanying remote_vignette_config.yaml file which has different paths as required for symlinks etc and scratch usage on Eddie).

Emailed @mikej888 some example job submission scripts I'm using currently for job submission script template builder. (Not sure this has a new issue ticket yet?)

**Comment by FlicAnderson** [comment]
Added bit to `docs/user/run-on-eddie.md` on new example vignette submission script and the corresponding yaml.

**Comment by mikej888** [comment]
SRRx are the YAML `fq_files` file prefixes. These could be used to populate `prefetch` and `fasterq-dump` commands.

**Comment by ewallace** [comment]
I think this issue has been replaced by #228.

Let's review.

**Comment by mikej888** [comment]
These are complementary. Proposing job submission scripts and writing a Python script to customise template job submission scripts (where the templates are derived from the actual examples).

**Comment by ewallace** [comment]
At dev meeting, we agreed that this has been superseded by #228.

There are examples of job submission scripts (with extra path dependencies) in various issue tickets in example-datasets that could be used for reference in the meantime, e.g. [example-datasets#18](/riboviz/example-datasets/pull/18).

Closing.
