### ISSUE TITLE
Write Python script to create job submission script from RiboViz configuration

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#228]
Write Python script to create job submission script from YAML configuration and command-line parameters.

Spawned from #217.

**Comment by mikej888** [comment]
Option: read in and customise job submission script template, replacing tokens. +ve: could use Python script with different templates for different platforms. -ve: requires maintaining code and template(s).

Option: create job submission script entirely within code. +ve: requires only maintaining code. -ve: different platforms require edited/additional code.

**Comment by mikej888** [comment]
Created branch `py-create-job-submission-script-228` from `job-submission-scripts-217` and merged in current `develop`

**Comment by mikej888** [comment]
Commit abff862. Implemented `create_job_script` token replacement. Script reads in:
    
* Configuration file
* Configuration parameters from command-line
* Template (for example `jobs/eddie-template.sh`
    
Replaces tokens of form `%%<CONFIG_PARAMETER>%%` in template with values from configuration file and command-line.

Command-line configuration parameters override those defined in configuration file.

Examples:

```console
$ python -m riboviz.tools.create_job_script -c vignette/vignette_config.yaml -i jobs/eddie-template.sh -o run_B-Sc_2012_nu.sh --job_name B-Sc_2012 --runtime 48:00:00 --memory 8G --num_cpus 16 --r_libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary --data_folder B-Sc_2012

$ python -m riboviz.tools.create_job_script -c vignette/vignette_config.yaml -i jobs/eddie-template.sh -o run_W-Cn-H99_2020_nu.sh --job_name W-Cn-H99_2020 --runtime 48:00:00 --memory 8G --num_cpus 16 --r_libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary --data_folder Wallace_2020_H99
```

TODO:

Implement support for populating the `prefetch` section based on the YAML `fq_files` or `multiplexed_fq_files` values.

Discuss default values and tokens:
 
* `%%job_name%%`: Can YAML `dataset` value be used for this (removing need for separate token)? Or keep distinct?
* `%%runtime%%`: 48:00:00. But is YAML the most appropriate place for this? Yes as a hint to others.
* `%%memory%%`: 8GB. See above.
* `%%num_cpus%%`: 16. See above.
* `%%r_libs%%`: No sensible default is possible, nor should this be defined in the YAML file as it would greatly inhibit the portability of those files.
* `%%data_folder%%"`: Make equal to `job_name` and `dataset`?
* `%%pre_fetch%%`: TODO, see above.
* `%%config_path%%`: Absolute path to YAML configuration file given to `riboviz.tools.create_job_script`.
* `%%config_file%%`: Base-name YAML configuration file given to `riboviz.tools.create_job_script`.

Discuss the following in `eddie-template.sh` (derived from Flic's example scripts):

```
cd $HOME/riboviz/riboviz
```

This is rather restrictive. A more intuitive one would be `$HOME/riboviz`,  and to use this as the default value for a token `%%riboviz_home%%` unless a specific value for `riboviz_home` is provided.  Again, this would not be appropriate to define in the YAML.

Discuss that there is only so much generalisation that can be done. The template assumes prefetching will be done to get the data files. This means that the same template cannot be used to create a job submission script for the vignette, where the data files already exist. The more conditional logic that is required the more the code moves away from being a token replacer to a job submission script generator, with all the complexity that would incur (both in defining templates and in code to customise these templates). It'd be preferable to use a separate job submission script template for such cases.

**Comment by ewallace** [comment]
Agree that a job submission script including prefetch/fasterq-dump is not what we want. Those download tasks are really steps in the workflow, so should be part of the nextflow workflow as addressed in fromSRA (#207). We want to keep the job submission script as simple as possible, just loading modules then running the nextflow workflow in the right place and queue. Let's discuss at dev meeting.

**Comment by mikej888** [comment]
I agree that Nextflow would be a good place for doing the fetches.

**Comment by ewallace** [comment]
Suggestions for the job submission script:
* Add email notifications, `-m beas`, as a default option; could give option to change the address with `-M`
* How can we make it easy to submit a near-identical job to *only* run for 5 minutes on the fastest queue, running a `validate_only` smoke test?
* When we scale up to more datasets, we will need to delete the `work` folder and intermediate files if the job completes successfully with no errors. Could that be an option in the job submission script? Or does it belong somewhere else, i.e. in nextflow pipeline? Is there a nextflow option?
* We need to discuss paths and simplifying "where stuff is", in reference to [example-datasets#27](/riboviz/example-datasets/issues/27)

**Comment by FlicAnderson** [comment]
> ```
> cd $HOME/riboviz/riboviz
> ```
> 
> 
> This is rather restrictive. A more intuitive one would be `$HOME/riboviz`,  and to use this as the default value for a token `%%riboviz_home%%` unless a specific value for `riboviz_home` is provided.  Again, this would not be appropriate to define in the YAML.

@mikej888 agreed that this isn't very intuitive. 

This `$HOME/riboviz/riboviz` came about because I had thought @ewallace suggested it made more sense to have `example-datasets` and `riboviz` repos cloned into the same folder, called `riboviz`.  I may have just picked up the wrong end of the stick on what you meant with this?

**Comment by ewallace** [comment]
@FlicAnderson is correct about what I meant. But then we point to `%%riboviz_home%%`, and expect subdirectories `riboviz` and `example-datasets`. There's enough confusion (on my part) about how the paths work that we need to bash it out and draw some pictures about the relative locations of things.

**Comment by mikej888** [comment]
> Add email notifications, -m beas, as a default option; could give option to change the address with -M

OK this can be done. If the user specifies a mailing address we can add a `-M` line`. We can't have the `-M` line in any template as it has to either not be there or be there and point to a valid email address.

> How can we make it easy to submit a near-identical job to only run for 5 minutes on the fastest queue, running a validate_only smoke test?

This needs an example script, to turn into a template. This falls under the remit of #217, or a new issue, to create such a job so we know what it looks like, before it is turned into a template.

> When we scale up to more datasets, we will need to delete the work folder and intermediate files if the job completes successfully with no errors. Could that be an option in the job submission script? Or does it belong somewhere else, i.e. in nextflow pipeline? Is there a nextflow option?

What if the job completes successfully with no errors but on inspection the results are invalid somehow? The work directory, and intermediate files, will be lost? Needs more thought. Again, if it's Nextflow-specific it needs a new issue.

> We need to discuss paths and simplifying "where stuff is", in reference to example-datasets#27

> @FlicAnderson is correct about what I meant. But then we point to %%riboviz_home%%, and expect subdirectories riboviz and example-datasets. There's enough confusion (on my part) about how the paths work that we need to bash it out and draw some pictures about the relative locations of things.

Job submission script should only need to know where to find YAML, RiboViz, and R libraries.

**Comment by mikej888** [comment]
Current TODOs:

* `%%runtime%%`: 48:00:00. Add default to YAML as hint to users.
* `%%memory%%`: 8GB. Likewise.
* `%%num_cpus%%`: 16. Likewise.
* `#$ -m %%mail_events%%`, default `beas`.
* `job_email: NULL`. If `job_email` is not None then insert after ``%%mail_events&%%` a line `#$ -M job_email`
* If the user specifies a `validate_only` parameter then Nextflow can be run in `--validate_only` mode. Remove the `nextflow ... --validate_only` command from `eddie-template.sh` and add in `--validate_only` if that parameter is defined.
* Add `--with-report report.html`, optionally specify location.

**Comment by FlicAnderson** [comment]
I think @ewallace has found better success in getting jobs submitted quickly through asking for lower resource values: https://github.com/riboviz/riboviz/issues/230#issuecomment-722449302 so perhaps better to use 4 as the default for `%%num_cpus%%` instead of 16?  Which value of memory request did you find struck a good balance for the larger runs @ewallace?

**Comment by mikej888** [comment]
Revised `riboviz.tools.create_job_script` See documentation at https://github.com/riboviz/riboviz/blob/py-create-job-submission-script-228/docs/user/create-job-script.md.

**Comment by mikej888** [comment]
Example `--validate-only` run on EDDIE using simulated data:

```console
$ python -m riboviz.tools.create_job_script -i jobs/eddie-template.sh \
    -o run-simdata.sh --config-file vignette/simdata_umi_config.yaml \
    --r-libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary \
    --job-name riboviz-simdata --job-runtime 12:00:00 \
    --job-memory 8G --job-num-cpus 2 --job-email <EMAIL> \
    --validate-only
$ qsub -P <QUEUE> run-simdata.sh
Your job 8709646 ("riboviz-simdata") has been submitted
```

Received emails:

```
Job 8709646 (riboviz-simdata) Started
 User       = <USERNAME>
 Queue      = eddie
 Host       = <NODE>.ecdf.ed.ac.uk
 Start Time = 12/01/2020 16:07:23.332

Job 8709646 (riboviz-simdata) Complete
 User             = <USERNAME>
 Queue            = eddie@<NODE>.ecdf.ed.ac.uk
 Host             = <NODE>.ecdf.ed.ac.uk
 Start Time       = 12/01/2020 16:07:23.714
 End Time         = 12/01/2020 16:07:37.984
 User Time        = 00:00:11
 System Time      = 00:00:01
 Wallclock Time   = 00:00:14
 CPU              = 00:00:12
 Max vmem         = 10.984G
 Max rss          = NA
 Exit Status      = 0
```

On completion:

```console
$ cat riboviz-simdata-8709646-<NODE>.ecdf.ed.ac.uk.o
Running Nextflow riboviz...
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [evil_goldstine] - revision: e13128e34f
Validating configuration only
Validated configuration
Nextflow riboviz run complete!
```

Example run on EDDIE using simulated data:

```console
$ python -m riboviz.tools.create_job_script -i jobs/eddie-template.sh \
    -o run-simdata.sh --config-file vignette/simdata_umi_config.yaml \
    --r-libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary \
    --job-name riboviz-simdata --job-runtime 12:00:00 --job-memory 8G \
    --job-num-cpus 2 --job-email <EMAIL>
$ qsub -P bio_wallace_rna_riboviz run-simdata.sh
Your job 8710129 ("riboviz-simdata") has been submitted
```

Received emails:

```
Job 8710129 (riboviz-simdata) Started
 User       = <USERNAME>
 Queue      = eddie
 Host       = <NODE>.ecdf.ed.ac.uk
 Start Time = 12/01/2020 16:10:51.037

Job 8710129 (riboviz-simdata) Complete
 User             = <USERNAME>
 Queue            = eddie@<NODE>.ecdf.ed.ac.uk
 Host             = <NODE>.ecdf.ed.ac.uk
 Start Time       = 12/01/2020 16:10:51.403
 End Time         = 12/01/2020 16:12:48.843
 User Time        = 00:01:22
 System Time      = 00:00:14
 Wallclock Time   = 00:01:57
 CPU              = 00:01:36
 Max vmem         = 14.692G
 Max rss          = NA
 Exit Status      = 0
```

On completion:

```console
$ cat riboviz-simdata-8710129-<NODE>.ecdf.ed.ac.uk.o 
Running Nextflow riboviz...
N E X T F L O W  ~  version 20.04.1
Launching `prep_riboviz.nf` [tiny_mccarthy] - revision: e13128e34f
[3b/f97984] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[4e/29f5f2] Submitted process > cutAdapters (umi5_umi3)
[cf/45aecb] Submitted process > buildIndicesrRNA (yeast_rRNA)
[de/630d7e] Submitted process > extractUmis (umi5_umi3)
[86/cea2dd] Submitted process > hisat2rRNA (umi5_umi3)
[6a/be7c01] Submitted process > hisat2ORF (umi5_umi3)
[50/dc9165] Submitted process > trim5pMismatches (umi5_umi3)
[60/989427] Submitted process > samViewSort (umi5_umi3)
[ae/e53325] Submitted process > groupUmisPreDedup (umi5_umi3)
[24/f49785] Submitted process > dedupUmis (umi5_umi3)
[da/89e710] Submitted process > outputBams (umi5_umi3)
[f0/484f35] Submitted process > groupUmisPostDedup (umi5_umi3)
[88/14965a] Submitted process > bamToH5 (umi5_umi3)
[1d/299c04] Submitted process > makeBedgraphs (umi5_umi3)
[e6/dde2f5] Submitted process > generateStatsFigs (umi5_umi3)
Finished processing sample: umi5_umi3
[9f/a62171] Submitted process > renameTpms (umi5_umi3)
[7b/faa8ad] Submitted process > collateTpms (umi5_umi3)
[2f/b6b9c7] Submitted process > countReads
Workflow finished! (OK)
Nextflow riboviz run complete!

$ pytest riboviz/test/regression/test_regression.py \
    --expected=vignette-orig-nf \
    --config-file=vignette/simdata_umi_config.yaml \
    --skip-workflow --nextflow --check-index-tmp

=================== 50 passed, 3 skipped, 1 warning in 2.85s ===================
```

**Comment by mikej888** [comment]
`jobs/eddie-template.sh` has:

```
#$ -pe sharedmem %%job_num_cpus%%
```

However, #231 makes reference to `-pe mpi`, which in templated form would be:

```
#$ -pe mpi %%job_num_cpus%%
```

`-pe` is a [parallel environment](https://www.wiki.ed.ac.uk/display/ResearchServices/Parallel+Environments). Should this be configurable too e.g.

```
#$ -pe %%job_parallel_env%% %%job_num_cpus%%
```

?

**Comment by kavousan** [comment]
@FlicAnderson, @ewallace, please have a go (see branch py-create-job-submission-script-228) and provide feedback.

**Comment by mikej888** [comment]
Update template to `#$ -pe %%job_parallel_env%% %%job_num_cpus%%` with `job_parallel_env` to be `mpi` by default.

**Comment by mikej888** [comment]
Updated to support `job_parallel_env` (`mpi` by default). Also added `nextflow_resume` so a job that resumes an interrupted workflow can be configured.

**Comment by FlicAnderson** [comment]
@mikej888 just submitted [this test](https://github.com/riboviz/riboviz/issues/228#issuecomment-736668378) on the branch, will update with results!

**Comment by mikej888** [comment]
In relation to comments on #231 the job submission script only supports `-with-report`. Should it also support `-with-timeline` and `-with-dag`?

**Comment by ewallace** [comment]
Confirming that Mike's example above created a job submission script, then placed it in job submission with qsub; it hasn't run yet.

Should I test on a full-size example dataset before we close the issue?

I think it would be nice, but not strictly necessary, to add `-with-timeline` and `-with-dag`.

**Comment by mikej888** [comment]
If adding `-with-dag`, see if EDDIE has a module with graphviz and use `nextflow.svg` as default value, if so, otherwise `nextflow.dot` or `nextflow.html` if not. User would be able to override to choose the preferred format anyway - this is determined by the file name extension.

Users can convert .dot to .svg using GraphViz on their own machines:

```console
$ dot -T svg nextflow.dot -o nextflow.svg
```

**Comment by ewallace** [comment]
We need to change default nextflow working directory to something on scratch space, in response to today's email from Mike Wallis at Eddie/ECDF:

> Please DO NOT run jobs in home directories as this can cause issues for other users.
> 
> We strongly advise people run jobs on the /scratch filesystem or in eddie group space because the quotas available on those volumes are much higher than in your home directory and you won’t accidentally fill up the home directory volume (which has been happening over the last few weeks).
> 
> If you are running jobs with a working directory in $HOME (symbolic links to /scratch in home are fine) please adjust your scripts to output files to a different directory as a matter of urgency.

I'm happy to attack this soon when I turn to testing the script.

**Comment by FlicAnderson** [comment]
I ran this to test it out with example-datasets/#19 dataset (as mentioned [here](https://github.com/riboviz/example-datasets/issues/19#issuecomment-782170583)). 

I've created a validate-only submission script & a main-run script.  

I haven't set these up to start running yet as I've got something else going now, but aim to submit them at the start of next week.

**Comment by FlicAnderson** [comment]
Ran into issues when testing [the scripts mentioned above](https://github.com/riboviz/riboviz/issues/228#issuecomment-782199122) which I think arise from the methods I'm using in setting up datasets to run (with symlinked folders pointing to a location on scratch), and possibly also due to the default `-work-dir work` part filling up my home drive when run, which caused lots of unexpected and odd errors. I abandoned testing in order to get other things running as they were higher on my priority list for now. 

The home directory work output breakage was probably my fault, as I didn't seek out any documentation for the `riboviz.tools.create_job_script` tool, instead just going with an example usage from the issue ticket, so if there was advice on how to ensure you edit the `-work-dir work` parameter & location, I missed it and didn't clock this issue in the nextflow run command before pressing "GO". 

I think this job submission script code might be more useful following an update after we hear back and have further advice from Angela & Mike Wallis re: running on specific nodes on Eddie (riboviz/#236), as this would bring faster job start times than the current parameters I think.

It might also be handy to include some of @mikej888's work from [example-datasets/#27](https://github.com/riboviz/example-datasets/issues/27) and riboviz/#274 as these address some of the paths snarls and would be good to incorporate.

**Comment by mikej888** [comment]
> The home directory work output breakage was probably my fault, as I didn't seek out any documentation for the riboviz.tools.create_job_script tool, instead just going with an example usage from the issue ticket, so if there was advice on how to ensure you edit the -work-dir work parameter & location, I missed it and didn't clock this issue in the nextflow run command before pressing "GO".

[Create job submission script from template](https://github.com/riboviz/riboviz/blob/py-create-job-submission-script-228/docs/user/create-job-script.md) provides usage info. To set the Nextflow work directory you can define `nextflow_work_dir` in YAML or provide `---nextflow-work-dir` at the command-line e.g.

```console
$ python -m riboviz.tools.create_job_script -i jobs/eddie-template.sh -o example_job.sh \
    --r-libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary \
    --config-file vignette/vignette_config.yaml --nextflow-work-dir /some/scratch/dir
```
This produces `example_job.sh` with invocation:
```
nextflow run prep_riboviz.nf -params-file vignette/vignette_config.yaml -work-dir /some/scratch/dir -ansi-log false -with-report nextflow-report.html  
```

**Comment by mikej888** [comment]
> I think it would be nice, but not strictly necessary, to add -with-timeline and -with-dag.

Commit a96353e on [py-create-job-submission-script-228](https://github.com/riboviz/riboviz/tree/py-create-job-submission-script-228) adds support `nextflow_dag_file`, `nextflow_timing_file`, `nextflow_trace_file` parameters (for customising job submission script templates).

Nextflow [trace reports](https://www.nextflow.io/docs/latest/tracing.html#trace-report) are TSV files with execution traces.

The Default DAG filename is `nextflow-dag.html` to avoid problems on EDDIE with GraphViz (`dot`) not being available which can arise if an SVG visualisation is requested. As the extension determines the format of the visualisation users with GraphViz can override the report name with, for example `nextflow-dag.svg`.

Here is an example on EDDIE. I used `--job-parallel-env sharedmem` as the default, `mpi`, meant jobs spent a very long time in the queue)

```console
$ python -m riboviz.tools.create_job_script \
    -i jobs/eddie-template.sh \
    -o run-simdata-sharedmem.sh \
    --config-file vignette/simdata_umi_config.yaml \
    --r-libs /exports/csce/eddie/biology/groups/wallace_rna/Rlibrary \
    --job-name riboviz-simdata \
    --job-runtime 12:00:00 \
    --job-memory 8G \
    --job-num-cpus 2 \
    --job-parallel-env sharedmem
$ qsub -P bio_wallace_rna_riboviz run-simdata-sharedmem.sh
...
$ ls -1
nextflow-dag.html
nextflow-report.html
nextflow-timeline.html
nextflow-trace.tsv
```

**Comment by kavousan** [comment]
@3mma-mack to try this on the next dataset; new ticket required.

**Comment by mikej888** [comment]
Merged as https://github.com/riboviz/riboviz/pull/288

**Comment by mikej888** [comment]
> @3mma-mack to try this on the next dataset; new ticket required.

See #289.
