### ISSUE TITLE
Can deletion of Nextflow 'work' directory be automated?

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#235]
Arising from #228...

When we scale up to more datasets, we will need to delete the work folder and intermediate files if the job completes successfully with no errors.

* Could that be an option in the job submission script?
* Does it belong somewhere else, i.e. in nextflow pipeline? Is there a Nextflow option?
* What if the job completes successfully with no errors but on inspection the results are invalid somehow? The work directory, and intermediate files, will be lost.

**Comment by mikej888** [comment]
Only a specific user can tell if it is safe to delete intermediate files, and that can only be done after they've inspected them. After that, no solution will be quicker than `rm -rf work`.

**Comment by kavousan** [comment]
Mike's view was accepted; we are not able to automate.
