### ISSUE TITLE
R packages: install single `tidyverse` meta-package, or install several tidyverse-stable packages separately?

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#251]
Came up via work on integrating #239 

:question: is it worth swapping to meta-package `tidyverse` in installation of riboviz, rather than maintaining multiple separate tidyverse stable packages separately? 

:heavy_plus_sign:  Arguments for meta-package: simpler, less install lines to do/forget to do, more modern R way of doing things. 

:heavy_minus_sign: Arguments against meta-package: would an updated version in 1 package break the install if other versions of other packages are still required? Potentially bloat-y if we don't use all the packages? Would it be more difficult to find/resolve package install issues? Is the order of package install (and therefore masked functions/objects) important in riboviz? Would this be affected if we swap to 'tidyverse' package with 1 load (library) command?

**Comment by FlicAnderson** [comment]
@mikej888 @ewallace any opinions/ideas on this?

**Comment by mikej888** [comment]
Also another advantage of a meta-package is hopefully its packages will be consistent in terms of versioning.

I guess there is a tradeoff between the number of unused packages it would install vs. the number of packages it saves the user from installing.

I think the idea is fine but it'd need tested on a fresh VM to ensure that no unforeseen dependency issues arose.

**Comment by FlicAnderson** [comment]
Marking this closed as we're now using `tidyverse` package by preference.
