### ISSUE TITLE
Tiny simulated data

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#253]
As discussed 13/01/2020, it would be helpful to have some tiny simulated data to write unit tests for code such as `bam_to_h5.R` (see #238).

Suggestion is:
* @ewallace designs tiny fasta/gff files with a couple of short genes with short ORFs, uploads them to [example_datasets](riboviz/example_datasets).
* @amandamok then simulates some data with, a small number of reads (10?) across this tiny transcriptome.
* we share these with riboviz team to run tests.

**Comment by ewallace** [comment]
I designed/drafted a tiny annotation file, see [example-datasets#26](https://github.com/riboviz/example-datasets/pull/36).

Hopefully that makes it easy to simulate some reads? Unless they are too tiny?

**Comment by amandamok** [comment]
https://github.com/amandamok/simRiboSeq/tree/master/simulation_runs/riboviz
commit 8367709

- `tiny_2genes.fq`: fastq file of footprint reads with adaptor sequence `CTGTAGGCACCATCAAT`
- `tiny_2genes_footprints.sam`: alignment file of reads aligned with hisat2 to tiny_2genes_20utrs.fa
- `tiny_2genes_counts.tsv`: table of read counts by transcript, codon position, read length, read frame
