### ISSUE TITLE
Ingest pyRNATagSeq demultiplexer and deduplicator code

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#26]
Edward's [pyRNATagSeq](https://github.com/ewallace/pyRNATagSeq) includes scripts to:

* [SplitRNATagSeqFastQ.py](https://github.com/ewallace/pyRNATagSeq/blob/master/SplitRNATagSeqFastQ.py): split at left end, assuming the barcode is on the left.
* [DedupEndFastQ.py](https://github.com/ewallace/pyRNATagSeq/blob/master/DedupEndFastQ.py): deduplicate based on UMI at left end.

Ingest into RiboViz.

Update to split on a 5 nucleotide barcode on right and deduplex for UMI on a mixture of both left and right.

**Comment by ewallace** [comment]
Fixed in course of #84, closed by #117.
