### ISSUE TITLE
Make hisat2ORF options flexible for multi-mapping etc.

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#267]
Check how we specify hisat2 options in nextflow. Specifying hisat2 alignment and multimap options in the nextflow call gives flexibility in addressing #241.

**Comment by ewallace** [comment]
We discussed this at the 27th Jan 2021 meeting.

@lianafaye pointed out that `-k 2` [hisat2 option (reporting up to 2 highest-score alignments)](https://daehwankimlab.github.io/hisat2/manual/) causes a problem in yeast because some highly expressed genes are in 2 near-identical copies, so will be double-counted. Notably TEF1/TEF2 and some ribosomal protein genes. We are not sure which other organisms/genes this will be a problem for. We could avoid this by changing to `-k 1`, but it is unclear if this is "uniformly at random" assignment or not from the hisat2 manual.

We should check if other aligners deal with this randomness better (e.g. STAR); or can try a better method like RSEM.

For now, we will fix by allowing the user to choose their options.

* In `prepriboviz.nf` process `hisat2ORF`, `-k 2` is currently hard-coded. We need to make this a parameter in the `config.yaml`, that users can choose.
* We need to add some documentation on the option about why users would choose one rather than another.
* We should contact hisat2 team to ask if multi-mapping reads are aligned deterministically or not.

**Comment by ewallace** [comment]
I submitted issue [hisat2#279](/DaehwanKimLab/hisat2/issues/279) to request clarification.

Closer inspection of the `--non-deterministic` option documentation: 
> Normally, HISAT2 re-initializes its pseudo-random generator for each read. [...]

This suggests that the combination of `-k 1` and default hisat2 settings will indeed produce a different pseudo-random assignment for each read in a fastq file. But it isn't quite explicitly stated anywhere.

**Comment by ewallace** [comment]
We discussed this on 23rd June and I would like to prioritize putting hisat2 options in the config file.

@lianafaye, @shahpr and I think that`k = 1` is a better default, but are sceptical that we don't know how hisat2 does random assignment.
We could test that with a simulated dataset with some duplicate ORFs.

**Comment by ewallace** [comment]
@kavousan a note, can we put this on the agenda for next meeting?

**Comment by ewallace** [comment]
I am thinking that the options could be passed in as a string, that has default value "-k 2" as used in commit bf06a94 (or "-k 2 -un unaligned.fq" if we were simultaneously addressing #377).  I do not know what is best practice for specifying multiple command line options for nextflow in a yaml file. It would be "easy" to do as a single string but might give the user more opportunity to break the code, add duplicate options erroneously, etc.

Steps to address this could be:
* [ ] add hisat2ORF command line options to config.yaml
* [ ] ensure that those command line options are passed to hisat2ORF only (not hisat2rRNA?)
* [ ] check that vignette tests pass with same value "-k 2"
* [ ] document the differences in a full-size yeast dataset if "-k 2 --non-deterministic", "-k 1 --non-deterministic", "-k 1" are used.

Might @canuse be willing to address this issue? Should be a quick-ish fix. But it may not fit with the goals of his project.

**Comment by mikej888** [comment]
Invocation from `prep_riboviz.nf`, `process hisat2ORF`:

```
hisat2 -p ${params.num_processes} -k 2 --no-spliced-alignment \
  --rna-strandness F --no-unal \
  --un unaligned.fq -x ${params.orf_index_prefix} \
  -S orf_map.sam -U ${sample_fq}
```

Argument descriptions for HISAT 2.1.0, from `hisat2 -h`:

| Argument | Description | Default value |
| -------- | ----------- | ------------- |
| `-p ${params.num_processes}` | Number of alignment threads to launch | 1 |
| `-k 2` | Report up to <int> alns per read | 5 |
| `--no-spliced-alignment` | Disable spliced alignment | |
| `--rna-strandness F` | Specify strand-specific information | unstranded |
| `--no-unal` | Suppress SAM records for reads that failed to align | |
| `--un unaligned.fq` | Write unpaired reads that didn't align to <path> | - |
| `-x ${params.orf_index_prefix}` | Index filename prefix (mandatory) | - |
| `-S orf_map.sam` | File for SAM output | stdout |
| `-U ${sample_fq}` | File with unpaired reads (input) | - |

`--no-unal` isn't in the `-h` text but is documented in the [HISAT2 Manual](http://daehwankimlab.github.io/hisat2/manual/).

**Comment by mikej888** [comment]
Commit f4c9327 of branch [hisat2-options-267](https://github.com/riboviz/riboviz/tree/hisat2-options-267) adds a new `hisat2_orf_params` configuration parameter...

Added:
```
hisat2_orf_params: -k 2 --no-spliced-alignment --rna-strandness F --no-unal
```
to:
```
riboviz/default_config.yaml
vignette/remote_vignette_config.yaml
vignette/riboviz_env.yaml
vignette/simdata_multiplex_config.yaml
vignette/simdata_umi_config.yaml
vignette/vignette_config.yaml
riboviz/test/config/config_current.yaml
```

Added `HISAT2_ORF_PARAMS = "hisat2_orf_params"` to `riboviz/params.py`.

Updated `prep_riboviz.nf`:

* Added description of `hisat2_orf_params` and default value to `helpMessage()`.
* Added definition of parameter and default value:
```
params.hisat2_orf_params = "-k 2 --no-spliced-alignment --rna-strandness F --no-unal"
```
* Updated `process hisat2ORF` to use parameter:
```
        hisat2 -p ${params.num_processes} ${params.hisat2_orf_params} \
            --un unaligned.fq -x ${params.orf_index_prefix} \
            -S orf_map.sam -U ${sample_fq}
```

Updated `docs/user/prep-riboviz-config.md` with parameter description, references to `hisat2 -h` and hisat2 manual for available parameters, and the caveat that files cannot be specified in this parameter.

**Comment by mikej888** [comment]
Arguments that take file names need (e.g. `--un unaligned.fq`, the subject of '-un flag in hisat2 may affect the performance' #377) need the Nextflow `hisat2ORF` process itself to be changed, since the process needs to declare its input and output files.

**Comment by mikej888** [comment]
@ewallace commented that

> It would be "easy" to do as a single string ...

This is the approach I have implemented. The alternative is trying to anticipate what parameters users might want to set and then having to incrementally add these. As there are over 50 `hisat2` configuration parameters, this isn't scalable.

> but might give the user more opportunity to break the code, add duplicate options erroneously, etc.

The worst case is that a user provides a configuration that `hisat2` doesn't accept and that workflow step will fail (as expected). That risk is no more or less than the risk any user takes when executing `hisat2` from the command-line. If users don't know what the configuration does and experiments with it anyway then they are accepting the risk that things will fail.

**Comment by mikej888** [comment]
If the default, `"-k 2 --no-spliced-alignment --rna-strandness F --no-unal"` needs changed then the definition of parameter and its default value in the following files needs to be updated:
```
riboviz/default_config.yaml
vignette/remote_vignette_config.yaml
vignette/riboviz_env.yaml
vignette/simdata_multiplex_config.yaml
vignette/simdata_umi_config.yaml
vignette/vignette_config.yaml
riboviz/test/config/config_current.yaml
docs/user/prep-riboviz-config.md
prep_riboviz.nf
```

**Comment by mikej888** [comment]
I ran the vignette with four values of `--hisat2_orf_params`:
```
"-k 1 --no-spliced-alignment --rna-strandness F --no-unal"
"-k 1 --non-deterministic --no-spliced-alignment --rna-strandness F --no-unal"
"-k 2 --no-spliced-alignment --rna-strandness F --no-unal"
"-k 2 --non-deterministic --no-spliced-alignment --rna-strandness F --no-unal"
```
```console
$ rm -rf vignette/index vignette/tmp vignette/output
$ nextflow run prep_riboviz.nf -ansi-log false -params-file vignette/vignette_config.yaml --hisat2_orf_params=<VALUE>
$ cp -r vignette vignette-k1|k1-nondet|k2|k2-nondet
```
Use the integration test to compare outputs:

1. Compare `-k 1` to `-k 1 --non-deterministic`:
```console
$ rm -rf vignette
$ cp -r vignette-k1 vignette
$ pytest -vs riboviz/test/integration/testegration.py --expected=vignette-k1-nondet --skip-workflow --check-index-tmp
```
2. Compare `-k 1` to `-k 2`:
```console
$ pytest -vs riboviz/test/integration/testegration.py --expected=vignette-k2 --skip-workflow --check-index-tmp
```
3. Compare `-k 2` to `-k 2 --non-deterministic`:
```console
$ rm -rf vignette
$ cp -r vignette-k2 vignette
$ pytest -vs riboviz/test/integration/testegration.py --expected=vignette-k2-nondet --skip-workflow --check-index-tmp
```

In each case, the first tests to fail are the comparisons of the `orf_map.sam` files output by `hisat2ORF`:

```
FAILED riboviz/test/integration/test_integration.py::test_hisat2_sam[vignette/tmp-WTnone-orf_map.sam]
FAILED riboviz/test/integration/test_integration.py::test_hisat2_sam[vignette/tmp-WT3AT-orf_map.sam]
```

The `unaligned.fq` files output remain unchanged.

**Comment by mikej888** [comment]
> Document the differences in a full-size yeast dataset if "-k 2 --non-deterministic", "-k 1 --non-deterministic", "-k 1" are used.

This needs to be done by someone who knows what differences to look for.

**Comment by mikej888** [comment]
Merged @447.
