### ISSUE TITLE
Add UMI example to documentation

### ISSUE THREAD

**Issue by 3mma-mack** [riboviz/riboviz#279]
Adding an example of a UMI regular expression where UMI's are only present at one end of the strand to prevent confusion about the need for  '^' and '$' in the regular expression for `umi_regexp` parameter in a new dataset's configuration file.

Currently all the examples present in the [configuration documentation](https://github.com/riboviz/riboviz/blob/master/docs/user/prep-riboviz-config.md) have '^' and '$' at the start and end of their expressions, which led to confusion about whether they were just part of the format of a regular expression.

**Comment by 3mma-mack** [comment]
I've created the branch umi-example-docs-279, and plan to add the regular expression used for the Weinberg dataset to the documents there

**Comment by 3mma-mack** [comment]
I have added the line '`(?P<umi_1>.{8})` extracts an 8nt UMI from the 5' end of the read.' to [prep-riboviz-config.md](https://github.com/riboviz/riboviz/blob/umi-example-docs-279/docs/user/prep-riboviz-config.md) on the new umi-example-docs-279 branch. I will have a think about if there is anything else I could add overnight.

**Comment by ewallace** [comment]
This looks great. I have a (hopefully) simple suggestion: 

1. Go through all the config.yaml files currently in example-datasets and see if any of them has UMIs that we don't have.
2. Add them. 
3. Maybe also add a link for each example UMI regex to an example-dataset that uses it, which would put it in context?

**Comment by 3mma-mack** [comment]
I've done some hunting through the branches in example datasets and could only find three examples of config yamls with a non null  `umi-regexp`, the [Saccharomyces Weinberg dataset](https://github.com/riboviz/example-datasets/blob/weinberg_2016_dataset-20/fungi/saccharomyces/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml), the [Saccharomyces Gupta dataset](https://github.com/riboviz/example-datasets/blob/master/fungi/saccharomyces/Gupta_2018_tRNA_Modification_Carbon_Nitrogen_Metabolism_RPF_9-samples_CDS_w_250utrs_config.yaml) and the [E. coli Favate dataset](https://github.com/riboviz/example-datasets/blob/master/bacteria/ecoli/Favate_2020_unpublished.yaml ). I have added the Favate and Gupta `umi-regexp` as an example seeing as they share the same expression and have included links to the relevant config files.

I noticed that a few of the config. yamls do not have `umi-regexp` parameter, the [neurospora RiboViz_Yu2015_config.yaml](https://github.com/riboviz/example-datasets/blob/master/fungi/neurospora/RiboViz_Yu2015_config.yaml), the [Saccharomyces Iserman_2020 config.yaml]( https://github.com/riboviz/example-datasets/blob/Iserman-heatshockDed1-15/fungi/saccharomyces/Iserman_2020_heatshock_RPF_12-samples_CDS_w_250utrs_config.yaml), and the [Candida Muzzey_2014 config.yaml](https://github.com/riboviz/example-datasets/blob/fungi-muzzey-2014-candida/fungi/candida/Muzzey_2014_RPF_CAlbi_CDS_with_120utrs_config.yaml) but I'm assuming these would be null.

**Comment by FlicAnderson** [comment]
> I noticed that a few of the config. yamls do not have `umi-regexp` parameter, the [neurospora RiboViz_Yu2015_config.yaml](https://github.com/riboviz/example-datasets/blob/master/fungi/neurospora/RiboViz_Yu2015_config.yaml), the [Saccharomyces Iserman_2020 config.yaml](https://github.com/riboviz/example-datasets/blob/Iserman-heatshockDed1-15/fungi/saccharomyces/Iserman_2020_heatshock_RPF_12-samples_CDS_w_250utrs_config.yaml), and the [Candida Muzzey_2014 config.yaml](https://github.com/riboviz/example-datasets/blob/fungi-muzzey-2014-candida/fungi/candida/Muzzey_2014_RPF_CAlbi_CDS_with_120utrs_config.yaml) but I'm assuming these would be null.

Hi @3mma-mack - you're right, if there's no parameter, it's read as a null. These config files were probably set up before the `umi-regexp` parameter became 'a thing'.
