### ISSUE TITLE
Bring in new datasets

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#29]
We need to test-run RiboViz on some new datasets to check that it can actually work. These will not be incorporated into the automated testing, but will provide a larger informal test. And also move towards asking new substantial biological questions with RiboViz.

Ideas:
- Muzzey 2014 _Candida albicans_ (2 reps)
- Weinberg 2016 _Saccharomyces cerevisiae_ (1 rep, "standard")
- Polymenis 2018 _Saccharomyces cerevisiae_ mitosis (3 reps in many conditions)
- Duncan and Mata _Schizosaccharomyces pombe_ (up to 7 reps, useful for stats)

@ewallace will share the .yaml file for Mussey 2014, and track down the references and accession numbers for the others so that @FlicAnderson can start attacking them.

**Comment by ewallace** [comment]
Sent to @FlicAnderson and @mikej888 info inc yaml files and transcriptome annotation for Muzzey et al, https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52236

> Muzzey D, Sherlock G, Weissman JS. Extensive and coordinated control of allele-specific expression by both transcription and translation in Candida albicans. Genome Res 2014 Jun;24(6):963-73. PMID: 24732588

**Comment by ewallace** [comment]
Weinberg & Shah 2016 dataset is
Improved Ribosome-Footprint and mRNA Measurements Provide Insights into Dynamics and Regulation of Yeast Translation.
https://www.ncbi.nlm.nih.gov/pubmed/26876183
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE75897

I do not have a .yaml file for them. _Saccharomyces cerevisiae_ annotation files (250nt padding) available in `RiboViz/docs/prepare-data.md`

**Comment by ewallace** [comment]
@shahpr and/or @lianafaye, can you reommend one dataset with the new inline barcodes?

**Comment by shahpr** [comment]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE124428



On Jul 22, 2019, at 2:08 PM, Edward Wallace <notifications@github.com<mailto:notifications@github.com>> wrote:


@shahpr<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshahpr&data=02%7C01%7Cpremal.shah%40rutgers.edu%7Ceeec9b3fba79466d661a08d70ecf98df%7Cb92d2b234d35447093ff69aca6632ffe%7C1%7C0%7C636994157096159274&sdata=X6rYYD4xUkOCpdEVZgY%2FGlKtl0yzyjK2lhZobUoaG1k%3D&reserved=0> and/or @lianafaye<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flianafaye&data=02%7C01%7Cpremal.shah%40rutgers.edu%7Ceeec9b3fba79466d661a08d70ecf98df%7Cb92d2b234d35447093ff69aca6632ffe%7C1%7C0%7C636994157096169271&sdata=JlfoOVy94wDphuINfOC4VRrugYHtf0YhTrE2dzpywBc%3D&reserved=0>, can you reommend one dataset with the new inline barcodes?

**Comment by ewallace** [comment]
Also we can extend to a larger part of the Guydosh & Green 2014 dataset, that we subsampled for the vignette, described in #31.

**Comment by ewallace** [comment]
Relevant Duncan & Mata dataset is from this paper: [General amino acid control in fission yeast...](https://www.pnas.org/content/115/8/E1829.long)
Data are on ArrayExpress [E-MTAB-5810](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-5810/)

**Note structure of the read includes UMIs, described in Data Preprocessing and Read Alignment.** 
> For all other ribosome profiling samples, the structure of the reads is as follows: RRRR(NNNN…NNNN)RRRR-adaptor-, where R represents random nucleotides; N corresponds to the sequence of the RNA protected fragment; and the adaptor sequence is TGGAATTCTCGGGTGCCAAGG. 

The pipeline as currently conceived does not deal with random nucleotide UMIs. Also, the structure differs for 2 samples which also have sample barcodes RRRRRRRRRRRR(NNNN….NNNN)BBB so we may wish to exclude them (wt.noAT.ribo.2 / wt.AT.ribo.2) from the initial analysis.

These are the kinds of problems we need to extend the pipeline to deal with. We could ignore the UMIs by trimming the random nucleotides at the ends, but that still requires another step to the pipeline. This dataset could be a good test case for flexible way to deal with UMIs.

**Comment by kavousan** [comment]
28 August update: 

Flic has taken a full dataset and configured RiboViz to run on this. The next steps will be to try other datasets in the same pattern. Edward will inspect the data to validate it.

This spawned discussion on Quality Assurance #56 and also logging #55.

**Comment by kavousan** [comment]
Bring Muzzey 2014 Candida albicans as a full dataset; then downsample as per https://github.com/riboviz/RiboViz/issues/38

**Comment by kavousan** [comment]
@FlicAnderson: when feasible, please update the ticket with current progress.

**Comment by FlicAnderson** [comment]
Update of the datasets I'm working on getting through RiboViz:
Note: for my own sanity and own notes I'm using a 'codename format' of: 
[First Author's First Surname Letter]-[Genus-species first letters]_[publication year]
 

- [X] G-Sc_2014 (Guydosh & Green; *Saccharomyces cerevisiae*; no UMIs, no barcodes) :+1:  
- [ ] [in progress] M-Ca_2014 (Muzzey et al; *Candida albicans*; no UMIs, no barcodes, 2 reps)
- [ ] W-Sc_2016 (Weinberg & Shah 2016; *Saccharomyces cerevisiae*; no UMIs, no barcodes, 1 rep, "standard") 
- [ ] P-Sc_2018 (Polymenis 2018; *Saccharomyces cerevisiae* mitosis; with UMI, no barcodes, 3 reps in many conditions) 
- [ ] D-Sp_2018 (Duncan & Mata 2018; *Schizosaccharomyces pombe*; with UMI, no barcodes, up to 7 reps, useful for stats) 
- [ ] G-Sc_2019 (Gupta et al 2019; Premal's with UMI & with barcodes) (#39 )

G-Sc_2014 Guydosh & Green data was successfullly run late August (will shortly re-run with newly re-factored prep_riboviz.py)

M-Ca_2014 Muzzey data was run semi-successfully 09th Sept; majority of the pipeline ran, but due to different organism and lack of features_file (yeast_features.tsv does not apply to *Candida albicans*), the pipeline broke down when calling the missing value into generate_stats_figs.R.  This has been set up as issue #66 and I've created a branch to fix this in (handle-missing-features-file-66) and will work on that fix to complete the data run

W-Sc_2016 has not been run yet but should hopefully pose less of an immediate challenge :crossed_fingers:, and after running that I can work on creating downsampled dataset from M-Ca_2014 as agreed in issue #38 

After that, I'll be able to work on the UMI-containing datasets and work on the *Schizosaccharomyces pombe* data which hasn't been run through RiboViz previously (while the first 3 datasets have previously been successfully run through previous versions).

**Comment by FlicAnderson** [comment]
Via Liana during meeting 02 Oct: 
> Weinberg reads are 8 random nucleotides, then the footprint, and then the adapter is TCGTATGCCGTCTTCTGCTTG

**Comment by FlicAnderson** [comment]
Update: 
M-Ca_2014 dataset being re-run with latest develop to test fix #66
W-Sc_2016 dataset turns out to be a UMI dataset as per [comment "8 random nucleotides"](https://github.com/riboviz/RiboViz/issues/29#issuecomment-537590625), so will need UMI handling capabilities

**Comment by kavousan** [comment]
We want to see how long W-Sc_2016 takes to run; then we create a vignette from it.

To then test on one of the files of D-Sp_2018.

**Comment by FlicAnderson** [comment]
Progress update on datasets: 

- [x] G-Sc_2014 (Guydosh & Green; Saccharomyces cerevisiae; no UMIs, no barcodes) +1
- [x] M-Ca_2014 (Muzzey et al; Candida albicans; no UMIs, no barcodes, 2 reps)
- [x] W-Sc_2016 (Weinberg & Shah 2016; Saccharomyces cerevisiae; 8-NT 5' UMIs, no barcodes, 1 rep, "standard")
- [ ] **next target >>** D-Sp_2018 (Duncan & Mata 2018; Schizosaccharomyces pombe; with UMI, no barcodes, up to 7 reps, useful for stats)
- [ ] P-Sc_2018 (Polymenis 2018; Saccharomyces cerevisiae mitosis; with UMI, no barcodes, 3 reps in many conditions)
- [ ] G-Sc_2019 (Gupta et al 2019; Premal's with UMI & with barcodes) (#39)

**G-Sc_2014** Guydosh & Green data initially run late August, will shortly re-run to obtain new plot outputs from ribogrid-plot-68 feature (now in develop)

**M-Ca_2014** Muzzey data run successfully on 09 Oct on branch develop, last commit db73b2e81, run time: ~2 hours (8 processors)

**W-Sc_2016** Weinberg data run successfully 20 Oct on branch: use-umi-tools-dedup-58, last commit 632911e3, run time: 3 hours (8 processors)

**Next dataset:** Setting up and finding read (1 sample of 7 total samples) and genome files for D-Sp_2018, as agreed will contact Edward re: any missing or non-obvious files; set up yaml. Run with use-umi-tools-dedup-58 or develop, depending on whether these changes are merged into develop yet or not, as this is UMI dataset

**Next downsampled dataset:** Can start creating downsampled dataset from M-Ca_2014 as agreed in issue #38, next downsampled dataset AFTER M-Ca_2014 will include UMIs, but will be something with more than one sample file (ie not W-Sc_2016 as this is single read file).

**Comment by kavousan** [comment]
@ewallace asked @lianafaye and @shahpr to look at the outputs from W-Sc_2016 Weinberg. 

Agreed that D-Sp_2018 Schizosaccharomyces pombe is a good choice to be the next dataset just now; important dataset that does not require demultiplexing (which we don't yet have).

**Comment by kavousan** [comment]
@ewallace has found some issues with the above outputs and @FlicAnderson has addressed them.

We postpone the review until after we have closed #58.

**Comment by ewallace** [comment]
Also we should add the 14-replicate dataset from C-Sc_2017: Chou et al 2017 [Transcriptome-wide Analysis of Roles for tRNA Modifications in Translational Regulation](https://doi.org/10.1016/j.molcel.2017.11.002)

**Comment by ewallace** [comment]
We have made huge amounts of progress on this in [riboviz/example-datasets](https://github.com/riboviz/example-datasets). Let's go through this ticket, create a separate issue for each dataset in [riboviz/example-datasets](https://github.com/riboviz/example-datasets), then close it.

**Comment by ewallace** [comment]
Gupta et al 2019 is being addressed in [example-datasets#14](https://github.com/riboviz/example-datasets/issues/14) by @acope3.

**Comment by FlicAnderson** [comment]
> We have made huge amounts of progress on this in [riboviz/example-datasets](https://github.com/riboviz/example-datasets). Let's go through this ticket, create a separate issue for each dataset in [riboviz/example-datasets](https://github.com/riboviz/example-datasets), then close it.

All datasets have a separate issue ticket in example-datasets and can be followed up on there, so I'm now closing this ticket.
