### ISSUE TITLE
Discuss kebab-case vs. snake_case use within YAML configuration and command-line parameters

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#296]
Our command-line tools use `kebab-case` parameters, for consistency with each other and most bash/Linux command-line tools.

Our YAML configuration uses `snake_case` parameters

From #289, `create_job_script` takes command-line parameters corresponding to those in the YAML configuration, with a suitable change of delimiter e.g. to specify job name in the YAML one uses `job_name`, to specify it at the command-line one uses `--job-name`. This inconsistency may provide problematic for users.

| Option | Advantages | Disadvantages |
| ------ | ---------- | ------------- |
| 1. Use snake_case in `create_job_script` | Consistent with YAML configuration parameters | Inconsistent with our other command-line scripts |
| | |  Inconsistent with most bash/Linux command-line tools |
| | | |
| 2. Use kebab-case in `create_job_script` | Consistent with our other command-line scripts | Inconsistent with YAML configuration parameters |
| | Consistent with most bash/Linux command-line tools | |
| | | |
| 3. Use snake_case in all our command-line scripts | Consistentency across YAML configuration parameters and our command-line scripts  | Inconsistent with most bash/Linux command-line tools |
| | | |
| 4. Use kebab-case in YAML configuration and command-line scripts | Consistentency across YAML configuration parameters and our command-line scripts | Requires updates to documentation, code, YAML and `prep_riboviz.nf` [1] in `riboviz/`; updates to documentation, YAML in `example-datasets`; simple tool to migrate existing YAML configuration files [2] |
| | Consistent with most bash/Linux command-line tools | |

Note: We already have inconsistency introduced by our use of snake_case in our YAML configuration. This relates to the `nextflow` command. When running `nextflow`, its built-in parameters are kebab-case (e.g. `-ansi-log`, `-params-file`) consistent with most bash/Linux command-line tools. As our own parameters are snake_case they need to be provided as such (which is why we do `--validate_only` and not `--validate-only`).

[1] A switch to kebab-case would require, in `prep_riboviz.nf` changing how `params` is used from `param.<PARAMETER_NAME>` to `param["<PARAMETER-NAME>"]` (e.g. from `params.validate_only` to `params["validate-only"]`) as Nextflow/Groovy doesn't allow hyphens in variable names.
[2] This tool could read in the YAML, using the Python `yaml` library, convert all the keys, write out the YAML. However, any comments within the YAML file would be lost. Another, more brute force, approach is to read in the YAML line by line, split each line on the first `:` to get the key, convert the key then write out the updated line.

**Comment by ewallace** [comment]
For `create_job_script`, those parameters are also going in to `qsub`, [which takes snake_case command line options](http://gridscheduler.sourceforge.net/htmlman/htmlman1/qsub.html). So in that case I'm in support of snake_case.

**Comment by mikej888** [comment]
For just `create_job_script` or all our command line tools?

**Comment by mikej888** [comment]
Discussion at 24/03/21 meeting decided on option 1).
