### ISSUE TITLE
Document provenance and use of RiboViz data files

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#31]
There are a number of data files located in the RiboViz repository e.g. within:

* https://github.com/riboviz/RiboViz/tree/master/scripts
* https://github.com/riboviz/RiboViz/tree/master/vignette/input
* https://github.com/riboviz/RiboViz/tree/master/Data

Document the provenance and use of these files i.e.

* If they are copies of files from third-party sites then:
  - What sites, when were they accessed.
  - What was the licensing of the original data.
  - What changes (if any) were made before these were added to the repository.
* If they were created by RiboViz developers then:
  - How were they created.
  - When were they created.

This information is also essential for ensuring the data is appropriately licensed (and their presence in the repository does not violate third-party licensing).

**Comment by mikej888** [comment]
`vignette/input/`:

```
SRR1042855_s1mi.fastq.gz
# Origin: ???
# Referenced in vignette_config.yaml (fq_files parameter)

SRR1042864_s1mi.fastq.gz
# Origin: ???
# Referenced in vignette_config.yaml (fq_files parameter)

yeast_rRNA_R64-1-1.fa
# Origin: ???
# Referenced in vignette_config.yaml (rRNA_fasta parameter)

yeast_YAL_CDS_w_250utrs.fa
# Origin: ???
# Referenced in vignette/vignette_config.yaml (orf_fasta parameter)

yeast_YAL_CDS_w_250utrs.gff3
# Origin: ???
# Referenced in vignette/vignette_config.yaml (orf_gff_file parameter)
# Referenced in bam_to_h5.R debug block
```

`data/`:

```
data_unq.tsv                  
# Origin: ???
# Unreferenced anywhere

testdata_trim_5p_mismatch.sam 
# Origin: ???
# Referenced in trim_5p_mismatch.py comment
# Can be used for testing trim_5p_mismatch.py
testdata_trim_5pos5neg.sam 
# Origin: ???
# Referenced in trim_5p_mismatch.py comment
# Can be used for testing trim_5p_mismatch.py

yeast_CDS_w_250utrs.fa        
# Origin: rmarkdown/script_for_transcript_annotation.Rmd execution

yeast_CDS_w_250utrs.gff3      
# Origin: rmarkdown/script_for_transcript_annotation.Rmd execution

yeast_codon_pos_i200.RData    
# Origin: rmarkdown/script_for_transcript_annotation.Rmd execution
# Read by generate_stats_figs.R

yeast_features.tsv
# Origin: ???
# Referenced in vignette_config.yaml (features_file parameter)

yeast_tRNAs.tsv
# Origin: ???
# Read by generate_stats_figs.R
```

**Comment by mikej888** [comment]
@ewallace it is unclear why some files used by the scripts invoked by prep_riboviz.py use files located in `data/` (develop branch), `scripts/` (master branch) and others in `vignette/input/`.

**Comment by ewallace** [comment]
## Vignette read data, SRR*_s1mi.fastq.gz 

Goal was to make "real" data, but small enough to run quickly. So we downsampled some ribosome profiling data from Saccharomyces cerevisiae from the paper *Guydosh & Green, Cell 2014* https://www.ncbi.nlm.nih.gov/pubmed/24581494

NCBI accession for whole dataset is # GSE52968

SRX386986: GSM1279570: wild-type no additive: [SRR1042855](https://www.ncbi.nlm.nih.gov/sra/?term=SRR1042855)
SRX386995: GSM1279579: wild-type 3-AT: [SRR1042864](https://www.ncbi.nlm.nih.gov/sra/?term=SRR1042864)

In July 2017, @ewallace imported these original files by fastq-dump and gzipped:
SRR1042855.fastq.gz
SRR1042864.fastq.gz

Then sampled uniformly at random (I think) 1/50 reads from each file, about 1 mi reads total:
SRR1042855_s1mi.fastq.gz
SRR1042864_s1mi.fastq.gz

## Yeast genome and annotation

### rRNA, yeast_rRNA_R64-1-1.fa

Ribosomal RNA (rRNA) contaminants to remove.

Selected RDN-n-n sequences were copied & pasted from the file rna_coding_R64-1-1_20110203.fasta found in [genome release R64-1-1](https://downloads.yeastgenome.org/sequence/S288C_reference/genome_releases/S288C_reference_genome_R64-1-1_20110203.tgz)

### Downsampled yeast transcriptome 

Sequence & annotation files for the whole approximate Saccharomyces cerevisiae transcriptome were made using the script_for_transcript_annotation.Rmd, data also originating from yeastgenome.org although using the next genome release R64-2-1.
As described in [prepare-data.md](https://github.com/riboviz/RiboViz/docs/prepare-data.md)
Transcript sequences, yeast_CDS_w_250utrs.fa
Coding sequences locations, yeast_CDS_w_250utrs.gff3

Vignette data files yeast_YAL_CDS_w_250utrs.fa / yeast_YAL_CDS_w_250utrs.gff3 were then created by @ewallace from these, filtering only ORFs in the left arm of chromosome 1, for which ORF names start YALnnnx. [This document describes the naming conventions.](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9783527636778.app1)

## test data for trim_5p_mismatch

testdata_trim_5p_mismatch.sam / testdata_trim_5pos5neg.sam 

These were both created by @ewallace, starting by copying and pasting a couple of lines from the vignette data, and manually editing to produce the desired range of outcomes.

**Comment by ewallace** [comment]
@shahpr could you remind us the provenance of:

* yeast_codon_pos_i200.RData
* yeast_features.tsv
* yeast_tRNAs.tsv

**Comment by mikej888** [comment]
The R script, script_for_transcript_annotation.Rmd,  is run, once per species, and this produces outputs that are put into the data/ folder (in the "develop" branch, in the "master" branch this is in the scripts/ folder). This data is organism-specific process data. vignette/input is for a user's data. The user may use varying data for analyses within the context of a single organism.

**Comment by mikej888** [comment]
@ewallace, thanks for the updates. The only two files I'm still unclear on (and which are used as part of the `prep_riboviz.py` workflow) are:

* `scripts/yeast_features.tsv (master branch) / `data/yeast_features.tsv (develop branch): referenced in vignette_config.yaml (features_file parameter) (file of features to correlate with ORFs)
* `scripts/yeast_tRNAs.tsv` (master branch) / `data/yeast_tRNAs.tsv` (develop branch): read by generate_stats_figs.R (yeast tRNA estimates)

@ewallace @FlicAnderson. I've updated the docs with the information to date:

* https://github.com/riboviz/RiboViz/blob/develop/docs/run-vignette.md#inputs
* https://github.com/riboviz/RiboViz/blob/develop/docs/developer-guide.md#data-files

**Comment by kavousan** [comment]
Where do the data for the yeast features come from? @shahpr to add to this ticket.

**Comment by ewallace** [comment]
Here are the publications from which we got the data for the yeast features:
From @shahpr regarding `yeast_features.tsv`
1. Length - [SGD](https://downloads.yeastgenome.org/sequence/S288C_reference/) (GFF) R64-2-1 I assume.
2. 5'UTR Length - [Arribere & Gilbert 2013](http://doi.org/10.1101/gr.150342.112)
3. polyA Length - [Subtelny et al., 2014](http://doi.org/10.1038/nature13007)
4. uATG - estimated from 2 by counting the upstream ATGs in the annotated 5'UTR
5. UTR_GC - estimated from 2 by calculating proportion of G/C in the annotated 5'UTR
6. FE_cap - estimated from 2 (how?)
7. FE_atg - estimated from 30 bp near ATG (how?)

@shahpr, can you tell us program (RNAfold, etc) was used to estimate the folding energies (FE, 6/7)? Then we can close the ticket.

**Comment by FlicAnderson** [comment]
Folding energy estimation method:
> To estimate 5’ cap folding energy we used sequences of length 70 nts from the 5’ end of the mRNA transcript as sequences of these lengths showed the highest correlation with TE ratios (Figure S7). We calculated the folding energies using RNAfold algorithm from Vienna RNA package (Hofacker et al., 1994) at 37 ◦C. 

> Hofacker, I. L., Fontana, W., & Stadler, P. (1994). Fast folding and comparison of RNA secondary
structures. Monatshefte f¨ur Chemie, 125, 167–188.

via [Supplementary Methods](https://www.cell.com/cms/10.1016/j.celrep.2016.01.043/attachment/257faf34-ff8f-4071-a642-bfdb531c75b8/mmc1) for Weinberg et al. 2016

Weinberg et al. 2016 *"Improved Ribosome-Footprint and mRNA Measurements Provide Insights into Dynamics and Regulation of Yeast Translation"* https://doi.org/10.1016/j.celrep.2016.01.043

**Comment by FlicAnderson** [comment]
> Folding energy estimation method:
> 
> > To estimate 5’ cap folding energy we used sequences of length 70 nts from the 5’ end of the mRNA transcript as sequences of these lengths showed the highest correlation with TE ratios (Figure S7). We calculated the folding energies using RNAfold algorithm from Vienna RNA package (Hofacker et al., 1994) at 37 ◦C.

I think this answers item 6 above (FE_cap) for `yeast_features.tsv` but I'm not sure about item 7 (FE_ATG)? 

I might have missed this if it's in the Weinberg paper amongst the other supplementary information & would appreciate if @ewallace or @shahpr can review.

**Comment by ewallace** [comment]
@shahpr confirms `FE_ATG` is 30nt *upstream* from ATG.

I think we can close this issue now.
