### ISSUE TITLE
Discuss R script import restrictions and solutions

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#310]
`collate_tpms.R` (which has only command-line-related code) imports `collate_tpms_functions.R` (which has only functions) which, in turn, imports `provenance.R`. This reflects the pattern used for our Python components (decoupling the command-line from the functionlity) and will also be necessary when moving towards bundling the R code within an R package.

As part of #33, I developed `rscripts/tests/testthat/test_collate_tpms.R` script which tests `collate_tpms` via the use of R's `system(cmd)` function, invoking it as a command-line script and validating the output file. However I wanted also to have `rscripts/tests/testthat/test_collate_tpms_functions.R` script which would test the functions of `collate_tpms_functions.R` directory. However, a significant blocker is how we import functions from other files. At present this is done via:

```R
# Load local dependencies.
if (interactive()) {
  # Use hard-coded script name and assume script is in "rscripts"
  # directory. This assumes that interactive R is being run within
  # the parent of rscripts/ but imposes no other constraints on
  # where rscripts/ or its parents are located.
  self <- "collate_tpms_functions.R"
  path_to_self <- here("rscripts", self)
  source(here::here("rscripts", "provenance.R"))
} else {
  # Deduce file name and path using reflection as before.
  self <- getopt::get_Rscript_filename()
  path_to_self <- self
  source(file.path(dirname(self), "provenance.R"))
}
```
However, a shorter version can be:
```R
if (interactive()) {
  here::i_am("rscripts/collate_tpms_functions.R")
  root <- file.path(here(), "rscripts")
} else {
  root <- dirname(getopt::get_Rscript_filename())
}
print(paste0("collate_tpms_functions.R root: ", root))
source(file.path(root, "provenance.R"))
```
Regardless, either of these fail if imported via tests. 

If imported within `collate_tpms.R` all is fine. `getopt::get_Rscript_filename()` within `collate_tpms_functions.R` returns `/<path>/rscripts/collate_tpms.R` with the path used to import `provenance.R` (`dirname(self)` | `root` above) being `/<path>/rscripts/`.

However, if imported within `test_collate_tpms_functions.R`, then  `getopt::get_Rscript_filename()` within `collate_tpms_functions.R` returns `/<path>/rscripts/tests/testthat/test_collate_tpms_functions.R` with the path used to import `provenance.R` (`dirname(self)` | `root` above) being `/<path>/rscripts/tests/testthat`, so the import fails.

The issue is that R's support for importing functions in other files is sorely lacking compared to Python. I'd agree with the developer on https://stackoverflow.com/questions/47044068/get-the-path-of-current-script who remarked that "having to use source(). compared to python import it's tragically bad, because you have to use very bad tricks to ensure a proper reliable import." The complexity and variety of workarounds on that question would seem to support their view!

I think it'd be preferable, and more elegant, to move towards bundling the R files that have R functions only as a a package so they could be imported via `library(riboviz)`.

**Comment by mikej888** [comment]
With the help of https://kbroman.org/pkg_primer/pages/minimal.html and https://kbroman.org/pkg_primer/pages/build.html, we can bundle up and install our R functions as a package without going down the fully-fledged R package route as follows, for example:

Create folder with desired contents:
```
rpackage/
  R/
    collate_tpms_functions.R # Removed if-block that imports provenance.R
    provenance.R
  DESCRIPTION
```
where `DESCRIPTION` is:
```
Package: riboviz
Version: 2.1
```
Build and install:
```console
$ cd rpackage
$ R CMD build .
* checking for file 'rpackage/DESCRIPTION' ... OK
* preparing 'riboviz':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* creating default NAMESPACE file
* building 'riboviz_2.1.tar.gz'
$ R CMD INSTALL riboviz_2.1.tar.gz 
* installing to library '/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.6'
* installing *source* package ‘riboviz' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  'riboviz'
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (riboviz)
```
In another window:
```console
$ Rscript rscripts/list-r-packages.R | grep riboviz
              riboviz      2.1
$ R
```
```R
> library(riboviz)
> packageVersion("riboviz")
[1] '2.1'
> LoadTpms
...
<bytecode: 0x56106f61d778>
<environment: namespace:riboviz>
> write_provenance_header
...
<bytecode: 0x56106f649708>
<environment: namespace:riboviz>
```
Alternative approach using `devtools` in R, first removing existing package:
```R
> remove.packages(riboviz)
> build(".")
[1] "/home/ubuntu/riboviz/riboviz_2.1.tar.gz"
> install(".")
...
* DONE (riboviz)
```
In a fresh R session, try to use a function:
```R
> CollateTpms("collated_tpms.tsv", NA, c(WTnone="WTnone_tpms.tsv", WT3AT="WT3AT_tpms.tsv"))
Error in get_Rscript_filename() : 
  could not find function "get_Rscript_filename"
```
Try via `source`:
```R
> source("rscripts/provenance.R")
> source("rscripts/collate_tpms_functions.R")
> CollateTpms("collated_tpms.tsv", NA, c(WTnone="WTnone_tpms.tsv", WT3AT="WT3AT_tpms.tsv"))
```
OK, need to specify dependencies. Edit `DESCRIPTION`:
```
Package: riboviz
Version: 2.1
Imports:
 dplyr,
 here,
 purrr,
 readr,
 tibble,
 tidyr,
 Biostrings,
 getopt,
 git2r
```
Rebuild and reinstall and retry:
```R
> library(riboviz)
> CollateTpms("collated_tpms.tsv", NA, c(WTnone="WTnone_tpms.tsv", WT3AT="WT3AT_tpms.tsv"))
[1] "Loading ORFs from: WTnone_tpms.tsv"
...
[1] "Loading TPMs from: WTnone_tpms.tsv"
...
[1] "Loading TPMs from: WT3AT_tpms.tsv"
...
```
```console
$ head collated_tpms.tsv 
# Created by: RiboViz
# Date: 2021-04-27 03:23:56
# File: NA
# Version: unknown
ORF	WTnone	WT3AT
YAL001C	116.7	953
YAL002W	212.8	365.8
YAL003W	199013.8	100458.6
```
OK

Note that file and version are unknown. `provenance.R` functions need to be updated to get this information some other way e.g. use `packageVersion("riboviz")` instead of the Git hash. Arguably only point versions, not Git commit versions, should be used for published results anyway.

To use this we'd need to create a new directory with R files that hold functions only (i.e. no command-line code) and users would then need to install these. Such R files, and the command-line R files that use them would no longer need to be worried about where their dependent R files live on the file system. This would resolve this issue and take us down the path towards bundling all our R code in an R package hosted in a separate repository (#52).

**Comment by mikej888** [comment]
@FlicAnderson, @ewallace, @acope3 comments on the foregoing welcome. I think it'd be useful to discuss this at an upcoming developer's meeting.

**Comment by mikej888** [comment]
Relates to #165 and #292.

**Comment by ewallace** [comment]
In my opinion this would be solved properly by creating an R package, issue #322. So it is not worth spending any time creating temporary solutions instead, unless a bug appears.

**Comment by mikej888** [comment]
Once we have a package, review #352, and try the workflow without a `.git` repository present to ensure that no problems in importing R scripts arise.

**Comment by FlicAnderson** [comment]
Linking this to #322 as it's closely linked & Mike's comments include relevant info.

**Comment by FlicAnderson** [comment]
Closing as #322 would resolve these issues.
