### ISSUE TITLE
Remove now-deprecated `stop_in_cds` parameter

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#319]
Remove all occurrences of `stop_in_cds` from:

* `docs/user/prep-riboviz-config.md`
* `docs/reference/hdf5-data.md`
* `prep_riboviz.nf`
* `riboviz/workflow.py`.
* Remove `STOP_IN_CDS` from `riboviz.params` and hard-code `stop_in_cds` into `riboviz.upgrade_config`'s `UNUSED` list.

Spawned from Refactor bam_to_h5.R #61. To be done at a future post-R2.1 release.

**Comment by mikej888** [comment]
`riboviz.params` has already been updated prior to 2.1. Similarly, `riboviz.upgrade_config` renames `stop_in_cds` to `stop_in_feature`.

**Comment by mikej888** [comment]
Implemented, see PR #406.

**Comment by FlicAnderson** [comment]
This is something we'll need to change in the example-datasets yamls, so I'm tagging [example-datasets/#92](https://github.com/riboviz/example-datasets/issues/92) to remind me to check this in the outstanding branches & main repo.
