### ISSUE TITLE
Potential issue with different newline characters between systems

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#321]
@3mma-mack and I realized her FASTA and GFF3 files were using the `\r\n`newline characters, which seemed to be throwing off `check_fasta_gff.py`. We probably want to make sure `check_fasta_gff.py` is robust to different newline characters.

**Comment by mikej888** [comment]
`check_fasta_gff` uses FASTA and GFF files in three places.

1) In `get_fasta_sequence_ids` using:
```
   with open(fasta, "r") as f:
```
2) In `get_issues` using:
```
    fasta_genes = Fasta(fasta)
```
3) In `get_issues` using:
```
gffutils.create_db(gff, ...)
```
In 2) and 3) we are relying on these third-party packages to open the files and the function signatures don't seem to support any parameters stating how newlines are to be handled.

An alternative, and perhaps preferable, solution would be to ensure that the code that *saves* the problematic FASTA and GFF files does not add `\r\n` if running on Windows.

**Comment by mikej888** [comment]
Spawned from #278. As RiboViz is primarily for use in Linux environments, if there is no readily available solution code-wise, we could recommend users run `dos2unix` on such files (see https://github.com/riboviz/riboviz/issues/278#issuecomment-844290421).

**Comment by acope3** [comment]
It doesn't appear we have control over the newline character with the functions used to create the CDS and GFF files. As part of `check_fasta_gff.py`, we could load the files into memory, check for the `\r\n` character, and replace all of these with `\n`. IMO, this isn't a desirable solution. Honestly, I'm kinda surprised this is an issue. It would think this would only be problematic if going between systems. @3mma-mack remind me: were you creating the CDS and GFF files locally on Windows and then checking them on Eddie? If so, this seems like this is an edge case. I expect most users would be running things on the same system.

**Comment by 3mma-mack** [comment]
Sorry for the delay! Yes I was creating the files on my Windows laptop then sending to Eddie, which is probably why it is an issue

**Comment by mikej888** [comment]
@acope3 I'd agree with this being an edge case. It's recommended that users use a Linux flavour. Did you try running `dos2unix` on @3mma-mack's files and then running `check_fasta_gff.py` on those (that's how I'd usually resolve DOS vs. Linux file ending issues)?

**Comment by acope3** [comment]
I ran `dos2unix` on @3mma-mack's files. This resolved the issue.

**Comment by acope3** [comment]
As `dos2unix` resolves the issue and @mikej and I both agree this is an edge case, I'm going to close this issue ticket.
