### ISSUE TITLE
bam_to_h5.R fails on Eddie when run inside screen

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#323]
For me as of May 2021, this works:
```
source set-riboviz-env.sh
cd riboviz/riboviz
nextflow prep_riboviz.nf -params-file vignette/vignette_config.yaml 
```

This doesn't:
```
source set-riboviz-env.sh
cd riboviz/riboviz
screen
source activate riboviz
nextflow prep_riboviz.nf -params-file vignette/vignette_config.yaml 
```

The pipeline fails at `bam_to_h5.R` with the error message:
```
/exports/igmm/software/pkg/el7/apps/R/3.6.3/lib64/R/bin/exec/R: error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
```
so it is something to do with finding R libraries from inside screen.

Is it worth adding a line to `docs/user/run-on-eddie.md` saying "don't try to run riboviz inside `screen`"? Or not?

**Comment by canuse** [comment]
I think this is a similar problem to https://stackoverflow.com/questions/50591901/screen-inside-the-conda-environment-doesnt-work/53535739
We need to start a screen session before load anaconda and riboviz environment, and this works:
```
screen
source set-riboviz-env.sh
cd riboviz/riboviz
source activate riboviz     # if you didn't activate riboviz in set-riboviz-env.sh
nextflow prep_riboviz.nf -params-file vignette/vignette_config.yaml 
```

**Comment by ewallace** [comment]
It looks like this is a documentation issue that could be added somewhere.

@mikej888 @FlicAnderson do you think we need to add to our documentation, or just close without fixing?

**Comment by mikej888** [comment]
Commit 5b5c714 has a Troubleshooting section added to the end of [docs/user/run-on-eddie.md](https://github.com/riboviz/riboviz/blob/develop/docs/user/run-on-eddie.md) with @ewallace issue and @canuse workaround.

**Comment by kavousan** [comment]
@mikej888: can we close this, is it done?

**Comment by mikej888** [comment]
@kavousan I think so as we've documented the issue and a workaround.
