### ISSUE TITLE
Refactor collate_tpms.R

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#33]
* Conform to R styles.
* Comment.
* Provide testthat tests.

**Comment by FlicAnderson** [comment]
This might be worth checking back in on after #61 has been completed?

**Comment by mikej888** [comment]
Branch [collate-tpms-33](https://github.com/riboviz/riboviz/tree/collate-tpms-33)

**Comment by mikej888** [comment]
Commit 547fb43 on branch [collate-tpms-33](https://github.com/riboviz/riboviz/tree/collate-tpms-33):

* Added sample data from vignette to `data/tpms`.
* Added `rscripts/tests/testthat/test_collate_tpms.R`:
  - Test with sample-specific TPMs files colocated in same directory (`<output_dir>/<sample>_tpms.tsv` (Nextflow workflow-style invocation).
  - Test with sample-specific TPMs files in sample-specific sub-directories (`<output_dir>/<sample>/tpms.tsv` (Python workflow-style invocation).
* Commented and renamed variables in `collate_tpms.R`.

TODO

* Make `--tpms-file` NOT relative to output directory but an absolute path.
* Rename `--output-dir` to `samples-dir`.
* Consider providinf `<sample> <file>` pairs at command-line to remove need for `--sample-subdirs`. https://stackoverflow.com/questions/41205587/r-how-to-partition-a-list-or-vector-into-pairs-at-an-offset-of-1 may help here.
* Expand testthat tests:
  - Default vs. explicit `--tpms-file`.
  - Validate collated content based on inputs. Include 1 column case.
  - Non-existent sample file.
  - Inconsistent ORFs between sample files.
* Get ORF file used in vignette and provide as command-line parameter to see what happens. Add test.

**Comment by mikej888** [comment]
Commit d491e2b branch [collate-tpms-33](https://github.com/riboviz/riboviz/tree/collate-tpms-33):

* Tests now create sample-specific TPMs files and expected collated TPMs results in-code.
* Test for 1 sample, 2 samples, no ORFs.
* Fixed bug with how ORF lists are compared.

**Comment by mikej888** [comment]
Checked what happens if a FASTA file is provided via the `--orf_fasta` command-line parameter:

```console
$ cp vignette/output/WTnone/tpms.tsv WTnone_tpms.tsv
$ cp vignette/output/WT3AT/tpms.tsv WT3AT_tpms.tsv
Rscript --vanilla rscripts/collate_tpms.R --sample-subdirs=FALSE --output-dir=.  WTnone WT3AT --tpms-file collated_tpms.tsv
Rscript --vanilla rscripts/collate_tpms.R --sample-subdirs=FALSE --output-dir=.  WTnone WT3AT  --tpms-file orf_collated_tpms.tsv --orf-fasta vignette/input/yeast_YAL_CDS_w_250utrs.fa
head WTnone_tpms.tsv collated_tpms.tsv orf_collated_tpms.tsv
```
View first few lines of sample file and collated files:
```console
$ head WTnone_tpms.tsv collated_tpms.tsv orf_collated_tpms.tsv
==> WTnone_tpms.tsv <==
...
ORF	readcount	rpb	tpm
YAL001C	4	0.00113314447592068	116.685976611765
YAL002W	8	0.00206611570247934	212.759037933641
YAL003W	1291	1.93263473053892	199013.784878156
YAL005C	4797	2.42763157894737	249986.270649977
YAL007C	42	0.060431654676259	6222.9722634749

==> collated_tpms.tsv <==
...
ORF	WTnone	WT3AT
YAL001C	116.7	953
YAL002W	212.8	365.8
YAL003W	199013.8	100458.6
YAL005C	249986.3	239069
YAL007C	6223	3821.5

==> orf_collated_tpms.tsv <==
...
ORF	WTnone	WT3AT
YAL068C	116.7	953
YAL067W-A	212.8	365.8
YAL067C	199013.8	100458.6
YAL065C	249986.3	239069
YAL064W-B	6223	3821.5
```
Note how ORF names are out of synch with TPMs values for samples in the final file, where ORF names are taken from the file provided via the orf_fasta argument. This is because the ORFs in `vignette/input/yeast_YAL_CDS_w_250utrs.fa` are in a different order from the sample files:

```
>YAL068C
...
>YAL067W-A
...
>YAL067C
...
```
Need to check to see if upstream components output ORFs in TPMs TSV files in a sorted order. If so, then sort ORFs read from FASTA file likewise. Else, sort ORFs from both TPMs TSV files and FASTA file. This may cause regression tests to fail, if run against existing regression test data, if sorted order differs.

**Comment by mikej888** [comment]
Up to commit 5819fda branch [collate-tpms-33](https://github.com/riboviz/riboviz/tree/collate-tpms-33):

* ORFs are sorted upon loading from a FASTA file or a sample-specific TPMs TSV file. TPMs from sample-specific TPMs files are sorted by ORF also. This ensures that collation can occur regardless of the order of TPMs in individual TPMs files or in FASTA files. Added test to `test_collate_tpms.R` using sample-specific TPMs TSV files with different ORF ordering.
* Added test for `--orf-fasta` where ORFs are taken from FASTA file.
* Added test for collated TPMs only for existing sample files if one sample file does not exist.
* Added test for list of ORFs only in collated samples file if all sample file are missing and `--orf-fasta` is provided.

**Comment by mikej888** [comment]
Up to commit cb83b23 branch [collate-tpms-33](https://github.com/riboviz/riboviz/tree/collate-tpms-33):

* `<sample_name> <file_name>` pairs are expected at the command-line. This removes the need for `--output-dir` and `--samples-subdir` command-line parameters and simplifies the code as directory or file names no longer need to be parsed to infer sample names.
* Extracted all non-command-line-related code from `collate_tpms.R` to `collate_tpms_functions.R`.

**Comment by mikej888** [comment]
As of commit 375cec7:

* Added `ignore_row_order` (default `False`) to `riboviz.utils.equal_tsv` and `equal_dataframes`.
* Updated `riboviz.test.regression.test_collate_tpms_tsv` to call `utils.equal_tsv` with `ignore_row_order=True`
* Added `sort_orfs` and `digits` command-line parameters to `collate_tpms.R`. Set `sort_orfs` to `FALSE` by default in `collate_tpms.R` and `collate_tpms_functions.R`.
* Extended `test_collate_tpms.R`:
  - `--orf-fasta` test replaced by `--orf-fasta (sort_orfs=TRUE)` and `--orf-fasta (sort_orfs=FALSE)` tests.
  - `Sample files with ORFs in different orders` replaced by `sort_orfs=TRUE` and `sort_orfs=FALSE` tests.
  - Added `digits=0` test.

**Comment by mikej888** [comment]
Pull request #309 merged.
