### ISSUE TITLE
generate_stats_figs.R has test that dependency

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#334]
`generate_stats_figs.R` has `testthat` dependency but `docs/user/install.md` does not record this dependency which means the workflow fails when it runs.

Either remove the `testthat` dependency from `generate_stats_figs.R` (preferred) or update the documentation etc. to add the dependency.
```
suppressMessages(library(testthat))
```
New instructions on how to add/update dependencies is at https://github.com/riboviz/riboviz/blob/docs-326-327/docs/developer/dependencies.md (pending merge as part of PR #328).

**Comment by ewallace** [comment]
I think the dependency should be removed. `testthat` should be used for testing, not inside our pipeline. Testing can be shoved off into the R package when we make that, issue #322.

**Comment by mikej888** [comment]
The `suppressMessages(library(testthat))` can be removed as no `testthat` functions are used elsewhere in `generate_stats_figs.R`.
