### ISSUE TITLE
Static HTML and multiplexed data

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#343]
I decided to test the new static HTML output using the Gupta et. al. multiplexed data. It worked for a few of the samples, but did not complete for others. I'm attaching the log file. The error is `pandoc: AnalysisOutputs.utf8.md: openFile: does not exist (No such file or directory)`. @FlicAnderson any clue what is going on?

[command.txt](https://github.com/riboviz/riboviz/files/6577323/command.txt)

**Comment by acope3** [comment]
@ewallace believe there is an error in one of the chunks of R code in the R markdown file. I will take a look.

**Comment by acope3** [comment]
I reran this recently and I'm no longer accounting this issue. From what I can tell, this bug was addressed by @mikej888 as part of closed issue #372. I think we can close this ticket.

**Comment by mikej888** [comment]
@acope3 The error `pandoc: AnalysisOutputs.utf8.md: openFile: does not exist (No such file or directory)` in your `command.txt` was exactly the one I also encountered, and fixed, in #372.
