### ISSUE TITLE
Release RiboViz 2.1

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#345]
Release preparation tickets (labelled [R2.1](https://github.com/riboviz/RiboViz/labels/R2.1)):

* [all](https://github.com/riboviz/RiboViz/issues?utf8=%E2%9C%93&q=label%3AR2.1)
* [closed](https://github.com/riboviz/RiboViz/issues?q=label%3AR2.1+is%3Aclosed)
* [open](https://github.com/riboviz/RiboViz/labels/R2.1)

Release preparation:
 
- [x] See [docs/developer/releasing.md](https://github.com/riboviz/riboviz/blob/develop/docs/developer/releasing.md).
- [x] Create new integration test dataset for 2.1 #332
- [x] Deposit RiboViz 2.1 to Figshare.

Related releases, to be done after this release:

* Update example-datasets for release 2.1 riboviz/example-datasets#76
* Update containers for release 2.1 riboviz/containers#1

**Comment by ewallace** [comment]
We should also upgrade containers to R2.1 when the release is out, new issue ticket [containers#107](https://github.com/riboviz/containers/issues/1).
