### ISSUE TITLE
Fix broken links for 'Example `umi_regexp`' in docs/user/install.md

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#349]
There are three links:

> [Favate et al 2020 E. coli example dataset](https://github.com/riboviz/example-datasets/blob/master/bacteria/ecoli/Favate_2020_unpublished.yaml) 
> [Gupta et al 2018 saccharomyces example dataset](https://github.com/riboviz/example-datasets/blob/master/fungi/saccharomyces/Gupta_2018_tRNA_Modification_Carbon_Nitrogen_Metabolism_RPF_9-samples_CDS_w_250utrs_config.yaml).
> [Weinberg et al 2016 Saccharomyces example dataset](https://github.com/riboviz/example-datasets/blob/weinberg_2016_dataset-20/fungi/saccharomyces/Weinberg_2016_RPF_3_samples_CDS_w_250utrs_config.yaml).

The Favate and Weinberg links are broken. Also for Weinberg I'd recommend a link to the `master` branch not any other branch otherwise the link may easily break again in future.

**Comment by ewallace** [comment]
Requesting @FlicAnderson address this.

**Comment by FlicAnderson** [comment]
@mikej888 are you sure these links are in `docs/user/install.md`?  I'm not quite sure where to fix this?

**Comment by FlicAnderson** [comment]
> @mikej888 are you sure these links are in `docs/user/install.md`? I'm not quite sure where to fix this?

Nevermind, I think I found where you meant - prep-riboviz-config.md

**Comment by FlicAnderson** [comment]
Fixed the links and created linked PR from fix branch `fix-links-349`, which is now PR #364.

**Comment by mikej888** [comment]
> > @mikej888 are you sure these links are in `docs/user/install.md`? I'm not quite sure where to fix this?
> 
> Nevermind, I think I found where you meant - prep-riboviz-config.md

Sorry yes that was it.
