### ISSUE TITLE
Rename riboviz master branch to main

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#351]
https://github.com/github/renaming#renaming-existing-branches

**Comment by mikej888** [comment]
1. Any absolute URLs in documentation from "riboviz" to itself, or to `master` in the "example-datasets" or "bbsrc-nsf" repository need to be updated. A `grep` for `/master` can find these.
2. Team members then need to EITHER take a fresh clone of the repository OR do a `git fetch` and start to use the `main` branch (I haven't tried the latter but `main` should appear as a new branch).

**Comment by ewallace** [comment]
I am happy to rename our master branch to main.

**Comment by FlicAnderson** [comment]
I'm also happy with this renaming @mikej888, is this something you're planning to do soon?  Or is this something we will discuss further at the dev meeting?

**Comment by mikej888** [comment]
I was planning to do it at the time of the release.

**Comment by mikej888** [comment]
To rename:

* Go to your repository page on GitHub.
* Click Settings.
* Click Branches.
* In Default branches table, click pen icon to right of `master`.
* Enter `main`.
* Click Rename branch.

To update any local clone you have, run:

git branch -m master main
git fetch origin
git branch -u origin/main main

**Comment by mikej888** [comment]
Documentation updates done in branch [rename-master-main-351](https://github.com/riboviz/riboviz/tree/rename-master-main-351).

**Comment by mikej888** [comment]
Merged PR #365.
