### ISSUE TITLE
Create fastq examples for UMIs and barcode

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#36]
Write a script to create well-behaved fastq files to test RiboViz performance on UMIs and barcodes, `create_fastq_example.py`.

New-style ribosome profiling libraries have inline UMIs and/or barcodes as in [McGlincy and Ingolia 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5582988/). We need to incorporate barcode splitting and UMIs at both ends of reads in RiboViz to deal with this. To do this effectively we need to write a script that generates small fastq files with exaclty known entries with appropriate UMIs, barcodes, reads, and adapters.

Afterwards, we can write tests that rely on the created fastqs.

**Comment by ewallace** [comment]
Created branch simulatefastq-36 with draft version of this script, pyscripts/simulate_fastq_tests.py

**Comment by mikej888** [comment]
Merged simulatefastq-36 into develop, see #82.
