### ISSUE TITLE
Ribosome Density vs tRNA plotting functions has hard-coded values

### ISSUE THREAD

**Issue by acope3** [riboviz/riboviz#363]
The current implementation of `GatherCodonSpecificRibosomeDensityTRNACorrelation` has some hard-coded values that will break anytime the input tRNA file doesn't have the same number of columns as the example we use for yeast. I think we can modify this version of the function 

```
GatherCodonSpecificRibosomeDensityTRNACorrelation <- function(cod_dens_tRNA_data) {
  # Prepare data for plot
  cod_dens_tRNA_wide <- cod_dens_tRNA_data %>%
    gather(tRNA_type, tRNA_value, 3:6) %>%
    gather(Site, Ribodens, 3:5)
  return(cod_dens_tRNA_wide)
} 
```

to look like this

```
GatherCodonSpecificRibosomeDensityTRNACorrelation <- function(cod_dens_tRNA_data) {
  # Prepare data for plot
  cod_dens_tRNA_long <- cod_dens_tRNA_data %>% 
                            pivot_longer(!c(AA,Codon,A,P,E),names_to="tRNA_type",values_to="tRNA_value") %>% 
                            pivot_longer(c(A,P,E),names_to="Site",values_to="Ribodens")
  return(cod_dens_tRNA_long)
} 
```

**Comment by acope3** [comment]
This is addressed in branch ` trna_plot-363`.

**Comment by FlicAnderson** [comment]
+1 to tidyverse update :) this sounds like a really good catch.

**Comment by FlicAnderson** [comment]
@acope3 can you give me a ping on here when you've created the PR & added the results of running all the tests so I know if it's likely to be in or out of Release 2.1?  

This is the latest [developer testing.md documentation](https://github.com/riboviz/riboviz/blob/develop/docs/developer/testing.md)

Once you've got that done (if it's passing things), I can run the same tests & then if it's all looking good we can merge the PR & then I'll use `develop` to run my full-size testing (riboviz/#355).

**Comment by acope3** [comment]
@FlicAnderson see #368.
