### ISSUE TITLE
change upgrade config script default organism-specific behaviour to null

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#369]
When running current upgrade tool (from riboviz `develop` branch, last commit b0ded02030) on config files for organisms other than Saccharomyces cerevisiae, the default behaviour creates problems by inserting S.cerevisiae yeast-specific file entries to the following: 

* `codon_positions_file` 
* `features_file` 
* `t_rna_file`

If these parameters are not present in the config to be upgraded, the default value inserted should probably be 'null' to avoid yeast-specific files being added in and missed during configuation of non-yeast datasets (which I almost did!)

The configs I was testing did have pre-existing values for `asite_disp_length_file`, so these weren't replaced, but this parameter should also default to null as this is also organism-specific. 

@mikej888 I can't remember if this organism-specific default behaviour was addressed previously, and has crept back in as a bug, or is just something I hadn't noticed in testing yet?

In terms of priority, this would be a good one to fix after release 2.1 happens, ahead of work on upgrading example-datasets.  I'm therefore tagging as '2.1' but this is not considered a block to riboviz 2.1 release, and this is a 2.1-follow-on task really.

**Comment by mikej888** [comment]
@flic the upgrade tool has always added `codon_positions_file`, `features_file`, `t_rna_file`, `asite_disp_length_file` with the default values. The assumption was that a user would need to then inspect the configuration to see it's fit for their purpose. Adopting `null` wouldn't change that but it would have the benefit you mention. It's a quick change and won't affect the workflow testing so I'll do it now.

**Comment by mikej888** [comment]
@FlicAnderson The fix is now in `develop`.
