### ISSUE TITLE
Customise UMI-Tools to support simultaneous 5' and 3' UMI extraction

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#37]
**UMI-tools**

Tom Smith, Andreas Heger and Ian Sudbery. UMI-tools: modeling sequencing errors in Unique Molecular Identifiers to improve quantification accuracy, Genome Res. 2017. 27: 491-499, January 18, 2017, doi: 10.1101/gr.209601.116, https://genome.cshlp.org/content/27/3/491.full

https://github.com/CGATOxford/UMI-tools

* MIT licence
* Mar 2015 - Jun 2019, 30 releases
* Python, conda

Customise [UMI-Tools](https://github.com/CGATOxford/UMI-tools) to support simultaneous 5' and 3' UMI extraction:

* Update [extract_methods.py](https://github.com/CGATOxford/UMI-tools/blob/master/umi_tools/extract_methods.py) to take a new `umi_name` parameter which provides a prefix for the UMI extracted when inserted into the sequence header. If this parameter is provided and is not `None` then add a new header element of form `<umi_name>:<UMI>`. If it is `None` then retain existing functionality. There must be no space before or after the colon in the header, nor any space within `<umi_name>`.
* Update `umi_tools dedup` to accept a `<umi_name>` parameter.
* Write sample tests.
* Submit pull request.

Functionality will be added in such a way so as not to break current functionality or behaviour of UMI-Tools.

Adding this functionality contributes to using UMI-Tools within the RiboViz workflow to do deduplication.

**Comment by ewallace** [comment]
We will also need to add the `umi-name` parameter to the dedup function and check that still works.

Also we will need the header addition to be `<umi_name>:UMI` with **no space** after the colon.

**Comment by ewallace** [comment]
I checked with @IanSudbery and apparently this features is already there.

> Its been in for ages. Just specify it using a regex. Something like '--bc-pattern="^(?P<umi_1>.{6}).+(?P<umi_2>.{6})$"  --extract-method=regex' to specify the first and last 6nt of the read. see the docs at https://umi-tools.readthedocs.io/en/latest/regex.html#regex-regular-expression-mode

We do need to submit a pull request for the **documentation** which does not make this clear.

**Comment by FlicAnderson** [comment]
Great that it's already a feature, and as you say making docs clearer never goes amiss. Happy to take on the figure creation!

**Comment by ewallace** [comment]
Also [umi-tools dedup](https://umi-tools.readthedocs.io/en/latest/reference/dedup.html) has argument ` --umi-separator=<sep>`.

**Comment by mikej888** [comment]
Looking at `umi_tools extract`:

UMI-tools can handle both gzipped and uncompressed FASTQ files. Use unzipped FASTQ files so can see differences:

```console
$ cp ~/RiboViz/vignette/input/S*gz .
$ gunzip SRR1042864_s1mi.fastq.gz 
```

Python 2:

```console
$ source miniconda2/bin/activate
$ conda install -c bioconda umi_tools
$ umi_tools extract -p NNNNNNNN -I SRR1042864_s1mi.fastq -S processed.fastq
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/bin/umi_tools", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/umi_tools/umi_tools.py", line 58, in main
    module = importlib.import_module("umi_tools." + command, "umi_tools")
  File "/home/ubuntu/miniconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/umi_tools/extract.py", line 158, in <module>
    import umi_tools.extract_methods as extract_methods
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/umi_tools/extract_methods.py", line 7, in <module>
    import umi_tools.Utilities as U
ImportError: No module named Utilities
```

[umi_tools whitelist --help: ImportError: No module named Utilities #321](https://github.com/CGATOxford/UMI-tools/issues/321) comments that:

> As of this new version, 1.0.0 we no longer support python 2.7. Try creating a new python 3 conda environment and installing UMI-Tools with:

Also

> Alternatively, if you really need to install UMI-Tools in a python 2 enviornment, please install version 0.5.5 with conda install umi_tools==0.5.5 or pip install umi_tools==0.5.5

```console
$ conda uninstall umi_tools
$ conda install -c bioconda umi_tools==0.5.5
$ umi_tools -v
UMI-tools version: 0.5.5
```

Python 3:

```console
$ source miniconda3/bin/activate
$ conda install -c bioconda umi_tools
$ umi_tools -v
UMI-tools version: 1.0.0
```

8 nt UMI at (default) 5' end:

```console
$ umi_tools extract -p NNNNNNNN -I SRR1042864_s1mi.fastq -S processed.fastq
```

`N` is random part of barcode, use `X` for fixed part.

```console
$ head SRR1042864_s1mi.fastq processed.fastq
==> SRR1042864_s1mi.fastq <==
@SRR1042864.78 HWI-ST279:248:BC0N3DACXX:1:1101:3039:2225 length=51
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG
+
@@@FDDFDHHHBDCFHHAEFFGHGG?@FDGHGCG9FHGEGII>GGGIFFHF
@SRR1042864.114 HWI-ST279:248:BC0N3DACXX:1:1101:3830:2209 length=51
AATACTGCCAGCTGGGACTGAGGACTGCGACGCTGTAGGCACCATCAATAG
+
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJIJJJIIIIJIJJJJJJJJJJJJ
@SRR1042864.153 HWI-ST279:248:BC0N3DACXX:1:1101:4858:2190 length=51
TTGAGCGTCATTCTGTAGGCACCATCAATAGATCGGAAGAGCACACGTCTG

==> processed.fastq <==
@SRR1042864.78_AGATGGAT HWI-ST279:248:BC0N3DACXX:1:1101:3039:2225 length=51
ACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG
+
HHHBDCFHHAEFFGHGG?@FDGHGCG9FHGEGII>GGGIFFHF
@SRR1042864.114_AATACTGC HWI-ST279:248:BC0N3DACXX:1:1101:3830:2209 length=51
CAGCTGGGACTGAGGACTGCGACGCTGTAGGCACCATCAATAG
+
HHHHHJJJJJJJJJJJJJJJJIJJJIIIIJIJJJJJJJJJJJJ
@SRR1042864.153_TTGAGCGT HWI-ST279:248:BC0N3DACXX:1:1101:4858:2190 length=51
CATTCTGTAGGCACCATCAATAGATCGGAAGAGCACACGTCTG
```

Look at first sequence:

```
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG # Input sequence
AGATGGAT                                            # UMI in header
        ACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG # Output sequence
```

5 nt UMI at 3' end:

```console
$ umi_tools extract --3prime -p NNNNN -I SRR1042864_s1mi.fastq -S processed.fastq
$ head processed.fastq
@SRR1042864.78_AAGAG HWI-ST279:248:BC0N3DACXX:1:1101:3039:2225 length=51
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGG
+
@@@FDDFDHHHBDCFHHAEFFGHGG?@FDGHGCG9FHGEGII>GGG
@SRR1042864.114_AATAG HWI-ST279:248:BC0N3DACXX:1:1101:3830:2209 length=51
AATACTGCCAGCTGGGACTGAGGACTGCGACGCTGTAGGCACCATC
+
CCCFFFFFHHHHHJJJJJJJJJJJJJJJJIJJJIIIIJIJJJJJJJ
@SRR1042864.153_GTCTG HWI-ST279:248:BC0N3DACXX:1:1101:4858:2190 length=51
TTGAGCGTCATTCTGTAGGCACCATCAATAGATCGGAAGAGCACAC
```

Look at first sequence:

```
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG # Input sequence
                                              AAGAG # UMI in header
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGG      # Output sequence
```

2 nt UMI at 5' end and 5 nt UMI at 3' end, using a regexp:

```console
$ umi_tools extract --bc-pattern="^(?P<umi_1>.{2}).+(?P<umi_2>.{5})$" \
    --extract-method=regex \
    -I SRR1042864_s1mi.fastq -S processed.fastq
$ head SRR1042864_s1mi.fastq processed.fastq
@SRR1042864.78_AGAAGAG HWI-ST279:248:BC0N3DACXX:1:1101:3039:2225 length=51
ATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGG
+
@FDDFDHHHBDCFHHAEFFGHGG?@FDGHGCG9FHGEGII>GGG
@SRR1042864.114_AAAATAG HWI-ST279:248:BC0N3DACXX:1:1101:3830:2209 length=51
TACTGCCAGCTGGGACTGAGGACTGCGACGCTGTAGGCACCATC
+
CFFFFFHHHHHJJJJJJJJJJJJJJJJIJJJIIIIJIJJJJJJJ
@SRR1042864.153_TTGTCTG HWI-ST279:248:BC0N3DACXX:1:1101:4858:2190 length=51
GAGCGTCATTCTGTAGGCACCATCAATAGATCGGAAGAGCACAC
```

Look at first sequence:

```
AGATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGGAAGAG # Input sequence
AG                                            AAGAG # UMI in header
  ATGGATACGAATAAGGCGTCCTGTAGGCACCATCAATAGATCGG      # Output sequence
```

**Comment by mikej888** [comment]
See notes on Umi-tools, including use of regexps to detect both UMIs and barcodes and deduplication using UMIs and UMIs and barcodes: https://github.com/riboviz/bbsrc-nsf/blob/master/docs/general/UmiTools.md

**Comment by mikej888** [comment]
@ewallace `umi_tools extract` can be extended to add a header tag (`<umi_name>:<UMI>`) into the FASTQ files it outputs. However, I can't see how this information would be preserved when the FASTQ file is processed by Hisat2 such that it ends up in the resulting SAM files. I've tried with hand-tweaked FASTQ files but the only way it seems it is preserved is if it is appended to the sequence identifier as `umi_tools extract` currently does i.e. these would result in the SAM file retaining the information on the barcode and UMI:

```
@SRR1042864.36611_<BARCODE>_<UMI> HWI-ST279:248:BC0N3DACXX:1:1101:20614:6789 length=51
@SRR1042864.36611:<BARCODE>:<UMI> HWI-ST279:248:BC0N3DACXX:1:1101:20614:6789 length=51
@SRR1042864.36611:SOMETAG:<BARCODE>:<UMI> HWI-ST279:248:BC0N3DACXX:1:1101:20614:6789 length=51
```
but these attempts don't seem to:

```
@SRR1042864.36611 HWI-ST279:248:BC0N3DACXX:1:1101:20614:6789 UMI:<umi> length=51
@SRR1042864.36611 HWI-ST279:248:BC0N3DACXX:1:1101:20614:6789:UMI:<umi> length=51
```

[fastp]'s UMI handling - see [UMI example](https://github.com/OpenGene/fastp#umi-example) adopts a similar approach, commenting that:

> fastp will extract the UMIs, and append them to the first part of read names, so the UMIs will also be presented in SAM/BAM records.

For example, stripping an 8 nt UMI from:

```
@NS500713:64:HFKJJBGXY:1:11101:1675:1101 1:N:0:TATAGCCT+GACCCCCA
AAAAAAAAGCTACTTGGAGTACCAATAATAAAGTGAGCCCACCTTCCTGGTACCCAGACATTTCAGGAGGTCGGGAAA
```

gives:

```
@NS500713:64:HFKJJBGXY:1:11101:1675:1101:AAAAAAAA 1:N:0:TATAGCCT+GACCCCCA
GCTACTTGGAGTACCAATAATAAAGTGAGCCCACCTTCCTGGTACCCAGACATTTCAGGAGGTCGGGAAA
```

So, is just updating `umi_tools extract` to allow the use of other delimiters, not just `_`, sufficient?

Is there a need/desire for a post-processing tool that would traverse the resultant SAM file and strip the barcode and UMI from the identifier and add this information as tags instead? i.e. replace

```
SRR1042864.36611_<BARCODE>_<UMI> ... ... ...
```

with

```
SRR1042864.36611_<BARCODE>_<UMI> ... ... ... BC:<BARCODE> OX:<UMI>
```

**Comment by mikej888** [comment]
As UMI-Tools already supports simultaneous 5' and 3' UMI extraction, this issue can be closed.
