### ISSUE TITLE
Unable to initialize nextflow environment

### ISSUE THREAD

**Issue by Joseph-Waldron** [riboviz/riboviz#382]
When I install next flow with the following line

conda install -y -c bioconda nextflow=20

it looks like it installs without any issues, but then when I run 

nextflow -v

I get the following:

CAPSULE EXCEPTION: For input string: "" while processing attribute Allow-Snapshots: false (for stack trace, run with -Dcapsule.log=verbose)
USAGE: java <options> -jar miniconda2/envs/riboviz/share/nextflow/dist/20.10.0/nextflow-20.10.0-one.jar

Actions:
  capsule.version - Prints the capsule and application versions.
  capsule.modes - Prints all available capsule modes.
  capsule.jvms - Prints a list of all JVM installations found.
  capsule.help - Prints this help message.
  capsule.tree - Prints the capsule's dependency tree.
  capsule.resolve - Downloads all un-cached dependencies.

Options:
  capsule.mode=<value> - Picks the capsule mode to run.
  capsule.reset - Resets the capsule cache before launching. The capsule to be re-extracted (if applicable), and other possibly cached files will be recreated.
  capsule.log=<value> (default: quiet) - Picks a log level. Must be one of none, quiet, verbose, or debug.
  capsule.java.home=<value> - Sets the location of the Java home (JVM installation directory) to use; If 'current' forces the use of the JVM that launched the capsule.
  capsule.java.cmd=<value> - Sets the path to the Java executable to use.
  capsule.jvm.args=<value> - Sets additional JVM arguments to use when running the application.
  capsule.local=<value> - Sets the path of the local Maven repository to use.
Unable to initialize nextflow environment

**Comment by FlicAnderson** [comment]
Hi @Joseph-Waldron - I haven't experienced that error before.  @mikej888 do you have any ideas?

**Comment by mikej888** [comment]
@Joseph-Waldron Sorry, that error is new to me. What is your operating system and version?

**Comment by mikej888** [comment]
I Googled `"nextflow" "CAPSULE EXCEPTION: For input string"` and found https://gitter.im/nextflow-io/nextflow?at=56c3133a4dfe1fa71ffd1729, which is from 2016 but does have something which might provide more information. Try

```console
$ nextflow -v -Dcapsule.log=verbose
```

and if there are any chunks of output with `Exception` (upper or lower case) in them, please paste them in.

**Comment by mikej888** [comment]
I also found Nextflow won't start if a proxy URL env variable contains a trailing slash [109](https://github.com/nextflow-io/nextflow/issues/109). Please run

```console
$ echo $HTTP_PROXY
```

Don't paste in the output but do say whether not it has a trailing slash, `/`. Thanks.

**Comment by Joseph-Waldron** [comment]
Hi both, thanks for the help. Here is the output from running "nextflow -v -Dcapsule.log=verbose":
CAPSULE: Jar: /home/jwaldron/miniconda2/envs/riboviz/share/nextflow/dist/20.10.0/nextflow-20.10.0-one.jar
CAPSULE: Platform: linux
CAPSULE: Loading caplet: MavenCapsule
CAPSULE: Applying caplet MavenCapsule
CAPSULE: Initializing app ID
CAPSULE: Initialized app ID: nextflow_20.10.0
CAPSULE: Launching app nextflow_20.10.0
CAPSULE: Using JVM: /home/jwaldron/miniconda2/envs/riboviz
CAPSULE: WARNING resolve [] was empty
CAPSULE: WARNING resolve [] was empty
CAPSULE: Cache directory: /home/jwaldron/miniconda2/envs/riboviz/share/nextflow/capsule
CAPSULE: Adding `http` proxy: wwwcache.gla.ac.uk:8080 [from system environment]
CAPSULE: Adding `https` proxy: wwwcache.gla.ac.uk:8080 [from system environment]
CAPSULE: Cleanup
CAPSULE EXCEPTION: For input string: "" while processing attribute Allow-Snapshots: false
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:662)
	at java.lang.Integer.parseInt(Integer.java:770)
	at capsule.SystemProxySelector.addProxyFromEnv(SystemProxySelector.java:99)
	at capsule.SystemProxySelector.init(SystemProxySelector.java:71)
	at capsule.SystemProxySelector.<init>(SystemProxySelector.java:56)
	at capsule.SystemProxySelector.<init>(SystemProxySelector.java:48)
	at capsule.DependencyManager.newRepositorySession(DependencyManager.java:229)
	at capsule.DependencyManager.getSession(DependencyManager.java:207)
	at capsule.DependencyManager.setRepos(DependencyManager.java:145)
	at MavenCapsule.setDependencyRepositories(MavenCapsule.java:284)
	at MavenCapsule.initDependencyManager(MavenCapsule.java:264)
	at MavenCapsule.getDependencyManager(MavenCapsule.java:254)
	at MavenCapsule.resolve0(MavenCapsule.java:224)
	at Capsule.resolve(Capsule.java:3375)
	at Capsule.resolve(Capsule.java:3389)
	at Capsule.buildJavaProcess(Capsule.java:2228)
	at Capsule.buildProcess0(Capsule.java:1530)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.buildProcess(Capsule.java:1521)
	at Capsule.prelaunch0(Capsule.java:1494)
	at Capsule.prelaunch(Capsule.java:1487)
	at NextflowLoader.prelaunch(NextflowLoader.java:42)
	at Capsule.prepareForLaunch(Capsule.java:1339)
	at Capsule.launch(Capsule.java:1268)
	at Capsule.main0(Capsule.java:399)
	at Capsule.main(Capsule.java:379)
USAGE: java <options> -jar miniconda2/envs/riboviz/share/nextflow/dist/20.10.0/nextflow-20.10.0-one.jar

Actions:
  capsule.version - Prints the capsule and application versions.
  capsule.modes - Prints all available capsule modes.
  capsule.jvms - Prints a list of all JVM installations found.
  capsule.help - Prints this help message.
  capsule.tree - Prints the capsule's dependency tree.
  capsule.resolve - Downloads all un-cached dependencies.

Options:
  capsule.mode=<value> - Picks the capsule mode to run.
  capsule.reset - Resets the capsule cache before launching. The capsule to be re-extracted (if applicable), and other possibly cached files will be recreated.
  capsule.log=<value> (default: quiet) - Picks a log level. Must be one of none, quiet, verbose, or debug.
  capsule.java.home=<value> - Sets the location of the Java home (JVM installation directory) to use; If 'current' forces the use of the JVM that launched the capsule.
  capsule.java.cmd=<value> - Sets the path to the Java executable to use.
  capsule.jvm.args=<value> - Sets additional JVM arguments to use when running the application.
  capsule.local=<value> - Sets the path of the local Maven repository to use.
Unable to initialize nextflow environment

**Comment by Joseph-Waldron** [comment]
echo $HTTP_PROXY outputs a path with a trailing /

**Comment by mikej888** [comment]
Please can do 

```console
$ export HTTP_PROXY=<current value of HTTP_PROXY but without trailing />
```

and retry `nextflow -v`.

**Comment by Joseph-Waldron** [comment]
Thanks Mike

Just tried this as getting the same export though.

I'm not very familiar with proxys but should the output of echo $HTTP_PROXY start with http://http:// 
I was wondering whether having 2 x http:// was causing some parsing issues?

**Comment by mikej888** [comment]
I agree, that double `http://` looks strange. Try setting `HTTP_PROXY` using `export` to its current value but remove the first `http://` occurrence.

**Comment by Joseph-Waldron** [comment]
So that didn't work, but then I also changed the HTTPS_PROXY to remove the trailing / and prevailing https:// and it now works
Thanks very much

**Comment by Joseph-Waldron** [comment]
Do I need to change my bashrc file also?

**Comment by mikej888** [comment]
Glad that worked. If you want to have that change every time then yes. An alternative is to put it into your `set_riboviz_env.sh` script so it's only applied when you're wanting to run RiboViz.
