### ISSUE TITLE
GUI to generate yaml config file

### ISSUE THREAD

**Issue by amandamok** [riboviz/riboviz#389]
RShiny app / form to be more user-friendly to "typical biologist" users (addressing Reviewer 2 comment 3)

**Comment by amandamok** [comment]
App generates yaml file that looks to be correct by eye.

Need to test whether generated file is compatible with Nextflow.

Also, some extra parameters could use some further details as to how they're used:

- primary_id
- secondary_id
- rpf
- feature

Also, `run_static_html` is parameter in vignette config but not listed on https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md

**Comment by mikej888** [comment]
> Also, `run_static_html` is parameter in vignette config but not listed on https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-config.md

Added in commit 205add5.

**Comment by ewallace** [comment]
Work is in [yaml-gui-389/app.R](https://github.com/riboviz/riboviz/blob/yaml-gui-389/app.R)

**Comment by amandamok** [comment]
- [ ] make default values the same as vignette
- [ ] validate that generated yaml file is functional
- [ ] migrate to separate repository
- [ ] publish with shinyapps

**Comment by amandamok** [comment]
Validated generated yaml files on vignette example and UMI extraction, deduplication, multiplexing examples.

**Comment by amandamok** [comment]
Deployed with shinyapps at: https://riboviz.shinyapps.io/generate-yaml/

**Comment by amandamok** [comment]
Moved `app.R` to new repository [generate-yaml](https://github.com/riboviz/generate-yaml)

Now deployable in R environment with command:
`shiny::runGitHub("generate-yaml", "riboviz", ref="main")`

**Comment by kavousan** [comment]
> Deployed with shinyapps at: https://riboviz.shinyapps.io/generate-yaml/

Thank you Amanda, I really like the resolution to the URL discussion. Is it possible to have a holding page under https://riboviz.shinyapps.io/, also linking /generate-yaml/?

**Comment by amandamok** [comment]
I don't think shinyapps gives us the ability to control the [riboviz.shinyapps.io](https://riboviz.shinyapps.io) domain; but we can embed the app elsewhere:

https://docs.rstudio.com/shinyapps.io/applications.html#embedding-applications

**Comment by kavousan** [comment]
I did not mean to suggest that we move it from shinnyapps, it's fine as it is.
