### ISSUE TITLE
Problem running vignette

### ISSUE THREAD

**Issue by Joseph-Waldron** [riboviz/riboviz#394]
When I try to run the vignette it fails (output copied below).

It validated OK prior to this.

I believe I have everything installed OK (I will copy the output from the environment-tables.sh script in a separate comment below), but I already had hi-sat and bowtie installed previously using conda so I have not set the path to these as I believe conda would have already done this, so I am not sure if this is part of the problem

(riboviz) jwaldron@R11-JWAL-L-V:/mnt/data/JWALDRON/Scripts/riboviz$ nextflow run prep_riboviz.nf -params-file vignette/vignette_config.yaml -ansi-log false
N E X T F L O W  ~  version 20.10.0
Launching `prep_riboviz.nf` [agitated_rosalind] - revision: 6c6670470d
samples_dir: .
organisms_dir: .
data_dir: .
No such sample file (NotHere): example_missing_file.fastq.gz
[be/083804] Submitted process > cutAdapters (WTnone)
[c1/c85ee1] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[03/4c4c74] Submitted process > buildIndicesrRNA (yeast_rRNA)
[be/083804] NOTE: Process `cutAdapters (WTnone)` terminated with an error exit status (1) -- Error is ignored
[19/e4cb16] Submitted process > cutAdapters (WT3AT)
Error executing process > 'buildIndicesORF (YAL_CDS_w_250)'

Caused by:
  Process `buildIndicesORF (YAL_CDS_w_250)` terminated with an error exit status (1)

Command executed:

  hisat2-build --version
  hisat2-build yeast_YAL_CDS_w_250utrs.fa YAL_CDS_w_250

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  ln: failed to create symbolic link 'yeast_YAL_CDS_w_250utrs.fa': Operation not supported

Work dir:
  /mnt/data/JWALDRON/Scripts/riboviz/work/c1/c85ee144ca9af00653c622c5dbd599

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Finished visualising sample: null
Workflow finished! (failed)
WARN: Killing pending tasks (2)

**Comment by Joseph-Waldron** [comment]
(riboviz) jwaldron@R11-JWAL-L-V:/mnt/data/JWALDRON/Scripts/riboviz$ source bash/environment-tables.sh 
| Command-line tool | Version |
| ----------------- | ------- |
| Git | 2.17.1 |
| cURL | 7.77.0 |
| bedtools | 2.26.0 |
| hdf5tools (h5diff) | 1.10.6 |
| pigz | 2.6 |
| pandoc | 1.19.2.4 |
| GraphViz (dot) | 2.40.1 |
| zip | 3.0 |
| unzip | 6.00 |
| R | 4.1.0 |
| Python | 3.7.8 |
| Cutadapt | 3.4 |
| samtools | 1.9 |
| UMI-tools | 1.1.1 |
| Java (javac) | 10.0.2 |
| Java (java) | 10.0.2 |
| Nextflow | 20.10.0.5430 |
| Hisat2 | 2.1.0 |
| Bowtie | 1.2.3 |
 
| R Package | Version |
| --------- | ------- |
| Biostrings | 2.60.1 |
| devtools |  |
| git2r | 0.28.0 |
| glue | 1.4.2 |
| here | 1.0.1 |
| knitr | 1.33 |
| lintr |  |
| optparse | 1.6.6 |
| plotly | 4.9.4.1 |
| RcppRoll | 0.3.0 |
| rhdf5 | 2.36.0 |
| rmarkdown | 2.9 |
| roxygen2 |  |
| Rsamtools | 2.8.0 |
| rtracklayer | 1.52.0 |
| shiny | 1.6.0 |
| ShortRead | 1.50.0 |
| styler |  |
| testthat |  |
| tidyverse | 1.3.1 |
| withr | 2.4.2 |
 
| Python Package | Version | Package Manager |
| -------------- | ------- | --------------- |
| biopython | 1.78 | conda |
| cutadapt | 3.4 | conda |
| gffutils | 0.10.1 | conda |
| gitpython | 3.1.18 | conda |
| h5py | 2.10.0 | conda |
| nextflow | 20.10.0 | conda |
| pandas | 1.2.5 | conda |
| pycodestyle |  | conda |
| pylint |  | conda |
| pysam | 0.16.0.1 | conda |
| pytest | 6.2.4 | conda |
| pytest-cov |  | conda |
| pyyaml | 5.4.1 | conda |
| samtools | 1.9 | conda |
| sphinx |  | conda |
| umi_tools | 1.1.1 | conda |

**Comment by mikej888** [comment]
I see you have cutadapt 3.4. That might be the issue. Someone else had that issue, #380. Our workflow is currently designed for cutadapt 1.18. Their fix was to force a reinstall of cutadapt:
```console
$ conda install -c bioconda cutadapt --force-reinstall
```

**Comment by Joseph-Waldron** [comment]
OK, thanks Mike. I've just tried that but it has still resulted in version 3.4 being installed. Also, I'm a bit confused as it says in the documentation it should be v1.18 or later, isn't 3.4 more recent? Also, I think that's the default one that downloaded when I ran 

$ conda install -y -c bioconda cutadapt

as I have version 3.4 installed in my riboviz environment that I only just created but in my base environment I already have version 1.16

Many thanks
Joe

**Comment by mikej888** [comment]
We haven't updated the docs yet to record the constraint on 1.18. We haven't yet had a chance to explore why 3.4 gives issues.

**Comment by mikej888** [comment]
You could try (untested)
```console
$ conda install -y -c bioconda cutadapt=1.18
```

**Comment by Joseph-Waldron** [comment]
OK thanks Mike

I now have cutadapt 1.18 but still getting the same problem (although the order of error messages seems to be slightly different). It seems there's a problem with hisat2 and cutadapt. Output is copied below. Thanks again

(riboviz) jwaldron@R11-JWAL-L-V:/mnt/data/JWALDRON/Scripts/riboviz$ nextflow run prep_riboviz.nf -params-file vignette/vignette_config.yaml -ansi-log false
N E X T F L O W  ~  version 20.10.0
Launching `prep_riboviz.nf` [clever_becquerel] - revision: 6c6670470d
samples_dir: .
organisms_dir: .
data_dir: .
No such sample file (NotHere): example_missing_file.fastq.gz
[92/8073f6] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[5d/9eba1c] Submitted process > buildIndicesrRNA (yeast_rRNA)
[47/641071] Submitted process > cutAdapters (WTnone)
[49/4b9d11] Submitted process > cutAdapters (WT3AT)
Error executing process > 'buildIndicesORF (YAL_CDS_w_250)'

Caused by:
  Process `buildIndicesORF (YAL_CDS_w_250)` terminated with an error exit status (1)

Command executed:

  hisat2-build --version
  hisat2-build yeast_YAL_CDS_w_250utrs.fa YAL_CDS_w_250

Command exit status:
  1

Command output:
  (empty)

Command wrapper:
  ln: failed to create symbolic link 'yeast_YAL_CDS_w_250utrs.fa': Operation not supported

Work dir:
  /mnt/data/JWALDRON/Scripts/riboviz/work/92/8073f61aab6f41e81ee3c1d9ba66ea

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

Finished processing sample: null
Finished visualising sample: null
Workflow finished! (failed)
WARN: Killing pending tasks (2)
[47/641071] NOTE: Process `cutAdapters (WTnone)` terminated with an error exit status (1) -- Error is ignored

**Comment by mikej888** [comment]
If you follow the docs on debugging you can find out how to find out why buildIndicesORF and cutAdapters processes are failing including the output and error messages from when these are run:

https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-run-nextflow.md#debugging

**Comment by Joseph-Waldron** [comment]
OK thanks Mike

when I run

$ nextflow log clever_becquerel -f name -filter "status == 'FAILED'"

it returns

buildIndicesORF (YAL_CDS_w_250)
buildIndicesrRNA (yeast_rRNA)
cutAdapters (WTnone)

so we are having issues with both the buildIndices and the cutAdaptors scripts

When I run the following three commands I get the following, which I note all have exit status of 1, showing they failed

$ nextflow log clever_becquerel -f script,exit -filter "name == 'cutAdapters (WTnone)'"

        cutadapt --trim-n -O 1 -m 5 -a CTGTAGGCACC             -o trim.fq SRR1042855_s1mi.fastq.gz -j 0
        	1

$nextflow log clever_becquerel -f script,exit -filter "name == 'buildIndicesORF (YAL_CDS_w_250)'"

        hisat2-build --version
        hisat2-build yeast_YAL_CDS_w_250utrs.fa YAL_CDS_w_250
        	1

nextflow log clever_becquerel -f script,exit -filter "name == 'buildIndicesrRNA (yeast_rRNA)'"

        hisat2-build --version
        hisat2-build yeast_rRNA_R64-1-1.fa yeast_rRNA
        	1

However, to find out why, when I run the following I don't what I expect to

$ nextflow log clever_becquerel -f stdout,stderr -filter "name == 'cutAdapters (WTnone)'"

No such file: /mnt/data/JWALDRON/Scripts/riboviz/work/47/641071deac36fccf1014f2a683e49b/.command.out

$ nextflow log clever_becquerel -f stdout,stderr -filter "name == 'buildIndicesORF (YAL_CDS_w_250)'"

No such file: /mnt/data/JWALDRON/Scripts/riboviz/work/92/8073f61aab6f41e81ee3c1d9ba66ea/.command.out

$ nextflow log clever_becquerel -f stdout,stderr -filter "name == 'buildIndicesrRNA (yeast_rRNA)'"

No such file: /mnt/data/JWALDRON/Scripts/riboviz/work/5d/9eba1c476bacd1e0963081b561bfce/.command.out

When I go to one of these directories, the following files are present 

$ ls -a work/92/8073f61aab6f41e81ee3c1d9ba66ea/
.  ..  .command.begin  .command.log  .command.run  .command.sh  .exitcode

Any idea what's going wrong here, sorry I am not familiar with working with nextflow

Many thanks
Joe

**Comment by mikej888** [comment]
I don't understand why
```console
$ nextflow log clever_becquerel -f stdout,stderr -filter "name == 'buildIndicesORF (YAL_CDS_w_250)'"
```
returns
```
No such file: /mnt/data/JWALDRON/Scripts/riboviz/work/92/8073f61aab6f41e81ee3c1d9ba66ea/.command.out
```
when for you it seems to exist. Please do:
```console
$ cat work/92/8073f61aab6f41e81ee3c1d9ba66ea/.command.log
```
and paste in the content.

**Comment by Joseph-Waldron** [comment]
ln: failed to create symbolic link 'yeast_YAL_CDS_w_250utrs.fa': Operation not supported

**Comment by mikej888** [comment]
Please also try:
```console
$ cat work/92/8073f61aab6f41e81ee3c1d9ba66ea/
$ bash -x .command.run 
```

**Comment by Joseph-Waldron** [comment]
$ cat work/92/8073f61aab6f41e81ee3c1d9ba66ea/

cat: work/92/8073f61aab6f41e81ee3c1d9ba66ea/: Is a directory

$ bash -x .command.run

bash: .command.run: No such file or directory

**Comment by mikej888** [comment]
Sorry, I meant `cd` not `cat` i.e. change into the directory and run the command.

**Comment by Joseph-Waldron** [comment]
+ set -e
+ set -u
+ NXF_DEBUG=0
+ [[ 0 > 1 ]]
+ NXF_ENTRY=nxf_main
+ nxf_main
+ trap on_exit EXIT
+ trap on_term TERM INT USR2
+ trap '' USR1
+ [[ -n '' ]]
+ NXF_SCRATCH=
+ [[ 0 > 0 ]]
+ touch /mnt/data/JWALDRON/Scripts/riboviz/work/92/8073f61aab6f41e81ee3c1d9ba66ea/.command.begin
+ set +u
+ set -u
+ [[ -n '' ]]
+ nxf_stage
+ true
+ rm -f yeast_YAL_CDS_w_250utrs.fa
+ ln -s /mnt/data/JWALDRON/Scripts/riboviz/vignette/input/yeast_YAL_CDS_w_250utrs.fa yeast_YAL_CDS_w_250utrs.fa
ln: failed to create symbolic link 'yeast_YAL_CDS_w_250utrs.fa': Operation not supported
+ on_exit
+ exit_status=1
+ printf 1
+ set +u
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ true
+ exit 1

**Comment by mikej888** [comment]
OK the issue seems to be that you are not allowed to create symbolic links within your /mnt/ file system. Nextflow requires the ability to be able to create symbolic links. I have no idea about how to begin to resolve this. It would likely involve contacting whoever creates your mount to ask them to reconfigure it to allow you to create symbolic links within it.

Do you have another file system within which you could run RiboViz.

**Comment by Joseph-Waldron** [comment]
Oh ok, thanks Mike, at least we got to the bottom of this. I'll contact our IT department to see what they can do. Thanks again

**Comment by mikej888** [comment]
Sorry that you had to encounter possibly the most esoteric issue we've encountered with Nextflow so far.

**Comment by mikej888** [comment]
A short [Troubleshooting](https://github.com/riboviz/riboviz/blob/main/docs/user/prep-riboviz-run-nextflow.md#troubleshooting-ln-failed-to-create-symbolic-link) section was added to [rep-riboviz-run-nextflow.md in `main` prior to release 2.1.

**Comment by mikej888** [comment]
This is not RiboViz-specific and troubleshooting has been documented. Closing.
