### ISSUE TITLE
Add "calculate features" script to new RiboViz branch

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#40]
Fix and add the "calculate features" script to a new branch off the "develop" branch of https://github.com/riboviz/RiboViz/issues/new

**Comment by kavousan** [comment]
Premal to send a working script that we can interpret by 06 Sept.

**Comment by mikej888** [comment]
Tests will be required for this script at a future date.

**Comment by mikej888** [comment]
@shahpr add to https://github.com/riboviz/RiboViz, create a new branch of "develop" then add to the rmarkdown/ folder.
