### ISSUE TITLE
Add introduction to Linux `screen` command

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#401]
Linux's `screen` command provides a virtual terminal multiplexer. It allows us to run a number of different sessions (or windows, or virtual terminals) withina single terminal, or console, window. This can be useful if we do not have access to a graphical user interface with multiple windows, which is the case when using EDDIE.

**Comment by mikej888** [comment]
Added https://github.com/riboviz/riboviz/blob/develop/docs/user/using-linux-screen.md (produced for another project, also useful for EPCC MSc!)

**Comment by kavousan** [comment]
Great stuff. I seem to recall using screen when working on a flaky system/netwirk; I would easier pick up what I was doing when reconnecting.

I made some small typo edits, hopefully happy.

**Comment by mikej888** [comment]
@kavousan Thanks for fixing those typos!
