### ISSUE TITLE
Update documentation of ribogrid data by position and length to riboviz_outputs.md

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#426]
We need to check that the ribogrid data (read counts by position and length), as passed in to `metagene_start_ribogrid_by_length.pdf`, is described in [docs/user/riboviz_outputs.md](https://github.com/riboviz/riboviz/blob/develop/docs/user/riboviz_outputs.md). I don't know what it's called though! 

The current description is incorrect:
> using data that is saved in the `metagene_start_stop_read_counts.tsv` file.

We should check and fix this as part of #417. Requesting @FlicAnderson to address as part of resolving merge conflicts etc in that?

**Comment by 3mma-mack** [comment]
The file [gene_position_length_counts_5start.tsv ](https://github.com/riboviz/riboviz/blob/develop/docs/user/riboviz_outputs.md#gene_position_length_counts_5starttsv) contains read counts by position and length, and is described in riboviz-outputs.md beside the ribogrid plots.

**Comment by 3mma-mack** [comment]
Here is an example of the `gene_position_length_counts_5start.tsv` file

[gene_position_length_counts_5start.txt](https://github.com/riboviz/riboviz/files/7130872/gene_position_length_counts_5start.txt)

**Comment by ewallace** [comment]
I've created pull request #428 to address this, by correcting the reference.

BUT - wouldn't it be better to call that file `metagene_position_length_counts_5start.tsv`, because it is a metagene file? If you think so, let's fix that in #428 too.

**Comment by 3mma-mack** [comment]
That makes sense, I'll go through and make changes in the code and documentation today. The only bit I will struggle with is the `.dot` and `.svg` files as @mikej888 handled those last time.

**Comment by mikej888** [comment]
@3mma-mack please ping me when done and I can update the `.dot` and `.svg` files again.

**Comment by 3mma-mack** [comment]
I have updated file names and variables from `gene_position_length_counts_5start` to `metagene_position_length_counts_5start`, and tested that everything still works, which it does. 
@mikej888 would you be able to test and update the `.dot` and `.svg`, and the I think the issue is solved.

**Comment by mikej888** [comment]
@3mma-mack I've updated `.dot` and `.svg` and checked your updates and all seems fine.
