### ISSUE TITLE
Add documentation on how to develop further integration tests

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/riboviz#435]
Currently our developer documentation covers how developers can use the integration tests while developing riboviz, however it doesn't really cover **how developers can and should improve and build on our existing integration tests**.  

This would be a really useful addition which I think would help existing riboviz developers, as well as being useful in supporting outside contributions to riboviz.  

Identifying the process required by adding new tests: 
* to check for the existence of a new file 
* how best to test specific file types (for example check existance of a .pdf, vs checking within a .tsv file or other text formats) 
* follow naming formats/conventions to help keep things consistent.

**Comment by mikej888** [comment]
Update riboviz.test.integration.conftest and riboviz.test.integration.test_integration comments to provide more information on fixture injection, command-line parameters for these tests, and links into the relevant pytest documentation. Direct readers of the the developer docs to the comments in these files for more information.

**Comment by FlicAnderson** [comment]
Reminder: @FlicAnderson trying to get this PR checked next week!

**Comment by mikej888** [comment]
Merged #446.
