### ISSUE TITLE
Using riboviz on Amarel

### ISSUE THREAD

**Issue by acope3** [riboviz/RiboViz#453]
@dmbala has been working on getting riboviz working on Amarel (details for the computing environment: https://oarc.rutgers.edu/resources/amarel/). We are getting the following error: 

```
Error: 'h5writeAttribute.integer' is not an exported object from 'namespace:rhdf5'
Execution halted
```

Was this an issue anyone ran into when running on Eddie? @ewallace @mikej888 @FlicAnderson

@dmbala Can you add any details you think might be relevant? It might be helpful to upload the `.command.err` or `.command.out` files for the part of the pipeline where riboviz broke.

**Comment by ewallace** [comment]
I haven't seen that before. If you haven't already, I would suggest a thorough check of `rhdf5` package versions.

**Comment by dmbala** [comment]
The version of rhdf5 is `2.38.0`. Is there any specific version preferable? 

I ran the nextflow pipeline `nextflow run /env/riboviz/prep_riboviz.nf  -ansi-log false -params-file ribo_config.yaml` which completed a few and stopped at bamtoh5. Here is the stdout. 
```
[af/0bef6c] Submitted process > cutAdapters (WTnone)
[bb/67a326] Submitted process > buildIndicesORF (YAL_CDS_w_250)
[07/1efaf5] Submitted process > buildIndicesrRNA (yeast_rRNA)
[84/25fd69] Submitted process > cutAdapters (WT3AT)
[1a/eacc1f] Submitted process > createVizParamsConfigFile
[f0/cbf391] Submitted process > createInteractiveVizParamsConfigFile
[5b/0d4404] Submitted process > hisat2rRNA (WTnone)
[32/607f4c] Submitted process > hisat2rRNA (WT3AT)
[a1/5bfdb1] Submitted process > hisat2ORF (WTnone)
[18/e810b8] Submitted process > hisat2ORF (WT3AT)
[de/d73ae6] Submitted process > trim5pMismatches (WTnone)
[2f/2a5327] Submitted process > trim5pMismatches (WT3AT)
[5f/56f2c0] Submitted process > samViewSort (WTnone)
[24/75fcae] Submitted process > samViewSort (WT3AT)
[2d/69971b] Submitted process > outputBams (WTnone)
[b8/26dbf3] Submitted process > outputBams (WT3AT)
[f0/54246d] Submitted process > makeBedgraphs (WTnone)
[6c/fcfcf6] Submitted process > bamToH5 (WTnone)
[6c/fcfcf6] NOTE: Process `bamToH5 (WTnone)` terminated with an error exit status (1) -- Error is ignored
[25/f904d4] Submitted process > bamToH5 (WT3AT)
[25/f904d4] NOTE: Process `bamToH5 (WT3AT)` terminated with an error exit status (1) -- Error is ignored
[52/b0f91e] Submitted process > makeBedgraphs (WT3AT)
No sample was processed successfully
```
The output from `command.err` is 
```
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
Error: 'h5writeAttribute.integer' is not an exported object from 'namespace:rhdf5'
Execution halted
```

**Comment by mikej888** [comment]
riboviz was tested with rhdf5 2.30.1 (https://github.com/riboviz/riboviz/blob/main/docs/user/install.md#dependencies-overview) and also 2.34.0. For the latter, one would expect the workflow to succeed on the vignette but for 2 tests to fail [see "Troubleshooting: `FAILED ... test_bam_to_h5_h5[...]` test failures" in
https://github.com/riboviz/riboviz/blob/main/docs/developer/integration-tests.md]. But your problem doesn't seem to be that and is not one I've seen before.

I did a web search for "During startup - Warning messages:". This gives numerous hits for both this warning and "Setting LC_CTYPE" and the other messages you see. For example, https://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c. These warnings seem to arise from R and relate to locales for character encodings. Similarly I searched for "During startup - Warning messages:" "cluster" and this gave https://discourse.mc-stan.org/t/error-running-r-code-on-linux-computing-cluster/4690.

It's unclear whether the warnings:
```
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
```
are causing
```
Error: 'h5writeAttribute.integer' is not an exported object from 'namespace:rhdf5'
Execution halted
```
or these are two separate issues. It might be worth following advice in https://github.com/riboviz/riboviz/blob/main/docs/developer/dev-nextflow.md#debugging to rerun `bam_to_h5.R` directory and try to find out where in `bam_to_h5.R` the error is being raised.

**Comment by dmbala** [comment]
The warnings LC_CTYPE.... disappeared when setting the variable LC_ALL=C.UTF-8.  However, the error remains the same. 
I am trying to rebuild the docker image with the old version of rhdf5 (2.30), but there seems to be some conflicts.  I think it is better to run the docker or singularity image directly for testing purposes. This way I can get the setup going on the cluster with the available image.  Do we have the docker or singularity image available on the hub?

**Comment by mikej888** [comment]
As far as I know, no built Docker or Singularity image was deposited on DockerHub. @canuse did you deposit a built image?

**Comment by dmbala** [comment]
Okay, after downgrading the package rhdf5 to 2.30 version, the pipeline finished successfully.  I am keeping the working image on the hub: https://hub.docker.com/r/dmbala/riboviz

This is done. Please resolve this issue. Thank you.
