### ISSUE TITLE
Issue with `rhdf5::h5writeAttribute.integer` in `bam_to_h5_functions.R`

### ISSUE THREAD

**Issue by acope3** [riboviz/RiboViz#477]
In previous versions of `rhdf`, `h5writeAttribute.integer` could be accessed via `rhdf5::h5writeAttribute.integer`. As of version `rhdf5 v2.40.0`, we must now use `rhdf5:::h5writeAttribute.integer` (note the third `:`). I assume we chose `h5writeAttribute.integer` to help with efficiency. Is this how we want to proceed going forward, or do we want to switch to `h5writeAttribute`? @ewallace, do you have thoughts?

**Comment by ewallace** [comment]
Fixed by #480
