### ISSUE TITLE
Assess workflow language options

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#48]
Review CWL, NextFlow, SnakeMake in terms of:
 
* Ease of download, install, use
 * Current user/developer base.
 * Envisaged user/developer base 6 months, 2 years from now.

Decide whether to use one of these to implement the RiboViz pipeline and, if so, an estimate as to how much effort this would incur.

**Comment by mikej888** [comment]
See [RiboViz and Common Workflow Language (CWL)](https://github.com/riboviz/bbsrc-nsf/blob/master/docs/reports/201908-ssi-review/SsiRiboVizCwl.md) done during August 2018 SSI review.

**Comment by mikej888** [comment]
EPCC's Rosa Filgueira has used [Pegasus](https://pegasus.isi.edu/) and [CWL](https://www.commonwl.org/)

**Comment by mikej888** [comment]
Criteria should include: ability to iterate over samples output post-demultiplexing, ability to collate TPMs once sample-specific processing has completed, support for capturing log files, a dry-run option, generating bash shell scripts replicating the steps run.

**Comment by mikej888** [comment]
Created https://github.com/riboviz/workflows to hold notes and examples. Includes Snakemake notes and example Snakefile.

**Comment by ewallace** [comment]
[Informal article on workflows](https://www.nature.com/articles/d41586-019-02619-z).

**Comment by mikej888** [comment]
Notes on [Snakemake and CWL](https://github.com/riboviz/workflows/blob/master/cwl/SnakemakeCwl.md). Contrary to my naive assumption Snakemake does not export a CWL with steps for each step in the Snakemake file. It exports a CWL workflow with a step that invokes Snakemake. I ran the Nature Snakemake example, in the article above. I exported it using the `snakemake --export-cwl` command mentioned in the article but can't get it to run under cwltool or Toil. I raised an issue on the repository for the Nature example.

**Comment by mikej888** [comment]
Started implementing a subset of the RiboViz workflow using CWL. 
https://github.com/riboviz/workflows/tree/master/cwl currently has:

* A simple tool wrapper I wrote for `cutadapt`.
* A basic workflow to invoke `hisat2-build` (which uses a third-party open source tool wrapper) plus `cutadapt` using the tool wrapper above.
* A job file, which provides configuration for the workflow.

I plan to spend 1 more day on CWL then 2 days on NextFlow.

**Comment by ewallace** [comment]
Mick Watson (Roslin) [blogpost on why we should use workflows and containers](http://www.opiniomics.org/the-three-technologies-bioinformaticians-need-to-be-using-right-now/)

**Comment by mikej888** [comment]
Summary of observations/recommendations to date (12/03/2020) (from https://github.com/riboviz/workflows/blob/master/README.md):

Snakemake:

* Straightforward to learn.
* Bulk of RiboViz workflow was prototyped in Snakemake in a day.
* Prototype would take 2-3d to complete as an implementation of the RiboViz workflow. Adding support for `riboviz.tools.demultiplex_fastq` would be the most significant addition.

Snakemake and CWL:

* A Snakemake "hello world" example in a *Nature* article was exported to CWL, using the command in the article, but this could not be run using cwltool or Toil. It is unclear as to how this can be made to run.
* A CWL file exported from Snakemake is a simple workflow that invokes Snakemake itself, rather than being the CWL equivalent of the workflow steps implemented within a Snakefile.

CWL:

* More effort to learn.
* 3 steps of the RiboViz workflow were prototyped in a day.
* Prototype would take 2-3 weeks to complete.
* No support for conditional execution of steps as yet.
* "edit-compile-run" development cycle iss very slow.
* Developers would need to know JavaScript.
* Tool wrappers can be verbose for what are single command-line invocations e.g. the basic `cutadapt` wrapper in `cutadapt.cwl` is 47 lines.
* Workflows can be verbose e.g. the 3 step CWL workflow is 58 lines, whereas the 15 step Snakemake workflow is 220 lines (which are elegant in their conciseness).

General:

* Our Python workflow has custom error handling. Users using Snakemake and CWL will need to rely on their error reporting which may be more verbose, or, in the case of Toil, a possibly impenetrable stack trace. We can extend our documentation with the symptoms of common errors (e.g. missing files, missing configuration, step fails) and how to resolve these.

Recommendation to date:

* Adopt Snakemake - the work requires little effort to complete.
* Snakemake is a popular tool within the community.
* Rather than try and guess what the user community might want, ask the user community about their views on CWL.

An evaluation of Nextflow is pending.

**Comment by mikej888** [comment]
Read through Nextflow docs. It seems well designed to scale to HPC and Cloud environments. It is more challenging to write, partly due to its richness and the reference-style (rather than tutorial-style) nature of the docs. Nextflow scripts are similar in style, readability and verbosity to Snakemake - tasks and their inputs and outputs are defined (in Groovy, a Python-style language over Java) and Nextflow uses the inputs and outputs to determine the tasks to run. Aims to complete the evaluation next week.

**Comment by mikej888** [comment]
Completed assessment. Recommendation, from [workflows/README.md](https://github.com/riboviz/workflows/blob/master/README.md):

> I'd recommend adopting Nextflow over Snakemake for the following reasons:
>
> * While it would require more time to complete a port of the RiboViz workflow to Nextflow than to Snakemake, the time required is not significant (i.e. < 2 weeks).
> * Nextflow feels far richer in terms of its features and expressivity.
> * The execution of each task in isolated directories is very useful for debugging.
> * Nextflow's built-in support for, and documentation around, Docker, Singularity, cluster and cloud execution, seems more comprehensive than that of Snakemake.
> * While Nextflow and Snakemake are both very popular tools within the bioinformatics community, Nextflow seems to have the slight edge (based on Notes on Workflow Options 28/02/2020).

Short-cuts to notes on each and sample workflows (the READMEs describe how to run these).

* [RiboViz and Snakemake](https://github.com/riboviz/workflows/blob/master/snakemake/README.md), [Snakefile](https://github.com/riboviz/workflows/blob/master/snakemake/Snakefile)
* [RiboViz and Nextflow](https://github.com/riboviz/ workflows/blob/master/nextflow/README.md), [riboviz.nf](https://github.com/riboviz/workflows/blob/master/nextflow/riboviz.nf)

Comments welcome from @ewallace, @FlicAnderson

**Comment by kavousan** [comment]
US team happy with the approach.
