### ISSUE TITLE
Deprecate Python 2 support

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#54]
Python 2 comes to the end of its supported life in 2020 (see [PEP 373 Python 2.7 Release Schedule](https://legacy.python.org/dev/peps/pep-0373/)) and there will be no Python 2.8.

Decide when RiboViz will no longer support Python 2.

**Comment by mikej888** [comment]
Replace IOError and OSError with FileNotFoundError in any files where the latter is the intended exception.

**Comment by kavousan** [comment]
We want to abandon Python 2; UMI Tools does not support it.

**Comment by kavousan** [comment]
@lianafaye has no problem with deprecating this.

**Comment by mikej888** [comment]
Branched deprecate-py2-54 from develop
