### ISSUE TITLE
generate_stats_fig.R doesn't handle missing yeast_features.tsv 

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/RiboViz#66]
Currently pipeline blocked when dataset does not include a features file (likely in other organisms e.g. Candida albicans at Muzzey 2014 dataset). Pipeline doesn't handle missing file, and fails samples.

Ideally fix would handle missing features file, note somewhere (documentation?) what stats/graphs will not be produced by generate_stats_fig.R as a result, and continue to produce the output files, concluding with the collated TPMs.

Adjacent issue to be aware of: #32 Refactor generate_stats_fig.R

**Comment by FlicAnderson** [comment]
Created new branch to fix this in: handle-missing-features-file-66

**Comment by kavousan** [comment]
Should be easier to fix/mostly fixed when #72 is merged.
