### ISSUE TITLE
Create examples repository

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#75]
Create "examples" repository to complement "riboviz" repository. This repository will contain:

* YAML configuration files for RiboViz.
* Data files (at least for the short term and if data volume is acceptable, for longer term options, see riboviz/bbsrc-nsf/issues/5 and [Data storage options](https://github.com/riboviz/bbsrc-nsf/blob/master/docs/reports/DataStorageOptions.md)
* Documentation and notebooks on how data files in the repository were prepared (or from where they originate) and how to run RiboViz on these using the YAML configuration files.
* Content grouped by organisms - for each organism there can be many different YAML configuration files which use the same transcriptome files.

**Caution:** any repository should not exceed 1GB in size. GitHub's [What is my disk quota?](https://help.github.com/en/github/managing-large-files/what-is-my-disk-quota) comments "If your repository exceeds 1GB, you might receive a polite email from GitHub Support requesting that you reduce the size of the repository to bring it back down."

**Comment by ewallace** [comment]
The [/riboviz/example-datasets](https://github.com/riboviz/example-datasets/) repository has been created, and issues pertaining to that repor will now be tracked separately.

To clarify, we will *not* include the GB-scale fastq data on that repository. We *will* include riboviz-style transcriptome and gff files, and contaminant/rRNA fasta files.
