### ISSUE TITLE
Write prep_riboviz.py configuration for simulated fastq records

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#77]
simulatefastq-36 has riboviz/tools/create_fastq_examples.py which produces test data building up to Duncan & Mata-style:

* `data/simdata_UMI3_4nt.fastq` - 4nt UMI at 3' end
* `data/simdata_UMI5and3_4nt_adaptor.fastq` - 4nt UMI at 3' end and another at 5' end
* `data/simdata_UMI5and3_4nt.fastq`- 4nt UMI at 3' end and another at 5' end, and adaptor

These .fastqs were designed so they could be run with vignette index files `yeast_CDS_w_250utrs.fa/.gff3`, and the adaptor from the vignette, because the "reads" align to sequences in the `.fa`
They will need to be gzipped and the yaml edited as appropriate.

_Originally posted by @ewallace in https://github.com/riboviz/RiboViz/issues/58#issuecomment-527676381_

**Comment by mikej888** [comment]
I created a new YAML configuration, `vignette/vignette_simdata_config.yaml`, for the test data. The differences to the default configuration are as follows:
```console
$ diff vignette/vignette_config.yaml  vignette/vignette_simdata_config.yaml 
1c1
< dir_in: vignette/input # input directory
---
> dir_in: data/ # input directory
16,18c16
<   WTnone: SRR1042855_s1mi.fastq.gz
<   WT3AT: SRR1042864_s1mi.fastq.gz
<   NotHere: example_missing_file.fastq.gz # prepRiboviz should give error message for missing files
---
>   simdata: simdata_UMI5and3_4nt_adaptor.fastq 
```
Running fails at generate_stats_figs.R:
```console
$ python -m riboviz.tools.prep_riboviz rscripts/ vignette/vignette_simdata_config.yaml
...
Create summary statistics and analyses plots. Log: vignette/logs/20190930-063308/simdata_10_generate_stats_figs.log
Problem processing sample: simdata
...
AssertionError: ['Rscript', '--vanilla', 'rscripts/generate_stats_figs.R', '--Ncores=1', 
  --MinReadLen=10', '--MaxReadLen=50', '--Buffer=250', '--PrimaryID=Name',
  '--dataset=vignette', '--hdFile=vignette/output/simdata.h5', 
  '--out_prefix=vignette/output/simdata', '--orf_fasta=vignette/input/yeast_YAL_CDS_w_250utrs.fa',
  '--rpf=True', '--orf_gff_file=vignette/input/yeast_YAL_CDS_w_250utrs.gff3',
  '--dir_out=vignette/output', '--t_rna=data/yeast_tRNAs.tsv',
  '--codon_pos=data/yeast_codon_pos_i200.RData', '--features_file=data/yeast_features.tsv',
  '--do_pos_sp_nt_freq=True'] failed with exit code 1
Finished processing 1 samples, 1 failed
```
The invocation (from `run_riboviz_vignette.sh`) is:
```
Rscript --vanilla rscripts/generate_stats_figs.R --Ncores=1 --MinReadLen=10 \
  --MaxReadLen=50 --Buffer=250 --PrimaryID=Name --dataset=vignette \
  --hdFile=vignette/output/simdata.h5 --out_prefix=vignette/output/simdata \
  --orf_fasta=vignette/input/yeast_YAL_CDS_w_250utrs.fa --rpf=True \
  --orf_gff_file=vignette/input/yeast_YAL_CDS_w_250utrs.gff3 --dir_out=vignette/output \
  --t_rna=data/yeast_tRNAs.tsv --codon_pos=data/yeast_codon_pos_i200.RData \
  --features_file=data/yeast_features.tsv --do_pos_sp_nt_freq=True
```
The log shows:
```console
$ cat vignette/logs/20190930-063308/simdata_10_generate_stats_figs.log
...
[1] "Starting: Check for 3nt periodicity"
Saving 7 x 7 in image
[1] "Completed: Check for 3nt periodicity"
[1] "Starting: Distribution of lengths of all mapped reads"
Saving 7 x 7 in image
[1] "Completed: Distribution of lengths of all mapped reads"
[1] "Starting: Biases in nucleotide composition along mapped read lengths"
[1] "Completed nucleotide composition bias table"
[1] "Starting: Position specific distribution of reads"
Saving 7 x 7 in image
Warning message:
Removed 1000 rows containing missing values (geom_path). 
[1] "Completed: Position specific distribution of reads"
[1] "Starting: Calculate TPMs of genes"
[1] "Starting: Correlations between TPMs of genes with their sequence-based features"
Saving 7 x 7 in image
Error: Faceting variables must have at least one value
Execution halted
```
The following files had been created:
```console
$ ls -1 vignette/tmp/
simdata_nonrRNA.fq
simdata_orf_map_clean.sam
simdata_orf_map.sam
simdata_rRNA_map.sam
simdata_trim.fq
simdata_unaligned.fq
$ ls -1 vignette/output/
simdata_3nt_periodicity.pdf
simdata_3nt_periodicity.tsv
simdata.bam
simdata.bam.bai
simdata_features.pdf
simdata.h5
simdata_minus.bedgraph
simdata_plus.bedgraph
simdata_pos_sp_nt_freq.tsv
simdata_pos_sp_rpf_norm_reads.pdf
simdata_pos_sp_rpf_norm_reads.tsv
simdata_read_lengths.pdf
simdata_read_lengths.tsv
simdata_tpms.tsv
```
For the PDFs:

* `simdata_read_lengths.pdf`: bar at Length = 38 of height 1.
* `simdata_3nt_periodicity.pdf`: 5' graph has spike at 0, read counts 1; 3' graph has read counts 0
* `simdata_pos_sp_rpf_norm_reads.pdf`: graphs are empty
* `simdata_features.pdf`: PDF is blank

@ewallace any suggestions?

**Comment by ewallace** [comment]
Lengths of simdata reads should be 28nt and 30nt, if UMIs were *removed*. The extra 4nt of UMIs is likely to prevent alignment, which would explain why only a single read aligned. So we should have another file, `data/simdata_noUMI.fastq`, that runs for the existing vignette without deduplication. Then the other data files will work properly only when we have extracted the UMIs before alignment.

The error in `generate_stats_figs.R` occurs during `features_plot`. Faceting error means that ggplot2's `facet_wrap` is trying to plot a subgraph for every value of a variable, but it doesn't find any values. This is likely to come from the filtering step:

```
plot_data <- merge(features,tpms,by="ORF") %>%
    filter(readcount >= count_threshold, !is.na(ORF)) 
```

Which removes all genes with readcount below `count_threshold`, which has a default value of 64. Should be fixed by setting `count_threshold <- 1` in the config yaml.

**Comment by mikej888** [comment]
Commited changes to develop branch - 0983b49 - to allow `count_threshold` argument to `generate_stats_figs.R` to be specified via configuration parameter.

Commited changes to simulatefastq-36 branch - 6f9296d - extending `create_fastq_examples.py` to create fastq files post-UMI extraction. There are two new files created: `simdata_extracted_UMI5and3_4nt.fastq` and `simdata_extracted_UMI3_4nt.fastq` - these share the same reads but they differ in their quality scores as the data they are derived from - data that is saved in `simdata_UMI5and3_4nt.fastq` and `simdata_UMI3_4nt.fastq` - differ in their quality scores due to the way `create_fastq_examples.py` creates these. The commit also has a new `vignette/vignette_simdata_config.yaml` file.

```console
$ diff vignette/vignette_config.yaml  vignette/vignette_simdata_config.yaml
1c1
< dir_in: vignette/input # input directory
---
> dir_in: data/ # input directory
16,18c16,17
<   WTnone: SRR1042855_s1mi.fastq.gz
<   WT3AT: SRR1042864_s1mi.fastq.gz
<   NotHere: example_missing_file.fastq.gz # prepRiboviz should give error message for missing files
---
>   simdata5and3: simdata_extracted_UMI5and3_4nt.fastq
>   simdata3: simdata_extracted_UMI3_4nt.fastq
35c34
< count_threshold: 64 # Remove genes with a read count below this threshold, when generating statistics and figures
---
> count_threshold: 1 # Remove genes with a read count below this threshold, when generating statistics and figures
```

Run:

```console
rm -rf vignette/index vignette/tmp vignette/output/ vignette/logs/ riboviz.*.log run_riboviz_vignette.sh 
python -m riboviz.tools.prep_riboviz rscripts/ vignette/vignette_simdata_config.yaml
```

> Lengths of simdata reads should be 28nt and 30nt, if UMIs were removed.

* `simdata5and3_read_lengths.pdf` has Lengths=28, Counts=5 and Lengths=30, Counts=4: OK
* `simdata3_read_lengths.pdf` has Lengths=28, Counts=4 and Lengths=30, Counts=4:  OK
