### ISSUE TITLE
Replace NULL with NA in bam_to_h5.R make_option calls

### ISSUE THREAD

**Issue by mikej888** [riboviz/riboviz#78]
bam_to_h5.R defines

```R
    make_option("--SecondID", type="character", default=NULL,
        help="Secondary gene IDs to access the data (COX1, EFB1, etc.)"),
   
    make_option("--orf_gff_file", type="character", default=NULL,
        help="GFF2/GFF3 annotation file"),
```

and uses `is.null(SecondID)` checks. Update to

* Set the default values to be NA.
* Remove the check that SecondID is a string "NULL".
* Replace use of `is.null` with `is.na` throughout (as done in `generate_stats_figs.R`) in branch develop.

Update  `prep_riboviz.py` to construct the call to `bam_to_h5.R`, handling these optional values, in the same way as it does for `generate_stats_figs.R`.

Arose from #66.

**Comment by FlicAnderson** [comment]
Fix in refactoring of `bam_to_h5.R` #61 if not before!

**Comment by mikej888** [comment]
Completed as part of Refactor bam_to_h5.R #61. See commit c8b325b in branch [refactor-bam-to-h5-61](https://github.com/riboviz/riboviz/tree/refactor-bam-to-h5-61).

* `bam_to_h5.R` `--secondary-id` option has default value `NA`. Checks for `is.null` replaced with `is.na`.
* `test_bam_to_h5.R` function `RunSamToBamToH5` constucts `bam_to_h5.R` invocation to include `--secondary-id` if `secondary_id` is not `NA`.
* `prep_riboviz.nf|.py` only add `--secondary-id=<secondary_id>` to `bam_to_h5.R` invocation if configuration defines `secondary_id` and it is not `null|NULL`.
