### ISSUE TITLE
Ribogrid bar plot

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#81]
Related to #68, but to plot periodicity brokedn up by read length. Like [fig. 1 in the RiboCode paper](https://academic.oup.com/view-large/figure/117258100/gky179fig1.jpg). 

_RiboCode is an ORF-finder that scores translation of ORFs based on reads being in a correct frame_

**Comment by FlicAnderson** [comment]
Checked branch ribogrid-plot-68 at commit 495bd168d, regression tests all good and exit codes all fine. 

Merged in current develop into ribogrid-plot-68 (commit 076480d), re-ran regression tests and exit code test, all fine.

Pushed up to origin but not yet pull-requesting until I've figured out whether any readability/stylistic changes to generate_stats_figs.R made during review should be split off as separate branch/pull request or included with this one. 

Next I'll do additional reviewing and style checking, to follow [Google R Style Guide](https://google.github.io/styleguide/Rguide.html)
