### ISSUE TITLE
Rename config.yaml variables for consistency

### ISSUE THREAD

**Issue by FlicAnderson** [riboviz/RiboViz#86]
Fixing variable names in config.yaml for case consistency (capitalisation, snake_case).  Would have knock-on benefits for improving consistency in parsed options in R scripts like generate_stats_figs.R as part of #32 

Examples of inconsistency: 
`MaxReadLen`, `isTestRun`, `Buffer`. 

Example fixes:
`max_read_len`, `is_test_run`, `buffer` (also see renaming/scope issue for this variable #83).

**Comment by ewallace** [comment]
This needs to work with functions inside `generate_stats_figs.R` that we can't have default names of variables *inside* functions be the same as the default names outside.

I think this is why all the different `fid` vs `ffid` names came to be. What's the best workaround?

E.G. https://stackoverflow.com/questions/4357101/promise-already-under-evaluation-recursive-default-argument-reference-or-earlie

**Comment by mikej888** [comment]
To complement this a  converter script to convert a file with the old names to one with the new names.

**Comment by mikej888** [comment]
```
python upgrade_config.py old.yaml new.yaml"
```

Read in YAML, convert keys to new names, write out YAML. 

Updating configuration parameters needs update of `prep_riboviz.py` and documentation.

Run `prep_riboviz` with `--dry-run` to check if YAML has been converted correctly.

**Comment by mikej888** [comment]
Commits 5b4ddbd .. 390a925 in [config-86](https://github.com/riboviz/RiboViz/tree/config-86) branch have refactored .py and .R scripts to support command-line parameters consistent with bash and other command-line tools.:

* A single alphanumeric character prefixed by a hyphen e.g. `-v`, `-c 123`, `-s GATC`.
* A sequence of lower-case alphanumeric characters, prefixed by two hyphens and delimited by hyphens e.g. `--verbose`, `--control=123`, `--match-sequence=GATC`.

A section on Command-line parameters has been added to developer-guide.md.

YAML configuration files use snake_case (all lower-case, underscore-delimited) with the names, where appropriate, consistent with the command-line tool parameters.

**Comment by mikej888** [comment]
Next task is developing an "update" script to take YAML files from RiboViz 1.0, 1.1, and the current develop branch and apply necessary parameter updates (and, for 1.0, 1.1, to add the additional parameters now expected)

**Comment by mikej888** [comment]
Added `riboviz/test/tools/test_upgrade_config_file.py` which tests `upgrade_config_file.py` on `vignette_config.yaml` copies from 1.0.0, 1.1.0, current develop branch, plus `simdata_umi_config.yaml` and `simdata_multiplex_config.yaml`. Validation is done against current versions of the files in this branch.

Added "Upgrade configuration files from RiboViz 1.x" how-to in `docs/upgrade-1x.md`.

**Comment by mikej888** [comment]
Done, will create pull request in new year.

**Comment by mikej888** [comment]
Merged via pull request #124.

**Comment by mikej888** [comment]
@flic to test scripts on live data from the YAML files she has written for sample datasets.

**Comment by ewallace** [comment]
@FlicAnderson please update us on the tests here - do we need to fix something, or can we close the issue?

**Comment by FlicAnderson** [comment]
Tested branch on live data, with script working nicely on updating yamls from W-Sc_2016 runs. Outputs all looking good. Confirming they're good to run with :)

Updated the branch to latest develop, but latest develop already contains these changes.

**Comment by mikej888** [comment]
@FlicAnderson  Thanks :-)

**Comment by kavousan** [comment]
The script to upgrade is on https://github.com/riboviz/riboviz/blob/master/riboviz/tools/upgrade_config_file.py
