### ISSUE TITLE
Calculate read frame

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#89]
We need to count reads mapping to frames 0/1/2 on an ORF. This should happen in the same level as functions in `generate_stats_figs.R` and can be coded in R.

This is an essential QC step. Also an enhancement needed for @ewallace's immediate work on another project.

**Comment by ewallace** [comment]
Working to do this in branch `read-frame-89`. Commit `8563f8d` has tidyverse approach code that runs but is not much tested.

@FlicAnderson can we discuss? This introduces a new tidyverse package dependency, `purrr`. And I need your help to check for style.

Makes some progress also on #32

**Comment by ewallace** [comment]
@ewallace needs to fix so that the option 
```asite_disp_length=data.frame(read_length=c(28,29,30),
                                                          asite_disp=c(12,12,12))```
is defined, and check the vignette runs.

**Comment by ewallace** [comment]
Commit `81c1c23` ensures that the vignette runs:
* defines config option `asite_disp_length_file`
* if no `asite_disp_length_file` supplied, `generate_stats_figs.R` treats as NA and skips the code block
* if `asite_disp_length_file` defined, counts read frame for every CDS defined in the gff file.
* runs on vignette data and (informal check) the majority of reads are in frame 0 on high-expression genes YAL038W, YAL005C, etc. 

Still needs
* check that the 12nt A-site disp is adequate
* check for R style
* check for python style
* update vignette documentation
* test on full-size data

And enhancements
* graphic output, maybe boxplot of prop. in frame for all above-threshold genes?
* statistical test, maybe the wilcoxon-type test implemented in RiboCode?

**Comment by kavousan** [comment]
Should take @ewallace another 1-3 weeks; then to seek help for writing the tests.

**Comment by ewallace** [comment]
* @ewallace implemented wilcoxon test.
* we realized that existing `asite_disp_length_file` works and corrected W-Sc_2016 data.
* @FlicAnderson ran on G-Sc-2014 (pre-wilcoxon test) and looked good.

Next steps:
* After reviewing #58, @FlicAnderson to merge `use-umi-tools-dedup-58` into `read-frame-89`
* Test-run on W-Sc_2016.

Aim to review and close issue by week commencing 11th Nov.

**Comment by kavousan** [comment]
@FlicAnderson reran this with G-Sc-2014 including wilcoxon test; looking good. 

@FlicAnderson to:
* double-check the output; 
* augment regression test; 
* review the doc to ensure it covers things; 
* run on W-Sc_2016 to validate;
  * to validate, plot distribution of p-values against TPMs or read-counts
* issue pull-request;
* and close.

The validation method will likely feed into #56.

**Comment by FlicAnderson** [comment]
Update: 

Pushed commits with documentation edits and augmented regression test, though workflow.pdf still to edit.

Still need to run on W-Sc_2016 dataset to validate (after merging in UMI capabilities from branch use-umi-tools-58 / develop if pull request #98 has gone through), and then plot p-values vs TPMs and read-counts from outputs of that run.

**Comment by kavousan** [comment]
This should be the focus this week.

**Comment by FlicAnderson** [comment]
P-values of frames vs tpms and read counts plotted from outputs of W-Sc_2016 dataset run with branch read-frame-89.  I've put it [here](https://github.com/riboviz/scratch/blob/master/read-frame-89/verify_read-frame-89.Rmd) for now. @ewallace can you check if this was what you needed and whether it seems to give what you'd expected?

Made last change to read-frame-89 documentation (updated workflow.pdf) in commit 997bfef7.  
If the p-values plots have worked out well, then this branch is ready for pull request. 

I can create this PR as soon as @ewallace is happy with verification of outputs.

**Comment by FlicAnderson** [comment]
Created pull request, ready to review and merge with develop: https://github.com/riboviz/RiboViz/pull/103

**Comment by ewallace** [comment]
We noticed that `yeast_standard_asite_disp_length.txt` is incorrect, should have *15* in as the a-site displacement.

```
read_length	asite_disp
28	15
29	15
30	15
```

@ewallace's error, he will fix and update. Might require updating regression tests. @FlicAnderson, should we revoke pr to do this or not?

**Comment by mikej888** [comment]
Moved back to In progress pending bug fix.

**Comment by ewallace** [comment]
I updated the numbers to 15. Request @mikej888 to update regression tests and then update pr #103.

**Comment by mikej888** [comment]
Regression test values differ for WTnone_3ntframe_bygene.tsv and WT3AT_3ntframe_bygene.tsv.  Regression test code needs no updates. I'll create a new regression test data bundle once this, use-umi-tools-deplex-84 and docs-80 branches have been merged,
